
package com.digikey.services.searchws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SearchServiceSoap", targetNamespace = "http://services.digikey.com/SearchWS")
@XmlSeeAlso({
    com.digikey.services.searchws.ObjectFactory.class,
    org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.ObjectFactory.class
})
public interface SearchServiceSoap {


    /**
     * Searches for alternate packaging options for a Digi-Key Part Number
     * 
     * @param digikeyPartNumber
     * @return
     *     returns com.digikey.services.searchws.AlternatePackagingOptions
     */
    @WebMethod(operationName = "GetAlternatePackagingByDigikeyPartNumber", action = "http://services.digikey.com/SearchWS/GetAlternatePackagingByDigikeyPartNumber")
    @WebResult(name = "GetAlternatePackagingByDigikeyPartNumberResult", targetNamespace = "http://services.digikey.com/SearchWS")
    @RequestWrapper(localName = "GetAlternatePackagingByDigikeyPartNumber", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.GetAlternatePackagingByDigikeyPartNumber")
    @ResponseWrapper(localName = "GetAlternatePackagingByDigikeyPartNumberResponse", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.GetAlternatePackagingByDigikeyPartNumberResponse")
    public AlternatePackagingOptions getAlternatePackagingByDigikeyPartNumber(
        @WebParam(name = "digikeyPartNumber", targetNamespace = "http://services.digikey.com/SearchWS")
        String digikeyPartNumber);

    /**
     * Accepts a Digi-Key Part Number, Site, and Language and returns a ProductInfo record that consists of component specifications, quantity on hand, price breaks, etc. for that part number.
     * 
     * @param site
     * @param language
     * @param digikeyPartNumber
     * @param customerNumber
     * @return
     *     returns com.digikey.services.searchws.EDAProductInfoInt
     */
    @WebMethod(operationName = "GetProductInfoByDigikeyPartNumberSiteLanguage", action = "http://services.digikey.com/SearchWS/GetProductInfoByDigikeyPartNumberSiteLanguage")
    @WebResult(name = "GetProductInfoByDigikeyPartNumberSiteLanguageResult", targetNamespace = "http://services.digikey.com/SearchWS")
    @RequestWrapper(localName = "GetProductInfoByDigikeyPartNumberSiteLanguage", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.GetProductInfoByDigikeyPartNumberSiteLanguage")
    @ResponseWrapper(localName = "GetProductInfoByDigikeyPartNumberSiteLanguageResponse", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.GetProductInfoByDigikeyPartNumberSiteLanguageResponse")
    public EDAProductInfoInt getProductInfoByDigikeyPartNumberSiteLanguage(
        @WebParam(name = "digikeyPartNumber", targetNamespace = "http://services.digikey.com/SearchWS")
        String digikeyPartNumber,
        @WebParam(name = "customerNumber", targetNamespace = "http://services.digikey.com/SearchWS")
        int customerNumber,
        @WebParam(name = "site", targetNamespace = "http://services.digikey.com/SearchWS")
        String site,
        @WebParam(name = "language", targetNamespace = "http://services.digikey.com/SearchWS")
        String language);

    /**
     * Accepts a Digi-Key Part Number and returns a ProductInfo record that consists of component specifications, quantity on hand, price breaks, etc. for that part number.
     * 
     * @param digikeyPartNumber
     * @param customerNumber
     * @return
     *     returns com.digikey.services.searchws.EDAProductInfo
     */
    @WebMethod(operationName = "GetProductInfoByDigikeyPartNumber", action = "http://services.digikey.com/SearchWS/GetProductInfoByDigikeyPartNumber")
    @WebResult(name = "GetProductInfoByDigikeyPartNumberResult", targetNamespace = "http://services.digikey.com/SearchWS")
    @RequestWrapper(localName = "GetProductInfoByDigikeyPartNumber", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.GetProductInfoByDigikeyPartNumber")
    @ResponseWrapper(localName = "GetProductInfoByDigikeyPartNumberResponse", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.GetProductInfoByDigikeyPartNumberResponse")
    public EDAProductInfo getProductInfoByDigikeyPartNumber(
        @WebParam(name = "digikeyPartNumber", targetNamespace = "http://services.digikey.com/SearchWS")
        String digikeyPartNumber,
        @WebParam(name = "customerNumber", targetNamespace = "http://services.digikey.com/SearchWS")
        int customerNumber);

    /**
     * Accepts a Digi-Key Part Number and returns a ProductInfo record that consists of component specifications, quantity on hand, price breaks, etc. for that part number.
     * 
     * @param site
     * @param language
     * @param digikeyPartNumber
     * @return
     *     returns com.digikey.services.searchws.ProductInfoEx
     */
    @WebMethod(operationName = "GetProductInfo", action = "http://services.digikey.com/SearchWS/GetProductInfo")
    @WebResult(name = "GetProductInfoResult", targetNamespace = "http://services.digikey.com/SearchWS")
    @RequestWrapper(localName = "GetProductInfo", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.GetProductInfo")
    @ResponseWrapper(localName = "GetProductInfoResponse", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.GetProductInfoResponse")
    public ProductInfoEx getProductInfo(
        @WebParam(name = "digikeyPartNumber", targetNamespace = "http://services.digikey.com/SearchWS")
        String digikeyPartNumber,
        @WebParam(name = "site", targetNamespace = "http://services.digikey.com/SearchWS")
        String site,
        @WebParam(name = "language", targetNamespace = "http://services.digikey.com/SearchWS")
        String language);

    /**
     * Accepts a Digi-Key label barcode and returns a ProductInfo record that consists of component specifications, quantity on hand, price breaks, etc. for that part number.
     * 
     * @param labelBarcode
     * @param site
     * @param language
     * @return
     *     returns com.digikey.services.searchws.ProductInfoEx
     */
    @WebMethod(operationName = "GetProductInfoByBarcode", action = "http://services.digikey.com/SearchWS/GetProductInfoByBarcode")
    @WebResult(name = "GetProductInfoByBarcodeResult", targetNamespace = "http://services.digikey.com/SearchWS")
    @RequestWrapper(localName = "GetProductInfoByBarcode", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.GetProductInfoByBarcode")
    @ResponseWrapper(localName = "GetProductInfoByBarcodeResponse", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.GetProductInfoByBarcodeResponse")
    public ProductInfoEx getProductInfoByBarcode(
        @WebParam(name = "labelBarcode", targetNamespace = "http://services.digikey.com/SearchWS")
        String labelBarcode,
        @WebParam(name = "site", targetNamespace = "http://services.digikey.com/SearchWS")
        String site,
        @WebParam(name = "language", targetNamespace = "http://services.digikey.com/SearchWS")
        String language);

    /**
     * Accepts a Digi-Key Part Number and returns the current quantity on hand.
     * 
     * @param digikeyPartNumber
     * @return
     *     returns int
     */
    @WebMethod(operationName = "GetQuantityOnHandByDigikeyPartNumber", action = "http://services.digikey.com/SearchWS/GetQuantityOnHandByDigikeyPartNumber")
    @WebResult(name = "GetQuantityOnHandByDigikeyPartNumberResult", targetNamespace = "http://services.digikey.com/SearchWS")
    @RequestWrapper(localName = "GetQuantityOnHandByDigikeyPartNumber", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.GetQuantityOnHandByDigikeyPartNumber")
    @ResponseWrapper(localName = "GetQuantityOnHandByDigikeyPartNumberResponse", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.GetQuantityOnHandByDigikeyPartNumberResponse")
    public int getQuantityOnHandByDigikeyPartNumber(
        @WebParam(name = "digikeyPartNumber", targetNamespace = "http://services.digikey.com/SearchWS")
        String digikeyPartNumber);

    /**
     * Accepts a keyword/text string of up to 250 characters, a numerical parameter representing how many records to return (with a maximum of 100), a numerical parameter representing what position to start returning records from, a parameter (Flags Enumeration) that represents search options (In Stock, Lead Free, Rohs Compliant), Site, and Language.
     * 
     * @param recordStartPosition
     * @param site
     * @param keywords
     * @param recordCount
     * @param options
     * @param language
     * @return
     *     returns com.digikey.services.searchws.BaseProductInfoCollectionInt
     */
    @WebMethod(operationName = "KeywordSearchSiteLanguage", action = "http://services.digikey.com/SearchWS/KeywordSearchSiteLanguage")
    @WebResult(name = "KeywordSearchSiteLanguageResult", targetNamespace = "http://services.digikey.com/SearchWS")
    @RequestWrapper(localName = "KeywordSearchSiteLanguage", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.KeywordSearchSiteLanguage")
    @ResponseWrapper(localName = "KeywordSearchSiteLanguageResponse", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.KeywordSearchSiteLanguageResponse")
    public BaseProductInfoCollectionInt keywordSearchSiteLanguage(
        @WebParam(name = "keywords", targetNamespace = "http://services.digikey.com/SearchWS")
        String keywords,
        @WebParam(name = "recordCount", targetNamespace = "http://services.digikey.com/SearchWS")
        int recordCount,
        @WebParam(name = "recordStartPosition", targetNamespace = "http://services.digikey.com/SearchWS")
        int recordStartPosition,
        @WebParam(name = "options", targetNamespace = "http://services.digikey.com/SearchWS")
        List<String> options,
        @WebParam(name = "site", targetNamespace = "http://services.digikey.com/SearchWS")
        String site,
        @WebParam(name = "language", targetNamespace = "http://services.digikey.com/SearchWS")
        String language);

    /**
     * Accepts a keyword/text string of up to 250 characters, a numerical parameter representing how many records to return (with a maximum of 100), a numerical parameter representing what position to start returning records from, and a parameter (Flags Enumeration) that represents search options (In Stock, Lead Free, Rohs Compliant).
     * 
     * @param recordStartPosition
     * @param keywords
     * @param recordCount
     * @param options
     * @return
     *     returns com.digikey.services.searchws.BaseProductInfoCollection
     */
    @WebMethod(operationName = "KeywordSearch", action = "http://services.digikey.com/SearchWS/KeywordSearch")
    @WebResult(name = "KeywordSearchResult", targetNamespace = "http://services.digikey.com/SearchWS")
    @RequestWrapper(localName = "KeywordSearch", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.KeywordSearch")
    @ResponseWrapper(localName = "KeywordSearchResponse", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.KeywordSearchResponse")
    public BaseProductInfoCollection keywordSearch(
        @WebParam(name = "keywords", targetNamespace = "http://services.digikey.com/SearchWS")
        String keywords,
        @WebParam(name = "recordCount", targetNamespace = "http://services.digikey.com/SearchWS")
        int recordCount,
        @WebParam(name = "recordStartPosition", targetNamespace = "http://services.digikey.com/SearchWS")
        int recordStartPosition,
        @WebParam(name = "options", targetNamespace = "http://services.digikey.com/SearchWS")
        List<String> options);

    /**
     * Searches for parts based on a specified Mfr. Part Number, Site, and Language
     * 
     * @param manufacturerPartNumber
     * @param site
     * @param language
     * @return
     *     returns com.digikey.services.searchws.BaseProductInfoCollectionInt
     */
    @WebMethod(operationName = "SearchByManufacturerPartNumberSiteLanguage", action = "http://services.digikey.com/SearchWS/SearchByManufacturerPartNumberSiteLanguage")
    @WebResult(name = "SearchByManufacturerPartNumberSiteLanguageResult", targetNamespace = "http://services.digikey.com/SearchWS")
    @RequestWrapper(localName = "SearchByManufacturerPartNumberSiteLanguage", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.SearchByManufacturerPartNumberSiteLanguage")
    @ResponseWrapper(localName = "SearchByManufacturerPartNumberSiteLanguageResponse", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.SearchByManufacturerPartNumberSiteLanguageResponse")
    public BaseProductInfoCollectionInt searchByManufacturerPartNumberSiteLanguage(
        @WebParam(name = "manufacturerPartNumber", targetNamespace = "http://services.digikey.com/SearchWS")
        String manufacturerPartNumber,
        @WebParam(name = "site", targetNamespace = "http://services.digikey.com/SearchWS")
        String site,
        @WebParam(name = "language", targetNamespace = "http://services.digikey.com/SearchWS")
        String language);

    /**
     * Searches for parts based on a specified Mfr. Part Number.
     * 
     * @param manufacturerPartNumber
     * @return
     *     returns com.digikey.services.searchws.BaseProductInfoCollection
     */
    @WebMethod(operationName = "SearchByManufacturerPartNumber", action = "http://services.digikey.com/SearchWS/SearchByManufacturerPartNumber")
    @WebResult(name = "SearchByManufacturerPartNumberResult", targetNamespace = "http://services.digikey.com/SearchWS")
    @RequestWrapper(localName = "SearchByManufacturerPartNumber", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.SearchByManufacturerPartNumber")
    @ResponseWrapper(localName = "SearchByManufacturerPartNumberResponse", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.SearchByManufacturerPartNumberResponse")
    public BaseProductInfoCollection searchByManufacturerPartNumber(
        @WebParam(name = "manufacturerPartNumber", targetNamespace = "http://services.digikey.com/SearchWS")
        String manufacturerPartNumber);

    /**
     * Searches for parts based on a specified vendorID, Site, and Language
     * 
     * @param recordStartPosition
     * @param site
     * @param recordCount
     * @param options
     * @param vendorID
     * @param language
     * @return
     *     returns com.digikey.services.searchws.BaseProductInfoCollectionInt
     */
    @WebMethod(operationName = "SearchByVendorSiteLanguage", action = "http://services.digikey.com/SearchWS/SearchByVendorSiteLanguage")
    @WebResult(name = "SearchByVendorSiteLanguageResult", targetNamespace = "http://services.digikey.com/SearchWS")
    @RequestWrapper(localName = "SearchByVendorSiteLanguage", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.SearchByVendorSiteLanguage")
    @ResponseWrapper(localName = "SearchByVendorSiteLanguageResponse", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.SearchByVendorSiteLanguageResponse")
    public BaseProductInfoCollectionInt searchByVendorSiteLanguage(
        @WebParam(name = "vendorID", targetNamespace = "http://services.digikey.com/SearchWS")
        int vendorID,
        @WebParam(name = "recordCount", targetNamespace = "http://services.digikey.com/SearchWS")
        int recordCount,
        @WebParam(name = "recordStartPosition", targetNamespace = "http://services.digikey.com/SearchWS")
        int recordStartPosition,
        @WebParam(name = "options", targetNamespace = "http://services.digikey.com/SearchWS")
        List<String> options,
        @WebParam(name = "site", targetNamespace = "http://services.digikey.com/SearchWS")
        String site,
        @WebParam(name = "language", targetNamespace = "http://services.digikey.com/SearchWS")
        String language);

    /**
     * Searches for parts based on a specified vendorID
     * 
     * @param recordStartPosition
     * @param recordCount
     * @param options
     * @param vendorID
     * @return
     *     returns com.digikey.services.searchws.BaseProductInfoCollection
     */
    @WebMethod(operationName = "SearchByVendor", action = "http://services.digikey.com/SearchWS/SearchByVendor")
    @WebResult(name = "SearchByVendorResult", targetNamespace = "http://services.digikey.com/SearchWS")
    @RequestWrapper(localName = "SearchByVendor", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.SearchByVendor")
    @ResponseWrapper(localName = "SearchByVendorResponse", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.SearchByVendorResponse")
    public BaseProductInfoCollection searchByVendor(
        @WebParam(name = "vendorID", targetNamespace = "http://services.digikey.com/SearchWS")
        int vendorID,
        @WebParam(name = "recordCount", targetNamespace = "http://services.digikey.com/SearchWS")
        int recordCount,
        @WebParam(name = "recordStartPosition", targetNamespace = "http://services.digikey.com/SearchWS")
        int recordStartPosition,
        @WebParam(name = "options", targetNamespace = "http://services.digikey.com/SearchWS")
        List<String> options);

    /**
     * Checks the status of the search web service
     * 
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SystemAvailabilityCheck", action = "http://services.digikey.com/SearchWS/SystemAvailabilityCheck")
    @WebResult(name = "SystemAvailabilityCheckResult", targetNamespace = "http://services.digikey.com/SearchWS")
    @RequestWrapper(localName = "SystemAvailabilityCheck", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.SystemAvailabilityCheck")
    @ResponseWrapper(localName = "SystemAvailabilityCheckResponse", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.SystemAvailabilityCheckResponse")
    public boolean systemAvailabilityCheck();

    /**
     * Accepts a list of Digi-Key or Manufacturer Part Numbers and returns a list of ProductInfo records that consists of component specifications, quantity on hand, price breaks, etc.
     * 
     * @param partNumberList
     * @param site
     * @param exactManufacturerPartMatch
     * @param language
     * @param currency
     * @return
     *     returns com.digikey.services.searchws.ArrayOfProductInfoListResult
     */
    @WebMethod(operationName = "GetProductInfoList", action = "http://services.digikey.com/SearchWS/GetProductInfoList")
    @WebResult(name = "GetProductInfoListResult", targetNamespace = "http://services.digikey.com/SearchWS")
    @RequestWrapper(localName = "GetProductInfoList", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.GetProductInfoList")
    @ResponseWrapper(localName = "GetProductInfoListResponse", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.GetProductInfoListResponse")
    public ArrayOfProductInfoListResult getProductInfoList(
        @WebParam(name = "PartNumberList", targetNamespace = "http://services.digikey.com/SearchWS")
        ArrayOfInputPartNumber partNumberList,
        @WebParam(name = "site", targetNamespace = "http://services.digikey.com/SearchWS")
        String site,
        @WebParam(name = "language", targetNamespace = "http://services.digikey.com/SearchWS")
        String language,
        @WebParam(name = "currency", targetNamespace = "http://services.digikey.com/SearchWS")
        String currency,
        @WebParam(name = "exactManufacturerPartMatch", targetNamespace = "http://services.digikey.com/SearchWS")
        boolean exactManufacturerPartMatch);

    /**
     * Accepts a keyword/text string of up to 250 characters, a numerical parameter representing how many records to return (with a maximum of 100), a numerical parameter representing what position to start returning records from, a parameter (Flags Enumeration) that represents search options (In Stock, Lead Free, Rohs Compliant), Site, and Language.
     * 
     * @param recordStartPosition
     * @param site
     * @param keywords
     * @param recordCount
     * @param options
     * @param language
     * @return
     *     returns com.digikey.services.searchws.BaseProductInfoAllPricingCollectionInt
     */
    @WebMethod(operationName = "KeywordSearchSiteLanguageIncludeAllPricing", action = "http://services.digikey.com/SearchWS/KeywordSearchSiteLanguageIncludeAllPricing")
    @WebResult(name = "KeywordSearchSiteLanguageIncludeAllPricingResult", targetNamespace = "http://services.digikey.com/SearchWS")
    @RequestWrapper(localName = "KeywordSearchSiteLanguageIncludeAllPricing", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.KeywordSearchSiteLanguageIncludeAllPricing")
    @ResponseWrapper(localName = "KeywordSearchSiteLanguageIncludeAllPricingResponse", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.KeywordSearchSiteLanguageIncludeAllPricingResponse")
    public BaseProductInfoAllPricingCollectionInt keywordSearchSiteLanguageIncludeAllPricing(
        @WebParam(name = "keywords", targetNamespace = "http://services.digikey.com/SearchWS")
        String keywords,
        @WebParam(name = "recordCount", targetNamespace = "http://services.digikey.com/SearchWS")
        int recordCount,
        @WebParam(name = "recordStartPosition", targetNamespace = "http://services.digikey.com/SearchWS")
        int recordStartPosition,
        @WebParam(name = "options", targetNamespace = "http://services.digikey.com/SearchWS")
        List<String> options,
        @WebParam(name = "site", targetNamespace = "http://services.digikey.com/SearchWS")
        String site,
        @WebParam(name = "language", targetNamespace = "http://services.digikey.com/SearchWS")
        String language);

    /**
     * Accepts a keyword/text string of up to 250 characters, a numerical parameter representing how many records to return (with a maximum of 100), a numerical parameter representing what position to start returning records from, and a parameter (Flags Enumeration) that represents search options (In Stock, Lead Free, Rohs Compliant).
     * 
     * @param recordStartPosition
     * @param keywords
     * @param recordCount
     * @param options
     * @return
     *     returns com.digikey.services.searchws.BaseProductInfoAllPricingCollection
     */
    @WebMethod(operationName = "KeywordSearchIncludeAllPricing", action = "http://services.digikey.com/SearchWS/KeywordSearchIncludeAllPricing")
    @WebResult(name = "KeywordSearchIncludeAllPricingResult", targetNamespace = "http://services.digikey.com/SearchWS")
    @RequestWrapper(localName = "KeywordSearchIncludeAllPricing", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.KeywordSearchIncludeAllPricing")
    @ResponseWrapper(localName = "KeywordSearchIncludeAllPricingResponse", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.KeywordSearchIncludeAllPricingResponse")
    public BaseProductInfoAllPricingCollection keywordSearchIncludeAllPricing(
        @WebParam(name = "keywords", targetNamespace = "http://services.digikey.com/SearchWS")
        String keywords,
        @WebParam(name = "recordCount", targetNamespace = "http://services.digikey.com/SearchWS")
        int recordCount,
        @WebParam(name = "recordStartPosition", targetNamespace = "http://services.digikey.com/SearchWS")
        int recordStartPosition,
        @WebParam(name = "options", targetNamespace = "http://services.digikey.com/SearchWS")
        List<String> options);

    /**
     * Accepts a keyword/text string of up to 250 characters, a numerical parameter representing how many records to return (with a maximum of 100), a numerical parameter representing what position to start returning records from, a parameter (Flags Enumeration) that represents search options (In Stock, Lead Free, Rohs Compliant), Site, and Language.
     * 
     * @param recordStartPosition
     * @param site
     * @param keywords
     * @param recordCount
     * @param options
     * @param language
     * @return
     *     returns com.digikey.services.searchws.BaseProductInfoPricingCollectionInt
     */
    @WebMethod(operationName = "KeywordSearchSiteLanguageIncludePricing", action = "http://services.digikey.com/SearchWS/KeywordSearchSiteLanguageIncludePricing")
    @WebResult(name = "KeywordSearchSiteLanguageIncludePricingResult", targetNamespace = "http://services.digikey.com/SearchWS")
    @RequestWrapper(localName = "KeywordSearchSiteLanguageIncludePricing", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.KeywordSearchSiteLanguageIncludePricing")
    @ResponseWrapper(localName = "KeywordSearchSiteLanguageIncludePricingResponse", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.KeywordSearchSiteLanguageIncludePricingResponse")
    public BaseProductInfoPricingCollectionInt keywordSearchSiteLanguageIncludePricing(
        @WebParam(name = "keywords", targetNamespace = "http://services.digikey.com/SearchWS")
        String keywords,
        @WebParam(name = "recordCount", targetNamespace = "http://services.digikey.com/SearchWS")
        int recordCount,
        @WebParam(name = "recordStartPosition", targetNamespace = "http://services.digikey.com/SearchWS")
        int recordStartPosition,
        @WebParam(name = "options", targetNamespace = "http://services.digikey.com/SearchWS")
        List<String> options,
        @WebParam(name = "site", targetNamespace = "http://services.digikey.com/SearchWS")
        String site,
        @WebParam(name = "language", targetNamespace = "http://services.digikey.com/SearchWS")
        String language);

    /**
     * Accepts a keyword/text string of up to 250 characters, a numerical parameter representing how many records to return (with a maximum of 100), a numerical parameter representing what position to start returning records from, and a parameter (Flags Enumeration) that represents search options (In Stock, Lead Free, Rohs Compliant).
     * 
     * @param recordStartPosition
     * @param keywords
     * @param recordCount
     * @param options
     * @return
     *     returns com.digikey.services.searchws.BaseProductInfoPricingCollection
     */
    @WebMethod(operationName = "KeywordSearchIncludePricing", action = "http://services.digikey.com/SearchWS/KeywordSearchIncludePricing")
    @WebResult(name = "KeywordSearchIncludePricingResult", targetNamespace = "http://services.digikey.com/SearchWS")
    @RequestWrapper(localName = "KeywordSearchIncludePricing", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.KeywordSearchIncludePricing")
    @ResponseWrapper(localName = "KeywordSearchIncludePricingResponse", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.KeywordSearchIncludePricingResponse")
    public BaseProductInfoPricingCollection keywordSearchIncludePricing(
        @WebParam(name = "keywords", targetNamespace = "http://services.digikey.com/SearchWS")
        String keywords,
        @WebParam(name = "recordCount", targetNamespace = "http://services.digikey.com/SearchWS")
        int recordCount,
        @WebParam(name = "recordStartPosition", targetNamespace = "http://services.digikey.com/SearchWS")
        int recordStartPosition,
        @WebParam(name = "options", targetNamespace = "http://services.digikey.com/SearchWS")
        List<String> options);

    /**
     * Searches part records by keyword(s), categories, families, parametric values, site, and language.  WARNING: This method is reserved for use by the Digi-Key mobile application.
     * 
     * @param recordStartPosition
     * @param site
     * @param expandPackaging
     * @param keywords
     * @param recordCount
     * @param options
     * @param parametricValues
     * @param language
     * @param categories
     * @param families
     * @return
     *     returns com.digikey.services.searchws.CategoryCollection
     */
    @WebMethod(operationName = "KeywordParametricSearch", action = "http://services.digikey.com/SearchWS/KeywordParametricSearch")
    @WebResult(name = "KeywordParametricSearchResult", targetNamespace = "http://services.digikey.com/SearchWS")
    @RequestWrapper(localName = "KeywordParametricSearch", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.KeywordParametricSearch")
    @ResponseWrapper(localName = "KeywordParametricSearchResponse", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.KeywordParametricSearchResponse")
    public CategoryCollection keywordParametricSearch(
        @WebParam(name = "keywords", targetNamespace = "http://services.digikey.com/SearchWS")
        String keywords,
        @WebParam(name = "recordCount", targetNamespace = "http://services.digikey.com/SearchWS")
        int recordCount,
        @WebParam(name = "recordStartPosition", targetNamespace = "http://services.digikey.com/SearchWS")
        int recordStartPosition,
        @WebParam(name = "options", targetNamespace = "http://services.digikey.com/SearchWS")
        List<String> options,
        @WebParam(name = "categories", targetNamespace = "http://services.digikey.com/SearchWS")
        ArrayOfInt categories,
        @WebParam(name = "families", targetNamespace = "http://services.digikey.com/SearchWS")
        ArrayOfInt1 families,
        @WebParam(name = "parametricValues", targetNamespace = "http://services.digikey.com/SearchWS")
        ArrayOfParametricValue parametricValues,
        @WebParam(name = "site", targetNamespace = "http://services.digikey.com/SearchWS")
        String site,
        @WebParam(name = "language", targetNamespace = "http://services.digikey.com/SearchWS")
        String language,
        @WebParam(name = "expandPackaging", targetNamespace = "http://services.digikey.com/SearchWS")
        boolean expandPackaging);

    /**
     * Accepts a Digi-Key Part Number, Site, and Language and returns a ProductInfo record that consists of component specifications, quantity on hand, price breaks, etc. for that part number.  WARNING: This method is reserved for use by the Digi-Key mobile application.
     * 
     * @param site
     * @param language
     * @param digikeyPartNumber
     * @param customerNumber
     * @return
     *     returns com.digikey.services.searchws.MobileProductInfo
     */
    @WebMethod(operationName = "GetProductInfoByDigikeyPartNumber2", action = "http://services.digikey.com/SearchWS/GetProductInfoByDigikeyPartNumber2")
    @WebResult(name = "GetProductInfoByDigikeyPartNumber2Result", targetNamespace = "http://services.digikey.com/SearchWS")
    @RequestWrapper(localName = "GetProductInfoByDigikeyPartNumber2", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.GetProductInfoByDigikeyPartNumber2")
    @ResponseWrapper(localName = "GetProductInfoByDigikeyPartNumber2Response", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.GetProductInfoByDigikeyPartNumber2Response")
    public MobileProductInfo getProductInfoByDigikeyPartNumber2(
        @WebParam(name = "digikeyPartNumber", targetNamespace = "http://services.digikey.com/SearchWS")
        String digikeyPartNumber,
        @WebParam(name = "customerNumber", targetNamespace = "http://services.digikey.com/SearchWS")
        int customerNumber,
        @WebParam(name = "site", targetNamespace = "http://services.digikey.com/SearchWS")
        String site,
        @WebParam(name = "language", targetNamespace = "http://services.digikey.com/SearchWS")
        String language);

    /**
     * Accepts a Digi-Key Part Number, Customer Number and returns a ProductInfo record that consists of component specifications including quantity on hand, price breaks, part image URL, UNSPSC code, etc. for that part number.
     * 
     * @param digikeyPartNumber
     * @param customerNumber
     * @return
     *     returns com.digikey.services.searchws.EDAProductInfoUnspsc
     */
    @WebMethod(operationName = "GetProductInfoByDigikeyPartNumberIncludeUnspscCode", action = "http://services.digikey.com/SearchWS/GetProductInfoByDigikeyPartNumberIncludeUnspscCode")
    @WebResult(name = "GetProductInfoByDigikeyPartNumberIncludeUnspscCodeResult", targetNamespace = "http://services.digikey.com/SearchWS")
    @RequestWrapper(localName = "GetProductInfoByDigikeyPartNumberIncludeUnspscCode", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.GetProductInfoByDigikeyPartNumberIncludeUnspscCode")
    @ResponseWrapper(localName = "GetProductInfoByDigikeyPartNumberIncludeUnspscCodeResponse", targetNamespace = "http://services.digikey.com/SearchWS", className = "com.digikey.services.searchws.GetProductInfoByDigikeyPartNumberIncludeUnspscCodeResponse")
    public EDAProductInfoUnspsc getProductInfoByDigikeyPartNumberIncludeUnspscCode(
        @WebParam(name = "digikeyPartNumber", targetNamespace = "http://services.digikey.com/SearchWS")
        String digikeyPartNumber,
        @WebParam(name = "customerNumber", targetNamespace = "http://services.digikey.com/SearchWS")
        int customerNumber);

}
