
package in.gov.incometaxindiaefiling.ditws.addclientdetails.v_1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "addClientPort", targetNamespace = "http://incometaxindiaefiling.gov.in/ditws/addClientDetails/v_1_0")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AddClientPort {


    /**
     * 
     * @param addClient
     * @param loginInfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://incometaxindiaefiling.gov.in/ditws/addClientDetails/v_1_0")
    @RequestWrapper(localName = "addClientDetails", targetNamespace = "http://incometaxindiaefiling.gov.in/ditws/addClientDetails/v_1_0", className = "in.gov.incometaxindiaefiling.ditws.addclientdetails.v_1_0.AddClientDetails")
    @ResponseWrapper(localName = "addClientDetailsResponse", targetNamespace = "http://incometaxindiaefiling.gov.in/ditws/addClientDetails/v_1_0", className = "in.gov.incometaxindiaefiling.ditws.addclientdetails.v_1_0.AddClientDetailsResponse")
    public String addClientDetails(
        @WebParam(name = "LoginInfo", targetNamespace = "http://incometaxindiaefiling.gov.in/ditws/addClientDetails/v_1_0")
        LoginInfoType loginInfo,
        @WebParam(name = "addClient", targetNamespace = "http://incometaxindiaefiling.gov.in/ditws/addClientDetails/v_1_0")
        AddClientType addClient);

}
