
package defaultnamespace;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "chemEquation", targetNamespace = "http://DefaultNamespace", wsdlLocation = "META-INF/wsdl/chemEquation.wsdl")
public class ChemEquation_Service
    extends Service
{

    private final static URL CHEMEQUATION_WSDL_LOCATION;
    private final static WebServiceException CHEMEQUATION_EXCEPTION;
    private final static QName CHEMEQUATION_QNAME = new QName("http://DefaultNamespace", "chemEquation");

    static {
        CHEMEQUATION_WSDL_LOCATION = defaultnamespace.ChemEquation_Service.class.getClassLoader().getResource("META-INF/wsdl/chemEquation.wsdl");
        WebServiceException e = null;
        if (CHEMEQUATION_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/chemEquation.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CHEMEQUATION_EXCEPTION = e;
    }

    public ChemEquation_Service() {
        super(__getWsdlLocation(), CHEMEQUATION_QNAME);
    }

    public ChemEquation_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHEMEQUATION_QNAME, features);
    }

    public ChemEquation_Service(URL wsdlLocation) {
        super(wsdlLocation, CHEMEQUATION_QNAME);
    }

    public ChemEquation_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHEMEQUATION_QNAME, features);
    }

    public ChemEquation_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ChemEquation_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ChemEquation
     */
    @WebEndpoint(name = "chemEquationHttpPort")
    public ChemEquation getChemEquationHttpPort() {
        return super.getPort(new QName("http://DefaultNamespace", "chemEquationHttpPort"), ChemEquation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChemEquation
     */
    @WebEndpoint(name = "chemEquationHttpPort")
    public ChemEquation getChemEquationHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://DefaultNamespace", "chemEquationHttpPort"), ChemEquation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHEMEQUATION_EXCEPTION!= null) {
            throw CHEMEQUATION_EXCEPTION;
        }
        return CHEMEQUATION_WSDL_LOCATION;
    }

}
