
package com.w3schools.webservices;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TempConvert", targetNamespace = "http://www.w3schools.com/webservices/", wsdlLocation = "META-INF/wsdl/TempConvert.wsdl")
public class TempConvert
    extends Service
{

    private final static URL TEMPCONVERT_WSDL_LOCATION;
    private final static WebServiceException TEMPCONVERT_EXCEPTION;
    private final static QName TEMPCONVERT_QNAME = new QName("http://www.w3schools.com/webservices/", "TempConvert");

    static {
        TEMPCONVERT_WSDL_LOCATION = com.w3schools.webservices.TempConvert.class.getClassLoader().getResource("META-INF/wsdl/TempConvert.wsdl");
        WebServiceException e = null;
        if (TEMPCONVERT_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/TempConvert.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        TEMPCONVERT_EXCEPTION = e;
    }

    public TempConvert() {
        super(__getWsdlLocation(), TEMPCONVERT_QNAME);
    }

    public TempConvert(WebServiceFeature... features) {
        super(__getWsdlLocation(), TEMPCONVERT_QNAME, features);
    }

    public TempConvert(URL wsdlLocation) {
        super(wsdlLocation, TEMPCONVERT_QNAME);
    }

    public TempConvert(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TEMPCONVERT_QNAME, features);
    }

    public TempConvert(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TempConvert(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TempConvertSoap
     */
    @WebEndpoint(name = "TempConvertSoap")
    public TempConvertSoap getTempConvertSoap() {
        return super.getPort(new QName("http://www.w3schools.com/webservices/", "TempConvertSoap"), TempConvertSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TempConvertSoap
     */
    @WebEndpoint(name = "TempConvertSoap")
    public TempConvertSoap getTempConvertSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.w3schools.com/webservices/", "TempConvertSoap"), TempConvertSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TEMPCONVERT_EXCEPTION!= null) {
            throw TEMPCONVERT_EXCEPTION;
        }
        return TEMPCONVERT_WSDL_LOCATION;
    }

}
