
package com.xignite.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "XigniteSecuritySoap", targetNamespace = "http://www.xignite.com/services/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface XigniteSecuritySoap {


    /**
     * Lookup basic bond information by CUSIP.
     * 
     * @param cusip
     * @return
     *     returns com.xignite.services.BondLookup
     */
    @WebMethod(operationName = "LookupBond", action = "http://www.xignite.com/services/LookupBond")
    @WebResult(name = "LookupBondResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "LookupBond", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.LookupBond")
    @ResponseWrapper(localName = "LookupBondResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.LookupBondResponse")
    public BondLookup lookupBond(
        @WebParam(name = "CUSIP", targetNamespace = "http://www.xignite.com/services/")
        String cusip);

    /**
     * Get the symbol, name, CUSIP, and CIK for a security.
     * 
     * @param identifier
     * @param identifierType
     * @return
     *     returns com.xignite.services.Security
     */
    @WebMethod(operationName = "MapSecurity", action = "http://www.xignite.com/services/MapSecurity")
    @WebResult(name = "MapSecurityResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "MapSecurity", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.MapSecurity")
    @ResponseWrapper(localName = "MapSecurityResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.MapSecurityResponse")
    public Security mapSecurity(
        @WebParam(name = "Identifier", targetNamespace = "http://www.xignite.com/services/")
        String identifier,
        @WebParam(name = "IdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes identifierType);

    /**
     * Get the symbol, name, CUSIP, and CIK, Sector, and Industry for a security.
     * 
     * @param identifier
     * @param identifierType
     * @return
     *     returns com.xignite.services.Record
     */
    @WebMethod(operationName = "MapSecurityDetail", action = "http://www.xignite.com/services/MapSecurityDetail")
    @WebResult(name = "MapSecurityDetailResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "MapSecurityDetail", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.MapSecurityDetail")
    @ResponseWrapper(localName = "MapSecurityDetailResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.MapSecurityDetailResponse")
    public Record mapSecurityDetail(
        @WebParam(name = "Identifier", targetNamespace = "http://www.xignite.com/services/")
        String identifier,
        @WebParam(name = "IdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes identifierType);

    /**
     * List all securities mapping a specific identifier.
     * 
     * @param identifier
     * @param identifierType
     * @return
     *     returns com.xignite.services.ArrayOfSecurity
     */
    @WebMethod(operationName = "ListSecurities", action = "http://www.xignite.com/services/ListSecurities")
    @WebResult(name = "ListSecuritiesResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "ListSecurities", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.ListSecurities")
    @ResponseWrapper(localName = "ListSecuritiesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.ListSecuritiesResponse")
    public ArrayOfSecurity listSecurities(
        @WebParam(name = "Identifier", targetNamespace = "http://www.xignite.com/services/")
        String identifier,
        @WebParam(name = "IdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes identifierType);

    /**
     * Get the symbol, name, CUSIP, and CIK for a list of securities.
     * 
     * @param identifiers
     * @param identifierType
     * @return
     *     returns com.xignite.services.ArrayOfSecurity
     */
    @WebMethod(operationName = "MapSecurities", action = "http://www.xignite.com/services/MapSecurities")
    @WebResult(name = "MapSecuritiesResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "MapSecurities", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.MapSecurities")
    @ResponseWrapper(localName = "MapSecuritiesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.MapSecuritiesResponse")
    public ArrayOfSecurity mapSecurities(
        @WebParam(name = "Identifiers", targetNamespace = "http://www.xignite.com/services/")
        String identifiers,
        @WebParam(name = "IdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes identifierType);

    /**
     * Get the symbol, name, CUSIP, and CIK, Sector, and Industry for a list of securities.
     * 
     * @param identifiers
     * @param identifierType
     * @return
     *     returns com.xignite.services.ArrayOfRecord
     */
    @WebMethod(operationName = "MapSecurityDetails", action = "http://www.xignite.com/services/MapSecurityDetails")
    @WebResult(name = "MapSecurityDetailsResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "MapSecurityDetails", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.MapSecurityDetails")
    @ResponseWrapper(localName = "MapSecurityDetailsResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.MapSecurityDetailsResponse")
    public ArrayOfRecord mapSecurityDetails(
        @WebParam(name = "Identifiers", targetNamespace = "http://www.xignite.com/services/")
        String identifiers,
        @WebParam(name = "IdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes identifierType);

    /**
     * Get dividend history for a stock.
     * 
     * @param identifier
     * @param identifierType
     * @return
     *     returns com.xignite.services.DividendHistory
     */
    @WebMethod(operationName = "GetDividendHistory", action = "http://www.xignite.com/services/GetDividendHistory")
    @WebResult(name = "GetDividendHistoryResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetDividendHistory", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetDividendHistory")
    @ResponseWrapper(localName = "GetDividendHistoryResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetDividendHistoryResponse")
    public DividendHistory getDividendHistory(
        @WebParam(name = "Identifier", targetNamespace = "http://www.xignite.com/services/")
        String identifier,
        @WebParam(name = "IdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes identifierType);

    /**
     * Get dividend histories for a set of stock.
     * 
     * @param identifiers
     * @param identifierType
     * @return
     *     returns com.xignite.services.ArrayOfDividendHistory
     */
    @WebMethod(operationName = "GetDividendHistories", action = "http://www.xignite.com/services/GetDividendHistories")
    @WebResult(name = "GetDividendHistoriesResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetDividendHistories", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetDividendHistories")
    @ResponseWrapper(localName = "GetDividendHistoriesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetDividendHistoriesResponse")
    public ArrayOfDividendHistory getDividendHistories(
        @WebParam(name = "Identifiers", targetNamespace = "http://www.xignite.com/services/")
        String identifiers,
        @WebParam(name = "IdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes identifierType);

    /**
     * Get extended dividend history for a stock.
     * 
     * @param identifier
     * @param identifierType
     * @return
     *     returns com.xignite.services.ExtendedDividendHistory
     */
    @WebMethod(operationName = "GetExtendedDividendHistory", action = "http://www.xignite.com/services/GetExtendedDividendHistory")
    @WebResult(name = "GetExtendedDividendHistoryResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetExtendedDividendHistory", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetExtendedDividendHistory")
    @ResponseWrapper(localName = "GetExtendedDividendHistoryResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetExtendedDividendHistoryResponse")
    public ExtendedDividendHistory getExtendedDividendHistory(
        @WebParam(name = "Identifier", targetNamespace = "http://www.xignite.com/services/")
        String identifier,
        @WebParam(name = "IdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes identifierType);

    /**
     * Get split history for a stock.
     * 
     * @param identifier
     * @param identifierType
     * @return
     *     returns com.xignite.services.SplitHistory
     */
    @WebMethod(operationName = "GetSplitHistory", action = "http://www.xignite.com/services/GetSplitHistory")
    @WebResult(name = "GetSplitHistoryResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetSplitHistory", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetSplitHistory")
    @ResponseWrapper(localName = "GetSplitHistoryResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetSplitHistoryResponse")
    public SplitHistory getSplitHistory(
        @WebParam(name = "Identifier", targetNamespace = "http://www.xignite.com/services/")
        String identifier,
        @WebParam(name = "IdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes identifierType);

    /**
     * Return the cumulative split ratio for a security between two dates. For instance, if a security saw a 3:1 split and 2:1 split during the period, the split ratio 6 is returned. Returns 1 if no split occurred.
     * 
     * @param fromDate
     * @param identifier
     * @param toDate
     * @param identifierType
     * @return
     *     returns com.xignite.services.StockSplit
     */
    @WebMethod(operationName = "GetSplitRatio", action = "http://www.xignite.com/services/GetSplitRatio")
    @WebResult(name = "GetSplitRatioResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetSplitRatio", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetSplitRatio")
    @ResponseWrapper(localName = "GetSplitRatioResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetSplitRatioResponse")
    public StockSplit getSplitRatio(
        @WebParam(name = "Identifier", targetNamespace = "http://www.xignite.com/services/")
        String identifier,
        @WebParam(name = "IdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes identifierType,
        @WebParam(name = "FromDate", targetNamespace = "http://www.xignite.com/services/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://www.xignite.com/services/")
        XMLGregorianCalendar toDate);

    /**
     * Returns the Name, Symbol, Category and Exchange for a list of stocks, funds or indexes matching an expression.
     * 
     * @param name
     * @param type
     * @return
     *     returns com.xignite.services.ArrayOfLookupItem
     */
    @WebMethod(operationName = "Lookup", action = "http://www.xignite.com/services/Lookup")
    @WebResult(name = "LookupResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "Lookup", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.Lookup")
    @ResponseWrapper(localName = "LookupResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.LookupResponse")
    public ArrayOfLookupItem lookup(
        @WebParam(name = "Name", targetNamespace = "http://www.xignite.com/services/")
        String name,
        @WebParam(name = "Type", targetNamespace = "http://www.xignite.com/services/")
        LookupType type);

    /**
     * Returns the Name, Symbol, Category and Exchange for a list of stocks, funds or indexes matching an expression.
     * 
     * @param name
     * @param exchange
     * @return
     *     returns com.xignite.services.ArrayOfLookupItem
     */
    @WebMethod(operationName = "LookupByExchange", action = "http://www.xignite.com/services/LookupByExchange")
    @WebResult(name = "LookupByExchangeResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "LookupByExchange", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.LookupByExchange")
    @ResponseWrapper(localName = "LookupByExchangeResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.LookupByExchangeResponse")
    public ArrayOfLookupItem lookupByExchange(
        @WebParam(name = "Name", targetNamespace = "http://www.xignite.com/services/")
        String name,
        @WebParam(name = "Exchange", targetNamespace = "http://www.xignite.com/services/")
        String exchange);

    /**
     * Returns the Name, Symbol, Category and Exchange for a list of stocks, funds or indexes matching an expression.
     * 
     * @param name
     * @param exchanges
     * @return
     *     returns com.xignite.services.ArrayOfLookupItem
     */
    @WebMethod(operationName = "LookupByExchanges", action = "http://www.xignite.com/services/LookupByExchanges")
    @WebResult(name = "LookupByExchangesResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "LookupByExchanges", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.LookupByExchanges")
    @ResponseWrapper(localName = "LookupByExchangesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.LookupByExchangesResponse")
    public ArrayOfLookupItem lookupByExchanges(
        @WebParam(name = "Name", targetNamespace = "http://www.xignite.com/services/")
        String name,
        @WebParam(name = "Exchanges", targetNamespace = "http://www.xignite.com/services/")
        String exchanges);

    /**
     * Returns the Name, Symbol, Category and Exchange for a list of stocks matching an expression.
     * 
     * @param name
     * @return
     *     returns com.xignite.services.ArrayOfLookupItem
     */
    @WebMethod(operationName = "LookupStock", action = "http://www.xignite.com/services/LookupStock")
    @WebResult(name = "LookupStockResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "LookupStock", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.LookupStock")
    @ResponseWrapper(localName = "LookupStockResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.LookupStockResponse")
    public ArrayOfLookupItem lookupStock(
        @WebParam(name = "Name", targetNamespace = "http://www.xignite.com/services/")
        String name);

    /**
     * Returns the Name, Symbol, Category and Exchange for a list of funds matching an expression.
     * 
     * @param name
     * @return
     *     returns com.xignite.services.ArrayOfLookupItem
     */
    @WebMethod(operationName = "LookupFund", action = "http://www.xignite.com/services/LookupFund")
    @WebResult(name = "LookupFundResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "LookupFund", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.LookupFund")
    @ResponseWrapper(localName = "LookupFundResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.LookupFundResponse")
    public ArrayOfLookupItem lookupFund(
        @WebParam(name = "Name", targetNamespace = "http://www.xignite.com/services/")
        String name);

    /**
     * Get a CUSIP for a stock based on its symbol.
     * 
     * @param symbol
     * @return
     *     returns com.xignite.services.Cusip
     */
    @WebMethod(operationName = "GetCUSIPStock", action = "http://www.xignite.com/services/GetCUSIPStock")
    @WebResult(name = "GetCUSIPStockResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetCUSIPStock", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCUSIPStock")
    @ResponseWrapper(localName = "GetCUSIPStockResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCUSIPStockResponse")
    public Cusip getCUSIPStock(
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        String symbol);

    /**
     * Get a CUSIP for a mutual fund based on its symbol.
     * 
     * @param symbol
     * @return
     *     returns com.xignite.services.Cusip
     */
    @WebMethod(operationName = "GetCUSIPFund", action = "http://www.xignite.com/services/GetCUSIPFund")
    @WebResult(name = "GetCUSIPFundResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetCUSIPFund", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCUSIPFund")
    @ResponseWrapper(localName = "GetCUSIPFundResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCUSIPFundResponse")
    public Cusip getCUSIPFund(
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        String symbol);

    /**
     * Get largest declines in stock price for a time period.
     * 
     * @param identifier
     * @param identifierType
     * @param asOfDate
     * @param yearsOfHistory
     * @return
     *     returns com.xignite.services.StockGrowthVariations
     */
    @WebMethod(operationName = "GetLargestDeclines", action = "http://www.xignite.com/services/GetLargestDeclines")
    @WebResult(name = "GetLargestDeclinesResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetLargestDeclines", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetLargestDeclines")
    @ResponseWrapper(localName = "GetLargestDeclinesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetLargestDeclinesResponse")
    public StockGrowthVariations getLargestDeclines(
        @WebParam(name = "Identifier", targetNamespace = "http://www.xignite.com/services/")
        String identifier,
        @WebParam(name = "IdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes identifierType,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        XMLGregorianCalendar asOfDate,
        @WebParam(name = "YearsOfHistory", targetNamespace = "http://www.xignite.com/services/")
        int yearsOfHistory);

    /**
     * Get largest declines in market capitalization for a time period.
     * 
     * @param identifier
     * @param identifierType
     * @param extractIfUnavailable
     * @param asOfDate
     * @param yearsOfHistory
     * @return
     *     returns com.xignite.services.StockGrowthVariations
     */
    @WebMethod(operationName = "GetLargestCapDeclines", action = "http://www.xignite.com/services/GetLargestCapDeclines")
    @WebResult(name = "GetLargestCapDeclinesResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetLargestCapDeclines", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetLargestCapDeclines")
    @ResponseWrapper(localName = "GetLargestCapDeclinesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetLargestCapDeclinesResponse")
    public StockGrowthVariations getLargestCapDeclines(
        @WebParam(name = "Identifier", targetNamespace = "http://www.xignite.com/services/")
        String identifier,
        @WebParam(name = "IdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes identifierType,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        XMLGregorianCalendar asOfDate,
        @WebParam(name = "YearsOfHistory", targetNamespace = "http://www.xignite.com/services/")
        int yearsOfHistory,
        @WebParam(name = "ExtractIfUnavailable", targetNamespace = "http://www.xignite.com/services/")
        boolean extractIfUnavailable);

    /**
     * Get historical monthly market capitalization based on SEC filing for a security.
     * 
     * @param identifier
     * @param endDate
     * @param identifierType
     * @param extractIfUnavailable
     * @param startDate
     * @return
     *     returns com.xignite.services.HistoricalMarketCapitalization
     */
    @WebMethod(operationName = "GetHistoricalMonthlyMarketCapitalization", action = "http://www.xignite.com/services/GetHistoricalMonthlyMarketCapitalization")
    @WebResult(name = "GetHistoricalMonthlyMarketCapitalizationResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetHistoricalMonthlyMarketCapitalization", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalMonthlyMarketCapitalization")
    @ResponseWrapper(localName = "GetHistoricalMonthlyMarketCapitalizationResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalMonthlyMarketCapitalizationResponse")
    public HistoricalMarketCapitalization getHistoricalMonthlyMarketCapitalization(
        @WebParam(name = "Identifier", targetNamespace = "http://www.xignite.com/services/")
        String identifier,
        @WebParam(name = "IdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes identifierType,
        @WebParam(name = "StartDate", targetNamespace = "http://www.xignite.com/services/")
        String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        String endDate,
        @WebParam(name = "ExtractIfUnavailable", targetNamespace = "http://www.xignite.com/services/")
        boolean extractIfUnavailable);

    /**
     * Get historical market capitalization based on SEC filing for a security.
     * 
     * @param identifier
     * @param endDate
     * @param identifierType
     * @param extractIfUnavailable
     * @param startDate
     * @return
     *     returns com.xignite.services.HistoricalMarketCapitalization
     */
    @WebMethod(operationName = "GetHistoricalMarketCapitalization", action = "http://www.xignite.com/services/GetHistoricalMarketCapitalization")
    @WebResult(name = "GetHistoricalMarketCapitalizationResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetHistoricalMarketCapitalization", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalMarketCapitalization")
    @ResponseWrapper(localName = "GetHistoricalMarketCapitalizationResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalMarketCapitalizationResponse")
    public HistoricalMarketCapitalization getHistoricalMarketCapitalization(
        @WebParam(name = "Identifier", targetNamespace = "http://www.xignite.com/services/")
        String identifier,
        @WebParam(name = "IdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes identifierType,
        @WebParam(name = "StartDate", targetNamespace = "http://www.xignite.com/services/")
        String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        String endDate,
        @WebParam(name = "ExtractIfUnavailable", targetNamespace = "http://www.xignite.com/services/")
        boolean extractIfUnavailable);

    /**
     * Get historical market capitalization based on SEC filing for a security.
     * 
     * @param identifier
     * @param endDate
     * @param backupOption
     * @param identifierType
     * @param extractIfUnavailable
     * @param startDate
     * @return
     *     returns com.xignite.services.HistoricalMarketCapitalization
     */
    @WebMethod(operationName = "GetHistoricalMarketCapitalizationCustom", action = "http://www.xignite.com/services/GetHistoricalMarketCapitalizationCustom")
    @WebResult(name = "GetHistoricalMarketCapitalizationCustomResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetHistoricalMarketCapitalizationCustom", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalMarketCapitalizationCustom")
    @ResponseWrapper(localName = "GetHistoricalMarketCapitalizationCustomResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalMarketCapitalizationCustomResponse")
    public HistoricalMarketCapitalization getHistoricalMarketCapitalizationCustom(
        @WebParam(name = "Identifier", targetNamespace = "http://www.xignite.com/services/")
        String identifier,
        @WebParam(name = "IdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes identifierType,
        @WebParam(name = "StartDate", targetNamespace = "http://www.xignite.com/services/")
        String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        String endDate,
        @WebParam(name = "ExtractIfUnavailable", targetNamespace = "http://www.xignite.com/services/")
        boolean extractIfUnavailable,
        @WebParam(name = "BackupOption", targetNamespace = "http://www.xignite.com/services/")
        BackupOptionTypes backupOption);

    /**
     * Get historical market capitalization based on SEC filing for a security.
     * 
     * @param identifier
     * @param identifierType
     * @param asOfDate
     * @return
     *     returns com.xignite.services.HistoricalMarketCapitalization
     */
    @WebMethod(operationName = "GetMarketCapitalization", action = "http://www.xignite.com/services/GetMarketCapitalization")
    @WebResult(name = "GetMarketCapitalizationResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetMarketCapitalization", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetMarketCapitalization")
    @ResponseWrapper(localName = "GetMarketCapitalizationResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetMarketCapitalizationResponse")
    public HistoricalMarketCapitalization getMarketCapitalization(
        @WebParam(name = "Identifier", targetNamespace = "http://www.xignite.com/services/")
        String identifier,
        @WebParam(name = "IdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes identifierType,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        String asOfDate);

    /**
     * Convert a symbol from one methodology to another.
     * 
     * @param symbol
     * @param toType
     * @param fromType
     * @return
     *     returns com.xignite.services.Symbol
     */
    @WebMethod(operationName = "MapSymbol", action = "http://www.xignite.com/services/MapSymbol")
    @WebResult(name = "MapSymbolResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "MapSymbol", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.MapSymbol")
    @ResponseWrapper(localName = "MapSymbolResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.MapSymbolResponse")
    public Symbol mapSymbol(
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        String symbol,
        @WebParam(name = "FromType", targetNamespace = "http://www.xignite.com/services/")
        SymbologyTypes fromType,
        @WebParam(name = "ToType", targetNamespace = "http://www.xignite.com/services/")
        SymbologyTypes toType);

}
