
package linjegodswebservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Schenker_x0020_Norway_x0020_WebservicesSoap", targetNamespace = "LinjegodsWebServices")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SchenkerX0020NorwayX0020WebservicesSoap {


    /**
     * With this services You can track and trace on a given item observed in Norway. Input is shipment number, consigment number or collinumber. Yoy MUST use a valid User and Password , given by Schenker 
     * 
     * @param password
     * @param id
     * @param username
     * @return
     *     returns linjegodswebservices.TrackAndTraceResultat
     */
    @WebMethod(operationName = "TrackAndTrace", action = "LinjegodsWebServices/TrackAndTrace")
    @WebResult(name = "TrackAndTraceResult", targetNamespace = "LinjegodsWebServices")
    @RequestWrapper(localName = "TrackAndTrace", targetNamespace = "LinjegodsWebServices", className = "linjegodswebservices.TrackAndTrace")
    @ResponseWrapper(localName = "TrackAndTraceResponse", targetNamespace = "LinjegodsWebServices", className = "linjegodswebservices.TrackAndTraceResponse")
    public TrackAndTraceResultat trackAndTrace(
        @WebParam(name = "username", targetNamespace = "LinjegodsWebServices")
        String username,
        @WebParam(name = "password", targetNamespace = "LinjegodsWebServices")
        String password,
        @WebParam(name = "id", targetNamespace = "LinjegodsWebServices")
        String id);

    /**
     * This service gives You one or more POD URI's to tiff images. Input is shipment number, consigment number or collinumber
     * 
     * @param password
     * @param id
     * @param user
     * @return
     *     returns linjegodswebservices.TrackAndTracePODsResultat
     */
    @WebMethod(operationName = "TrackAndTracePODs", action = "LinjegodsWebServices/TrackAndTracePODs")
    @WebResult(name = "TrackAndTracePODsResult", targetNamespace = "LinjegodsWebServices")
    @RequestWrapper(localName = "TrackAndTracePODs", targetNamespace = "LinjegodsWebServices", className = "linjegodswebservices.TrackAndTracePODs")
    @ResponseWrapper(localName = "TrackAndTracePODsResponse", targetNamespace = "LinjegodsWebServices", className = "linjegodswebservices.TrackAndTracePODsResponse")
    public TrackAndTracePODsResultat trackAndTracePODs(
        @WebParam(name = "user", targetNamespace = "LinjegodsWebServices")
        String user,
        @WebParam(name = "password", targetNamespace = "LinjegodsWebServices")
        String password,
        @WebParam(name = "id", targetNamespace = "LinjegodsWebServices")
        String id);

    /**
     * Price and timetable
     * 
     * @param password
     * @param kriterie
     * @param username
     * @return
     *     returns linjegodswebservices.PriceAndTimeTableResult
     */
    @WebMethod(operationName = "PriceAndTimeTable", action = "LinjegodsWebServices/PriceAndTimeTable")
    @WebResult(name = "PriceAndTimeTableResult", targetNamespace = "LinjegodsWebServices")
    @RequestWrapper(localName = "PriceAndTimeTable", targetNamespace = "LinjegodsWebServices", className = "linjegodswebservices.PriceAndTimeTable")
    @ResponseWrapper(localName = "PriceAndTimeTableResponse", targetNamespace = "LinjegodsWebServices", className = "linjegodswebservices.PriceAndTimeTableResponse")
    public PriceAndTimeTableResult priceAndTimeTable(
        @WebParam(name = "username", targetNamespace = "LinjegodsWebServices")
        String username,
        @WebParam(name = "password", targetNamespace = "LinjegodsWebServices")
        String password,
        @WebParam(name = "kriterie", targetNamespace = "LinjegodsWebServices")
        FreightPriceArguments kriterie);

}
