
package com.oracle.xmlns.enterprise.hcm.services.ci_ci_personal_data;

import javax.xml.ws.WebFault;
import com.oracle.xmlns.enterprise.tools.schemas.m507254.CIFaultTypeShape;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "CIFault", targetNamespace = "http://xmlns.oracle.com/Enterprise/Tools/schemas/M507254.V1")
public class M507254V1
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CIFaultTypeShape faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public M507254V1(String message, CIFaultTypeShape faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public M507254V1(String message, CIFaultTypeShape faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.oracle.xmlns.enterprise.tools.schemas.m507254.CIFaultTypeShape
     */
    public CIFaultTypeShape getFaultInfo() {
        return faultInfo;
    }

}
