
package stadiswebservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "rentACar", targetNamespace = "http://stadiswebservice/")
@XmlSeeAlso({
    de.travel_it.sunnycars.ObjectFactory.class,
    stadiswebservice.ObjectFactory.class
})
public interface RentACar {


    /**
     * 
     * @param query
     * @return
     *     returns stadiswebservice.CarDataResponse
     */
    @WebMethod(operationName = "GetCarData")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetCarData", targetNamespace = "http://stadiswebservice/", className = "stadiswebservice.GetCarData")
    @ResponseWrapper(localName = "GetCarDataResponse", targetNamespace = "http://stadiswebservice/", className = "stadiswebservice.GetCarDataResponse")
    @Action(input = "http://stadiswebservice/rentACar/GetCarDataRequest", output = "http://stadiswebservice/rentACar/GetCarDataResponse")
    public CarDataResponse getCarData(
        @WebParam(name = "query", targetNamespace = "")
        CarDataQuery query);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "repeatMessage", targetNamespace = "http://stadiswebservice/", className = "stadiswebservice.RepeatMessage")
    @ResponseWrapper(localName = "repeatMessageResponse", targetNamespace = "http://stadiswebservice/", className = "stadiswebservice.RepeatMessageResponse")
    @Action(input = "http://stadiswebservice/rentACar/repeatMessageRequest", output = "http://stadiswebservice/rentACar/repeatMessageResponse")
    public String repeatMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
