
package au.gov.business.abr.abrxmlsearch;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ABRXMLSearchSoap", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ABRXMLSearchSoap {


    /**
     * Search By ABN e.g. 51835430479
     * 
     * @param searchString
     * @param authenticationGuid
     * @param includeHistoricalDetails
     * @return
     *     returns au.gov.business.abr.abrxmlsearch.Payload
     */
    @WebMethod(operationName = "ABRSearchByABN", action = "http://abr.business.gov.au/ABRXMLSearch/ABRSearchByABN")
    @WebResult(name = "ABRPayloadSearchResults", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
    @RequestWrapper(localName = "ABRSearchByABN", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.ABRSearchByABN")
    @ResponseWrapper(localName = "ABRSearchByABNResponse", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.ABRSearchByABNResponse")
    public Payload abrSearchByABN(
        @WebParam(name = "searchString", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String searchString,
        @WebParam(name = "includeHistoricalDetails", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String includeHistoricalDetails,
        @WebParam(name = "authenticationGuid", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String authenticationGuid);

    /**
     * Same as ABRSearchByABN but returns charity tax concession information if it exists for the ABN.
     * 
     * @param searchString
     * @param authenticationGuid
     * @param includeHistoricalDetails
     * @return
     *     returns au.gov.business.abr.abrxmlsearch.Payload
     */
    @WebMethod(operationName = "SearchByABNv200506", action = "http://abr.business.gov.au/ABRXMLSearch/SearchByABNv200506")
    @WebResult(name = "ABRPayloadSearchResults", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
    @RequestWrapper(localName = "SearchByABNv200506", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.SearchByABNv200506")
    @ResponseWrapper(localName = "SearchByABNv200506Response", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.SearchByABNv200506Response")
    public Payload searchByABNv200506(
        @WebParam(name = "searchString", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String searchString,
        @WebParam(name = "includeHistoricalDetails", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String includeHistoricalDetails,
        @WebParam(name = "authenticationGuid", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String authenticationGuid);

    /**
     * Same as SearchByABNv200506 but returns superannuation information if it exists for the ABN.
     * 
     * @param searchString
     * @param authenticationGuid
     * @param includeHistoricalDetails
     * @return
     *     returns au.gov.business.abr.abrxmlsearch.Payload
     */
    @WebMethod(operationName = "SearchByABNv200709", action = "http://abr.business.gov.au/ABRXMLSearch/SearchByABNv200709")
    @WebResult(name = "ABRPayloadSearchResults", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
    @RequestWrapper(localName = "SearchByABNv200709", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.SearchByABNv200709")
    @ResponseWrapper(localName = "SearchByABNv200709Response", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.SearchByABNv200709Response")
    public Payload searchByABNv200709(
        @WebParam(name = "searchString", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String searchString,
        @WebParam(name = "includeHistoricalDetails", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String includeHistoricalDetails,
        @WebParam(name = "authenticationGuid", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String authenticationGuid);

    /**
     * Same as SearchByABNv200709 but returns business names if they exist for the ABN.
     * 
     * @param searchString
     * @param authenticationGuid
     * @param includeHistoricalDetails
     * @return
     *     returns au.gov.business.abr.abrxmlsearch.Payload
     */
    @WebMethod(operationName = "SearchByABNv201205", action = "http://abr.business.gov.au/ABRXMLSearch/SearchByABNv201205")
    @WebResult(name = "ABRPayloadSearchResults", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
    @RequestWrapper(localName = "SearchByABNv201205", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.SearchByABNv201205")
    @ResponseWrapper(localName = "SearchByABNv201205Response", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.SearchByABNv201205Response")
    public Payload searchByABNv201205(
        @WebParam(name = "searchString", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String searchString,
        @WebParam(name = "includeHistoricalDetails", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String includeHistoricalDetails,
        @WebParam(name = "authenticationGuid", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String authenticationGuid);

    /**
     * Same as SearchByABNv201205 but returns DGR Item number and ACNC registration if they exist for the ABN.
     * 
     * @param searchString
     * @param authenticationGuid
     * @param includeHistoricalDetails
     * @return
     *     returns au.gov.business.abr.abrxmlsearch.Payload
     */
    @WebMethod(operationName = "SearchByABNv201408", action = "http://abr.business.gov.au/ABRXMLSearch/SearchByABNv201408")
    @WebResult(name = "ABRPayloadSearchResults", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
    @RequestWrapper(localName = "SearchByABNv201408", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.SearchByABNv201408")
    @ResponseWrapper(localName = "SearchByABNv201408Response", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.SearchByABNv201408Response")
    public Payload searchByABNv201408(
        @WebParam(name = "searchString", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String searchString,
        @WebParam(name = "includeHistoricalDetails", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String includeHistoricalDetails,
        @WebParam(name = "authenticationGuid", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String authenticationGuid);

    /**
     * Search By ASIC number e.g. 080036693
     * 
     * @param searchString
     * @param authenticationGuid
     * @param includeHistoricalDetails
     * @return
     *     returns au.gov.business.abr.abrxmlsearch.Payload
     */
    @WebMethod(operationName = "ABRSearchByASIC", action = "http://abr.business.gov.au/ABRXMLSearch/ABRSearchByASIC")
    @WebResult(name = "ABRPayloadSearchResults", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
    @RequestWrapper(localName = "ABRSearchByASIC", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.ABRSearchByASIC")
    @ResponseWrapper(localName = "ABRSearchByASICResponse", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.ABRSearchByASICResponse")
    public Payload abrSearchByASIC(
        @WebParam(name = "searchString", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String searchString,
        @WebParam(name = "includeHistoricalDetails", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String includeHistoricalDetails,
        @WebParam(name = "authenticationGuid", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String authenticationGuid);

    /**
     * Same as ABRSearchByASIC but returns charity tax concession information if it exists for the ABN.
     * 
     * @param searchString
     * @param authenticationGuid
     * @param includeHistoricalDetails
     * @return
     *     returns au.gov.business.abr.abrxmlsearch.Payload
     */
    @WebMethod(operationName = "SearchByASICv200506", action = "http://abr.business.gov.au/ABRXMLSearch/SearchByASICv200506")
    @WebResult(name = "ABRPayloadSearchResults", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
    @RequestWrapper(localName = "SearchByASICv200506", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.SearchByASICv200506")
    @ResponseWrapper(localName = "SearchByASICv200506Response", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.SearchByASICv200506Response")
    public Payload searchByASICv200506(
        @WebParam(name = "searchString", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String searchString,
        @WebParam(name = "includeHistoricalDetails", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String includeHistoricalDetails,
        @WebParam(name = "authenticationGuid", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String authenticationGuid);

    /**
     * Same as SearchByASICv200506 but returns business names if they exist for the ABN.
     * 
     * @param searchString
     * @param authenticationGuid
     * @param includeHistoricalDetails
     * @return
     *     returns au.gov.business.abr.abrxmlsearch.Payload
     */
    @WebMethod(operationName = "SearchByASICv201205", action = "http://abr.business.gov.au/ABRXMLSearch/SearchByASICv201205")
    @WebResult(name = "ABRPayloadSearchResults", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
    @RequestWrapper(localName = "SearchByASICv201205", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.SearchByASICv201205")
    @ResponseWrapper(localName = "SearchByASICv201205Response", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.SearchByASICv201205Response")
    public Payload searchByASICv201205(
        @WebParam(name = "searchString", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String searchString,
        @WebParam(name = "includeHistoricalDetails", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String includeHistoricalDetails,
        @WebParam(name = "authenticationGuid", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String authenticationGuid);

    /**
     * Same as SearchByASICv201205 but returns DGR Item number and ACNC registration if they exist for the ABN.
     * 
     * @param searchString
     * @param authenticationGuid
     * @param includeHistoricalDetails
     * @return
     *     returns au.gov.business.abr.abrxmlsearch.Payload
     */
    @WebMethod(operationName = "SearchByASICv201408", action = "http://abr.business.gov.au/ABRXMLSearch/SearchByASICv201408")
    @WebResult(name = "ABRPayloadSearchResults", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
    @RequestWrapper(localName = "SearchByASICv201408", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.SearchByASICv201408")
    @ResponseWrapper(localName = "SearchByASICv201408Response", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.SearchByASICv201408Response")
    public Payload searchByASICv201408(
        @WebParam(name = "searchString", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String searchString,
        @WebParam(name = "includeHistoricalDetails", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String includeHistoricalDetails,
        @WebParam(name = "authenticationGuid", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String authenticationGuid);

    /**
     * Search By Name.
     * 
     * @param authenticationGuid
     * @param externalNameSearch
     * @return
     *     returns au.gov.business.abr.abrxmlsearch.Payload
     */
    @WebMethod(operationName = "ABRSearchByName", action = "http://abr.business.gov.au/ABRXMLSearch/ABRSearchByName")
    @WebResult(name = "ABRPayloadSearchResults", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
    @RequestWrapper(localName = "ABRSearchByName", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.ABRSearchByName")
    @ResponseWrapper(localName = "ABRSearchByNameResponse", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.ABRSearchByNameResponse")
    public Payload abrSearchByName(
        @WebParam(name = "externalNameSearch", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        ExternalRequestNameSearch externalNameSearch,
        @WebParam(name = "authenticationGuid", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String authenticationGuid);

    /**
     * Advanced Search By Name - allows you to specify a search width and minimum score.
     * 
     * @param authenticationGuid
     * @param externalNameSearch
     * @return
     *     returns au.gov.business.abr.abrxmlsearch.Payload
     */
    @WebMethod(operationName = "ABRSearchByNameAdvanced", action = "http://abr.business.gov.au/ABRXMLSearch/ABRSearchByNameAdvanced")
    @WebResult(name = "ABRPayloadSearchResults", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
    @RequestWrapper(localName = "ABRSearchByNameAdvanced", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.ABRSearchByNameAdvanced")
    @ResponseWrapper(localName = "ABRSearchByNameAdvancedResponse", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.ABRSearchByNameAdvancedResponse")
    public Payload abrSearchByNameAdvanced(
        @WebParam(name = "externalNameSearch", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        ExternalRequestNameSearchAdvanced externalNameSearch,
        @WebParam(name = "authenticationGuid", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String authenticationGuid);

    /**
     * Same as ABRSearchByNameAdvanced but also allows you to set your own upper limit on the number of rows returned from the search (default is 200).
     * 
     * @param authenticationGuid
     * @param externalNameSearch
     * @return
     *     returns au.gov.business.abr.abrxmlsearch.Payload
     */
    @WebMethod(operationName = "ABRSearchByNameAdvanced2006", action = "http://abr.business.gov.au/ABRXMLSearch/ABRSearchByNameAdvanced2006")
    @WebResult(name = "ABRPayloadSearchResults", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
    @RequestWrapper(localName = "ABRSearchByNameAdvanced2006", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.ABRSearchByNameAdvanced2006")
    @ResponseWrapper(localName = "ABRSearchByNameAdvanced2006Response", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.ABRSearchByNameAdvanced2006Response")
    public Payload abrSearchByNameAdvanced2006(
        @WebParam(name = "externalNameSearch", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        ExternalRequestNameSearchAdvanced2006 externalNameSearch,
        @WebParam(name = "authenticationGuid", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String authenticationGuid);

    /**
     * Same as ABRSearchByNameAdvanced2006 but also allows you to filter by business names.
     * 
     * @param authenticationGuid
     * @param externalNameSearch
     * @return
     *     returns au.gov.business.abr.abrxmlsearch.Payload
     */
    @WebMethod(operationName = "ABRSearchByNameAdvanced2012", action = "http://abr.business.gov.au/ABRXMLSearch/ABRSearchByNameAdvanced2012")
    @WebResult(name = "ABRPayloadSearchResults", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
    @RequestWrapper(localName = "ABRSearchByNameAdvanced2012", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.ABRSearchByNameAdvanced2012")
    @ResponseWrapper(localName = "ABRSearchByNameAdvanced2012Response", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.ABRSearchByNameAdvanced2012Response")
    public Payload abrSearchByNameAdvanced2012(
        @WebParam(name = "externalNameSearch", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        ExternalRequestNameSearchAdvanced2012 externalNameSearch,
        @WebParam(name = "authenticationGuid", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String authenticationGuid);

    /**
     * Same as ABRSearchByName but allows you to call the method using http-get/post as well as SOAP.
     * 
     * @param tradingName
     * @param authenticationGuid
     * @param nt
     * @param tas
     * @param postcode
     * @param qld
     * @param wa
     * @param sa
     * @param legalName
     * @param vic
     * @param nsw
     * @param act
     * @param name
     * @return
     *     returns au.gov.business.abr.abrxmlsearch.Payload
     */
    @WebMethod(operationName = "ABRSearchByNameSimpleProtocol", action = "http://abr.business.gov.au/ABRXMLSearch/ABRSearchByNameSimpleProtocol")
    @WebResult(name = "ABRPayloadSearchResults", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
    @RequestWrapper(localName = "ABRSearchByNameSimpleProtocol", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.ABRSearchByNameSimpleProtocol")
    @ResponseWrapper(localName = "ABRSearchByNameSimpleProtocolResponse", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.ABRSearchByNameSimpleProtocolResponse")
    public Payload abrSearchByNameSimpleProtocol(
        @WebParam(name = "name", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String name,
        @WebParam(name = "postcode", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String postcode,
        @WebParam(name = "legalName", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String legalName,
        @WebParam(name = "tradingName", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String tradingName,
        @WebParam(name = "NSW", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String nsw,
        @WebParam(name = "SA", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String sa,
        @WebParam(name = "ACT", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String act,
        @WebParam(name = "VIC", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String vic,
        @WebParam(name = "WA", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String wa,
        @WebParam(name = "NT", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String nt,
        @WebParam(name = "QLD", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String qld,
        @WebParam(name = "TAS", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String tas,
        @WebParam(name = "authenticationGuid", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String authenticationGuid);

    /**
     * Same as ABRSearchByNameAdvanced but allows you to call the method using http-get/post as well as SOAP.
     * 
     * @param tradingName
     * @param authenticationGuid
     * @param nt
     * @param tas
     * @param postcode
     * @param qld
     * @param wa
     * @param sa
     * @param minimumScore
     * @param legalName
     * @param vic
     * @param nsw
     * @param act
     * @param name
     * @param searchWidth
     * @return
     *     returns au.gov.business.abr.abrxmlsearch.Payload
     */
    @WebMethod(operationName = "ABRSearchByNameAdvancedSimpleProtocol", action = "http://abr.business.gov.au/ABRXMLSearch/ABRSearchByNameAdvancedSimpleProtocol")
    @WebResult(name = "ABRPayloadSearchResults", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
    @RequestWrapper(localName = "ABRSearchByNameAdvancedSimpleProtocol", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.ABRSearchByNameAdvancedSimpleProtocol")
    @ResponseWrapper(localName = "ABRSearchByNameAdvancedSimpleProtocolResponse", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.ABRSearchByNameAdvancedSimpleProtocolResponse")
    public Payload abrSearchByNameAdvancedSimpleProtocol(
        @WebParam(name = "name", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String name,
        @WebParam(name = "postcode", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String postcode,
        @WebParam(name = "legalName", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String legalName,
        @WebParam(name = "tradingName", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String tradingName,
        @WebParam(name = "NSW", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String nsw,
        @WebParam(name = "SA", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String sa,
        @WebParam(name = "ACT", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String act,
        @WebParam(name = "VIC", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String vic,
        @WebParam(name = "WA", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String wa,
        @WebParam(name = "NT", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String nt,
        @WebParam(name = "QLD", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String qld,
        @WebParam(name = "TAS", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String tas,
        @WebParam(name = "authenticationGuid", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String authenticationGuid,
        @WebParam(name = "searchWidth", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String searchWidth,
        @WebParam(name = "minimumScore", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String minimumScore);

    /**
     * Same as ABRSearchByNameAdvanced2006 but allows you to call the method using http-get/post as well as SOAP
     * 
     * @param tradingName
     * @param authenticationGuid
     * @param nt
     * @param tas
     * @param postcode
     * @param qld
     * @param wa
     * @param sa
     * @param minimumScore
     * @param legalName
     * @param vic
     * @param nsw
     * @param act
     * @param name
     * @param searchWidth
     * @param maxSearchResults
     * @return
     *     returns au.gov.business.abr.abrxmlsearch.Payload
     */
    @WebMethod(operationName = "ABRSearchByNameAdvancedSimpleProtocol2006", action = "http://abr.business.gov.au/ABRXMLSearch/ABRSearchByNameAdvancedSimpleProtocol2006")
    @WebResult(name = "ABRPayloadSearchResults", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
    @RequestWrapper(localName = "ABRSearchByNameAdvancedSimpleProtocol2006", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.ABRSearchByNameAdvancedSimpleProtocol2006")
    @ResponseWrapper(localName = "ABRSearchByNameAdvancedSimpleProtocol2006Response", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.ABRSearchByNameAdvancedSimpleProtocol2006Response")
    public Payload abrSearchByNameAdvancedSimpleProtocol2006(
        @WebParam(name = "name", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String name,
        @WebParam(name = "postcode", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String postcode,
        @WebParam(name = "legalName", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String legalName,
        @WebParam(name = "tradingName", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String tradingName,
        @WebParam(name = "NSW", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String nsw,
        @WebParam(name = "SA", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String sa,
        @WebParam(name = "ACT", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String act,
        @WebParam(name = "VIC", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String vic,
        @WebParam(name = "WA", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String wa,
        @WebParam(name = "NT", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String nt,
        @WebParam(name = "QLD", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String qld,
        @WebParam(name = "TAS", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String tas,
        @WebParam(name = "authenticationGuid", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String authenticationGuid,
        @WebParam(name = "searchWidth", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String searchWidth,
        @WebParam(name = "minimumScore", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String minimumScore,
        @WebParam(name = "maxSearchResults", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String maxSearchResults);

    /**
     * Same as ABRSearchByNameAdvanced2012 but allows you to call the method using http-get/post as well as SOAP
     * 
     * @param tradingName
     * @param authenticationGuid
     * @param nt
     * @param tas
     * @param postcode
     * @param businessName
     * @param qld
     * @param wa
     * @param sa
     * @param minimumScore
     * @param legalName
     * @param vic
     * @param nsw
     * @param act
     * @param name
     * @param searchWidth
     * @param maxSearchResults
     * @return
     *     returns au.gov.business.abr.abrxmlsearch.Payload
     */
    @WebMethod(operationName = "ABRSearchByNameAdvancedSimpleProtocol2012", action = "http://abr.business.gov.au/ABRXMLSearch/ABRSearchByNameAdvancedSimpleProtocol2012")
    @WebResult(name = "ABRPayloadSearchResults", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
    @RequestWrapper(localName = "ABRSearchByNameAdvancedSimpleProtocol2012", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.ABRSearchByNameAdvancedSimpleProtocol2012")
    @ResponseWrapper(localName = "ABRSearchByNameAdvancedSimpleProtocol2012Response", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.ABRSearchByNameAdvancedSimpleProtocol2012Response")
    public Payload abrSearchByNameAdvancedSimpleProtocol2012(
        @WebParam(name = "name", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String name,
        @WebParam(name = "postcode", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String postcode,
        @WebParam(name = "legalName", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String legalName,
        @WebParam(name = "tradingName", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String tradingName,
        @WebParam(name = "businessName", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String businessName,
        @WebParam(name = "NSW", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String nsw,
        @WebParam(name = "SA", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String sa,
        @WebParam(name = "ACT", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String act,
        @WebParam(name = "VIC", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String vic,
        @WebParam(name = "WA", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String wa,
        @WebParam(name = "NT", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String nt,
        @WebParam(name = "QLD", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String qld,
        @WebParam(name = "TAS", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String tas,
        @WebParam(name = "authenticationGuid", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String authenticationGuid,
        @WebParam(name = "searchWidth", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String searchWidth,
        @WebParam(name = "minimumScore", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String minimumScore,
        @WebParam(name = "maxSearchResults", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String maxSearchResults);

    /**
     * Search for currently active ABNs for a postcode. Returns a list of matching ABNs.
     * 
     * @param authenticationGuid
     * @param postcode
     * @return
     *     returns au.gov.business.abr.abrxmlsearch.Payload
     */
    @WebMethod(operationName = "SearchByPostcode", action = "http://abr.business.gov.au/ABRXMLSearch/SearchByPostcode")
    @WebResult(name = "ABRPayloadSearchResults", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
    @RequestWrapper(localName = "SearchByPostcode", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.SearchByPostcode")
    @ResponseWrapper(localName = "SearchByPostcodeResponse", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.SearchByPostcodeResponse")
    public Payload searchByPostcode(
        @WebParam(name = "postcode", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String postcode,
        @WebParam(name = "authenticationGuid", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String authenticationGuid);

    /**
     * Search for ABNs by postcode and selected status. Returns a list of matching ABNs.
     * 
     * @param authenticationGuid
     * @param entityTypeCode
     * @param postcode
     * @param activeABNsOnly
     * @param currentGSTRegistrationOnly
     * @return
     *     returns au.gov.business.abr.abrxmlsearch.Payload
     */
    @WebMethod(operationName = "SearchByABNStatus", action = "http://abr.business.gov.au/ABRXMLSearch/SearchByABNStatus")
    @WebResult(name = "ABRPayloadSearchResults", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
    @RequestWrapper(localName = "SearchByABNStatus", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.SearchByABNStatus")
    @ResponseWrapper(localName = "SearchByABNStatusResponse", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.SearchByABNStatusResponse")
    public Payload searchByABNStatus(
        @WebParam(name = "postcode", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String postcode,
        @WebParam(name = "activeABNsOnly", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String activeABNsOnly,
        @WebParam(name = "currentGSTRegistrationOnly", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String currentGSTRegistrationOnly,
        @WebParam(name = "entityTypeCode", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String entityTypeCode,
        @WebParam(name = "authenticationGuid", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String authenticationGuid);

    /**
     * Search for ABNs that have been registered/re-activated of month and year. Returns a list of matching ABNs.
     * 
     * @param authenticationGuid
     * @param month
     * @param year
     * @param entityTypeCode
     * @param postcode
     * @param state
     * @return
     *     returns au.gov.business.abr.abrxmlsearch.Payload
     */
    @WebMethod(operationName = "SearchByRegistrationEvent", action = "http://abr.business.gov.au/ABRXMLSearch/SearchByRegistrationEvent")
    @WebResult(name = "ABRPayloadSearchResults", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
    @RequestWrapper(localName = "SearchByRegistrationEvent", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.SearchByRegistrationEvent")
    @ResponseWrapper(localName = "SearchByRegistrationEventResponse", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.SearchByRegistrationEventResponse")
    public Payload searchByRegistrationEvent(
        @WebParam(name = "postcode", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String postcode,
        @WebParam(name = "state", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String state,
        @WebParam(name = "entityTypeCode", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String entityTypeCode,
        @WebParam(name = "month", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String month,
        @WebParam(name = "year", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String year,
        @WebParam(name = "authenticationGuid", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String authenticationGuid);

    /**
     * Search for ABNs by update event (includes registrations). Returns a list of matching ABNs.
     * 
     * @param authenticationGuid
     * @param updatedate
     * @param entityTypeCode
     * @param postcode
     * @param state
     * @return
     *     returns au.gov.business.abr.abrxmlsearch.Payload
     */
    @WebMethod(operationName = "SearchByUpdateEvent", action = "http://abr.business.gov.au/ABRXMLSearch/SearchByUpdateEvent")
    @WebResult(name = "ABRPayloadSearchResults", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
    @RequestWrapper(localName = "SearchByUpdateEvent", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.SearchByUpdateEvent")
    @ResponseWrapper(localName = "SearchByUpdateEventResponse", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.SearchByUpdateEventResponse")
    public Payload searchByUpdateEvent(
        @WebParam(name = "postcode", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String postcode,
        @WebParam(name = "state", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String state,
        @WebParam(name = "entityTypeCode", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String entityTypeCode,
        @WebParam(name = "updatedate", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String updatedate,
        @WebParam(name = "authenticationGuid", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String authenticationGuid);

    /**
     * Search for ABNs that have charities tax concessions. Returns a list of matching ABNs.
     * 
     * @param authenticationGuid
     * @param postcode
     * @param concessionTypeCode
     * @param charityTypeCode
     * @param state
     * @return
     *     returns au.gov.business.abr.abrxmlsearch.Payload
     */
    @WebMethod(operationName = "SearchByCharity", action = "http://abr.business.gov.au/ABRXMLSearch/SearchByCharity")
    @WebResult(name = "ABRPayloadSearchResults", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
    @RequestWrapper(localName = "SearchByCharity", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.SearchByCharity")
    @ResponseWrapper(localName = "SearchByCharityResponse", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", className = "au.gov.business.abr.abrxmlsearch.SearchByCharityResponse")
    public Payload searchByCharity(
        @WebParam(name = "postcode", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String postcode,
        @WebParam(name = "state", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String state,
        @WebParam(name = "charityTypeCode", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String charityTypeCode,
        @WebParam(name = "concessionTypeCode", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String concessionTypeCode,
        @WebParam(name = "authenticationGuid", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        String authenticationGuid);

}
