
package au.gov.business.abr.abrxmlsearch;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * ABN Lookup web based search services
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ABRXMLSearch", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", wsdlLocation = "META-INF/wsdl/ABRXMLSearch.wsdl")
public class ABRXMLSearch
    extends Service
{

    private final static URL ABRXMLSEARCH_WSDL_LOCATION;
    private final static WebServiceException ABRXMLSEARCH_EXCEPTION;
    private final static QName ABRXMLSEARCH_QNAME = new QName("http://abr.business.gov.au/ABRXMLSearch/", "ABRXMLSearch");

    static {
        ABRXMLSEARCH_WSDL_LOCATION = au.gov.business.abr.abrxmlsearch.ABRXMLSearch.class.getClassLoader().getResource("META-INF/wsdl/ABRXMLSearch.wsdl");
        WebServiceException e = null;
        if (ABRXMLSEARCH_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/ABRXMLSearch.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        ABRXMLSEARCH_EXCEPTION = e;
    }

    public ABRXMLSearch() {
        super(__getWsdlLocation(), ABRXMLSEARCH_QNAME);
    }

    public ABRXMLSearch(WebServiceFeature... features) {
        super(__getWsdlLocation(), ABRXMLSEARCH_QNAME, features);
    }

    public ABRXMLSearch(URL wsdlLocation) {
        super(wsdlLocation, ABRXMLSEARCH_QNAME);
    }

    public ABRXMLSearch(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ABRXMLSEARCH_QNAME, features);
    }

    public ABRXMLSearch(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ABRXMLSearch(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ABRXMLSearchSoap
     */
    @WebEndpoint(name = "ABRXMLSearchSoap")
    public ABRXMLSearchSoap getABRXMLSearchSoap() {
        return super.getPort(new QName("http://abr.business.gov.au/ABRXMLSearch/", "ABRXMLSearchSoap"), ABRXMLSearchSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ABRXMLSearchSoap
     */
    @WebEndpoint(name = "ABRXMLSearchSoap")
    public ABRXMLSearchSoap getABRXMLSearchSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://abr.business.gov.au/ABRXMLSearch/", "ABRXMLSearchSoap"), ABRXMLSearchSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ABRXMLSEARCH_EXCEPTION!= null) {
            throw ABRXMLSEARCH_EXCEPTION;
        }
        return ABRXMLSEARCH_WSDL_LOCATION;
    }

}
