
package com.avalara.avatax.services;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TaxSvc", targetNamespace = "http://avatax.avalara.com/services", wsdlLocation = "META-INF/wsdl/TaxSvc.wsdl")
public class TaxSvc
    extends Service
{

    private final static URL TAXSVC_WSDL_LOCATION;
    private final static WebServiceException TAXSVC_EXCEPTION;
    private final static QName TAXSVC_QNAME = new QName("http://avatax.avalara.com/services", "TaxSvc");

    static {
        TAXSVC_WSDL_LOCATION = com.avalara.avatax.services.TaxSvc.class.getClassLoader().getResource("META-INF/wsdl/TaxSvc.wsdl");
        WebServiceException e = null;
        if (TAXSVC_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/TaxSvc.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        TAXSVC_EXCEPTION = e;
    }

    public TaxSvc() {
        super(__getWsdlLocation(), TAXSVC_QNAME);
    }

    public TaxSvc(WebServiceFeature... features) {
        super(__getWsdlLocation(), TAXSVC_QNAME, features);
    }

    public TaxSvc(URL wsdlLocation) {
        super(wsdlLocation, TAXSVC_QNAME);
    }

    public TaxSvc(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TAXSVC_QNAME, features);
    }

    public TaxSvc(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaxSvc(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TaxSvcSoap
     */
    @WebEndpoint(name = "TaxSvcSoap")
    public TaxSvcSoap getTaxSvcSoap() {
        return super.getPort(new QName("http://avatax.avalara.com/services", "TaxSvcSoap"), TaxSvcSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaxSvcSoap
     */
    @WebEndpoint(name = "TaxSvcSoap")
    public TaxSvcSoap getTaxSvcSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://avatax.avalara.com/services", "TaxSvcSoap"), TaxSvcSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TAXSVC_EXCEPTION!= null) {
            throw TAXSVC_EXCEPTION;
        }
        return TAXSVC_WSDL_LOCATION;
    }

}
