
package https.ws_esortcode;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This webservice contains bank sortcode, bank account, branch details and Credit Card Number Validation lookup functions. Before using the eSortcode WebService please visit http://www.eSortcode.com and follow the instructions for signing up with a new account.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BankDetails", targetNamespace = "https://ws.esortcode.com", wsdlLocation = "META-INF/wsdl/10130_United_Kingdom_bankdetails.wsdl")
public class BankDetails
    extends Service
{

    private final static URL BANKDETAILS_WSDL_LOCATION;
    private final static WebServiceException BANKDETAILS_EXCEPTION;
    private final static QName BANKDETAILS_QNAME = new QName("https://ws.esortcode.com", "BankDetails");

    static {
        BANKDETAILS_WSDL_LOCATION = https.ws_esortcode.BankDetails.class.getClassLoader().getResource("META-INF/wsdl/10130_United_Kingdom_bankdetails.wsdl");
        WebServiceException e = null;
        if (BANKDETAILS_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/10130_United_Kingdom_bankdetails.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        BANKDETAILS_EXCEPTION = e;
    }

    public BankDetails() {
        super(__getWsdlLocation(), BANKDETAILS_QNAME);
    }

    public BankDetails(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANKDETAILS_QNAME, features);
    }

    public BankDetails(URL wsdlLocation) {
        super(wsdlLocation, BANKDETAILS_QNAME);
    }

    public BankDetails(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANKDETAILS_QNAME, features);
    }

    public BankDetails(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankDetails(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BankDetailsSoap
     */
    @WebEndpoint(name = "BankDetailsSoap")
    public BankDetailsSoap getBankDetailsSoap() {
        return super.getPort(new QName("https://ws.esortcode.com", "BankDetailsSoap"), BankDetailsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankDetailsSoap
     */
    @WebEndpoint(name = "BankDetailsSoap")
    public BankDetailsSoap getBankDetailsSoap(WebServiceFeature... features) {
        return super.getPort(new QName("https://ws.esortcode.com", "BankDetailsSoap"), BankDetailsSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANKDETAILS_EXCEPTION!= null) {
            throw BANKDETAILS_EXCEPTION;
        }
        return BANKDETAILS_WSDL_LOCATION;
    }

}
