
package uk.ac.ebi.webservices.whatizit.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "whatizit", targetNamespace = "http://www.ebi.ac.uk/webservices/whatizit/ws")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Whatizit {


    /**
     * 
     * @param pipelineName
     * @param convertToHtml
     * @param text
     * @return
     *     returns java.lang.String
     * @throws WhatizitException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "contact", targetNamespace = "http://www.ebi.ac.uk/webservices/whatizit/ws", className = "uk.ac.ebi.webservices.whatizit.ws.Contact")
    @ResponseWrapper(localName = "contactResponse", targetNamespace = "http://www.ebi.ac.uk/webservices/whatizit/ws", className = "uk.ac.ebi.webservices.whatizit.ws.ContactResponse")
    public String contact(
        @WebParam(name = "pipelineName", targetNamespace = "")
        String pipelineName,
        @WebParam(name = "text", targetNamespace = "")
        String text,
        @WebParam(name = "convertToHtml", targetNamespace = "")
        boolean convertToHtml)
        throws WhatizitException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<uk.ac.ebi.webservices.whatizit.ws.SelectItem>
     * @throws WhatizitException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPipelinesStatus", targetNamespace = "http://www.ebi.ac.uk/webservices/whatizit/ws", className = "uk.ac.ebi.webservices.whatizit.ws.GetPipelinesStatus")
    @ResponseWrapper(localName = "getPipelinesStatusResponse", targetNamespace = "http://www.ebi.ac.uk/webservices/whatizit/ws", className = "uk.ac.ebi.webservices.whatizit.ws.GetPipelinesStatusResponse")
    public List<SelectItem> getPipelinesStatus()
        throws WhatizitException_Exception
    ;

    /**
     * 
     * @param pipelineName
     * @param pmid
     * @return
     *     returns java.lang.String
     * @throws WhatizitException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryPmid", targetNamespace = "http://www.ebi.ac.uk/webservices/whatizit/ws", className = "uk.ac.ebi.webservices.whatizit.ws.QueryPmid")
    @ResponseWrapper(localName = "queryPmidResponse", targetNamespace = "http://www.ebi.ac.uk/webservices/whatizit/ws", className = "uk.ac.ebi.webservices.whatizit.ws.QueryPmidResponse")
    public String queryPmid(
        @WebParam(name = "pipelineName", targetNamespace = "")
        String pipelineName,
        @WebParam(name = "pmid", targetNamespace = "")
        String pmid)
        throws WhatizitException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns uk.ac.ebi.webservices.whatizit.ws.SearchResponse
     * @throws WhatizitException_Exception
     */
    @WebMethod
    @WebResult(name = "searchResponse", targetNamespace = "http://www.ebi.ac.uk/webservices/whatizit/ws", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public SearchResponse search(
        @WebParam(name = "search", targetNamespace = "http://www.ebi.ac.uk/webservices/whatizit/ws", partName = "parameters")
        Search parameters)
        throws WhatizitException_Exception
    ;

}
