
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.tourico.schemas.webservices.hotelv3.AmendRequest;
import com.tourico.schemas.webservices.hotelv3.AmendResult;
import com.tourico.schemas.webservices.hotelv3.BookV3Request;
import com.tourico.schemas.webservices.hotelv3.CostAmendRequest;
import com.tourico.schemas.webservices.hotelv3.RGInfoRequest;
import com.tourico.schemas.webservices.hotelv3.RGInfoResults;
import com.tourico.schemas.webservices.hotelv3.SearchHotelsByDestinationIdsRequest;
import com.tourico.schemas.webservices.hotelv3.SearchHotelsByIdRequest;
import com.tourico.schemas.webservices.hotelv3.SearchRequest;
import com.tourico.schemas.webservices.hotelv3.SearchResult;
import com.tourico.schemas.webservices.hotelv3.TermAndConditionsRequest;
import com.tourico.schemas.webservices.hotelv3.TermAndConditionsResult;
import com.tourico.webservices.CancellationFeeInfo;
import com.tourico.webservices.hotelv3.ArrayOfFeature;
import com.tourico.webservices.hotelv3.ArrayOfHotelID;
import com.tourico.webservices.tws_clxpolicies.HotelPolicyType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IHotelFlow", targetNamespace = "http://tourico.com/webservices/hotelv3")
@XmlSeeAlso({
    com.tourico.webservices.hotelv3.ObjectFactory.class,
    org.tempuri.tws_hoteldetailsv3.ObjectFactory.class,
    com.tourico.schemas.webservices.ObjectFactory.class,
    com.tourico.schemas.webservices.authentication.ObjectFactory.class,
    com.tourico.schemas.webservices.faults.ObjectFactory.class,
    com.tourico.schemas.webservices.hotelv3.ObjectFactory.class,
    com.tourico.webservices.ObjectFactory.class,
    com.tourico.webservices.tws_clxpolicies.ObjectFactory.class
})
public interface IHotelFlow {


    /**
     * 
     * @param request
     * @return
     *     returns com.tourico.schemas.webservices.hotelv3.SearchResult
     * @throws IHotelFlowSearchHotelsWSFaultFaultMessage
     */
    @WebMethod(operationName = "SearchHotels", action = "http://tourico.com/webservices/hotelv3/IHotelFlow/SearchHotels")
    @WebResult(name = "SearchHotelsResult", targetNamespace = "http://tourico.com/webservices/hotelv3")
    @RequestWrapper(localName = "SearchHotels", targetNamespace = "http://tourico.com/webservices/hotelv3", className = "com.tourico.webservices.hotelv3.SearchHotels")
    @ResponseWrapper(localName = "SearchHotelsResponse", targetNamespace = "http://tourico.com/webservices/hotelv3", className = "com.tourico.webservices.hotelv3.SearchHotelsResponse")
    public SearchResult searchHotels(
        @WebParam(name = "request", targetNamespace = "http://tourico.com/webservices/hotelv3")
        SearchRequest request)
        throws IHotelFlowSearchHotelsWSFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.tourico.schemas.webservices.hotelv3.SearchResult
     * @throws IHotelFlowSearchHotelsByIdWSFaultFaultMessage
     */
    @WebMethod(operationName = "SearchHotelsById", action = "http://tourico.com/webservices/hotelv3/IHotelFlow/SearchHotelsById")
    @WebResult(name = "SearchHotelsByIdResult", targetNamespace = "http://tourico.com/webservices/hotelv3")
    @RequestWrapper(localName = "SearchHotelsById", targetNamespace = "http://tourico.com/webservices/hotelv3", className = "com.tourico.webservices.hotelv3.SearchHotelsById")
    @ResponseWrapper(localName = "SearchHotelsByIdResponse", targetNamespace = "http://tourico.com/webservices/hotelv3", className = "com.tourico.webservices.hotelv3.SearchHotelsByIdResponse")
    public SearchResult searchHotelsById(
        @WebParam(name = "request", targetNamespace = "http://tourico.com/webservices/hotelv3")
        SearchHotelsByIdRequest request)
        throws IHotelFlowSearchHotelsByIdWSFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.tourico.schemas.webservices.hotelv3.SearchResult
     * @throws IHotelFlowCheckAvailabilityAndPricesWSFaultFaultMessage
     */
    @WebMethod(operationName = "CheckAvailabilityAndPrices", action = "http://tourico.com/webservices/hotelv3/IHotelFlow/CheckAvailabilityAndPrices")
    @WebResult(name = "CheckAvailabilityAndPricesResult", targetNamespace = "http://tourico.com/webservices/hotelv3")
    @RequestWrapper(localName = "CheckAvailabilityAndPrices", targetNamespace = "http://tourico.com/webservices/hotelv3", className = "com.tourico.webservices.hotelv3.CheckAvailabilityAndPrices")
    @ResponseWrapper(localName = "CheckAvailabilityAndPricesResponse", targetNamespace = "http://tourico.com/webservices/hotelv3", className = "com.tourico.webservices.hotelv3.CheckAvailabilityAndPricesResponse")
    public SearchResult checkAvailabilityAndPrices(
        @WebParam(name = "request", targetNamespace = "http://tourico.com/webservices/hotelv3")
        SearchHotelsByIdRequest request)
        throws IHotelFlowCheckAvailabilityAndPricesWSFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.tourico.schemas.webservices.hotelv3.SearchResult
     * @throws IHotelFlowSearchHotelsByDestinationIdsWSFaultFaultMessage
     */
    @WebMethod(operationName = "SearchHotelsByDestinationIds", action = "http://tourico.com/webservices/hotelv3/IHotelFlow/SearchHotelsByDestinationIds")
    @WebResult(name = "SearchHotelsByDestinationIdsResult", targetNamespace = "http://tourico.com/webservices/hotelv3")
    @RequestWrapper(localName = "SearchHotelsByDestinationIds", targetNamespace = "http://tourico.com/webservices/hotelv3", className = "com.tourico.webservices.hotelv3.SearchHotelsByDestinationIds")
    @ResponseWrapper(localName = "SearchHotelsByDestinationIdsResponse", targetNamespace = "http://tourico.com/webservices/hotelv3", className = "com.tourico.webservices.hotelv3.SearchHotelsByDestinationIdsResponse")
    public SearchResult searchHotelsByDestinationIds(
        @WebParam(name = "request", targetNamespace = "http://tourico.com/webservices/hotelv3")
        SearchHotelsByDestinationIdsRequest request)
        throws IHotelFlowSearchHotelsByDestinationIdsWSFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.tourico.schemas.webservices.hotelv3.RGInfoResults
     * @throws IHotelFlowBookHotelV3WSFaultFaultMessage
     */
    @WebMethod(operationName = "BookHotelV3", action = "http://tourico.com/webservices/hotelv3/IHotelFlow/BookHotelV3")
    @WebResult(name = "BookHotelV3Result", targetNamespace = "http://tourico.com/webservices/hotelv3")
    @RequestWrapper(localName = "BookHotelV3", targetNamespace = "http://tourico.com/webservices/hotelv3", className = "com.tourico.webservices.hotelv3.BookHotelV3")
    @ResponseWrapper(localName = "BookHotelV3Response", targetNamespace = "http://tourico.com/webservices/hotelv3", className = "com.tourico.webservices.hotelv3.BookHotelV3Response")
    public RGInfoResults bookHotelV3(
        @WebParam(name = "request", targetNamespace = "http://tourico.com/webservices/hotelv3")
        BookV3Request request)
        throws IHotelFlowBookHotelV3WSFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.tourico.schemas.webservices.hotelv3.RGInfoResults
     * @throws IHotelFlowGetRGInfoWSFaultFaultMessage
     */
    @WebMethod(operationName = "GetRGInfo", action = "http://tourico.com/webservices/hotelv3/IHotelFlow/GetRGInfo")
    @WebResult(name = "GetRGInfoResult", targetNamespace = "http://tourico.com/webservices/hotelv3")
    @RequestWrapper(localName = "GetRGInfo", targetNamespace = "http://tourico.com/webservices/hotelv3", className = "com.tourico.webservices.hotelv3.GetRGInfo")
    @ResponseWrapper(localName = "GetRGInfoResponse", targetNamespace = "http://tourico.com/webservices/hotelv3", className = "com.tourico.webservices.hotelv3.GetRGInfoResponse")
    public RGInfoResults getRGInfo(
        @WebParam(name = "request", targetNamespace = "http://tourico.com/webservices/hotelv3")
        RGInfoRequest request)
        throws IHotelFlowGetRGInfoWSFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.tourico.schemas.webservices.hotelv3.AmendResult
     * @throws IHotelFlowDoAmendWSFaultFaultMessage
     */
    @WebMethod(operationName = "DoAmend", action = "http://tourico.com/webservices/hotelv3/IHotelFlow/DoAmend")
    @WebResult(name = "DoAmendResult", targetNamespace = "http://tourico.com/webservices/hotelv3")
    @RequestWrapper(localName = "DoAmend", targetNamespace = "http://tourico.com/webservices/hotelv3", className = "com.tourico.webservices.hotelv3.DoAmend")
    @ResponseWrapper(localName = "DoAmendResponse", targetNamespace = "http://tourico.com/webservices/hotelv3", className = "com.tourico.webservices.hotelv3.DoAmendResponse")
    public AmendResult doAmend(
        @WebParam(name = "request", targetNamespace = "http://tourico.com/webservices/hotelv3")
        AmendRequest request)
        throws IHotelFlowDoAmendWSFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.tourico.schemas.webservices.hotelv3.AmendResult
     * @throws IHotelFlowCostAmendWSFaultFaultMessage
     */
    @WebMethod(operationName = "CostAmend", action = "http://tourico.com/webservices/hotelv3/IHotelFlow/CostAmend")
    @WebResult(name = "CostAmendResult", targetNamespace = "http://tourico.com/webservices/hotelv3")
    @RequestWrapper(localName = "CostAmend", targetNamespace = "http://tourico.com/webservices/hotelv3", className = "com.tourico.webservices.hotelv3.CostAmend")
    @ResponseWrapper(localName = "CostAmendResponse", targetNamespace = "http://tourico.com/webservices/hotelv3", className = "com.tourico.webservices.hotelv3.CostAmendResponse")
    public AmendResult costAmend(
        @WebParam(name = "request", targetNamespace = "http://tourico.com/webservices/hotelv3")
        CostAmendRequest request)
        throws IHotelFlowCostAmendWSFaultFaultMessage
    ;

    /**
     * 
     * @param features
     * @param hotelIds
     * @return
     *     returns com.tourico.webservices.hotelv3.GetHotelDetailsV3Response.GetHotelDetailsV3Result
     * @throws IHotelFlowGetHotelDetailsV3WSFaultFaultMessage
     */
    @WebMethod(operationName = "GetHotelDetailsV3", action = "http://tourico.com/webservices/hotelv3/IHotelFlow/GetHotelDetailsV3")
    @WebResult(name = "GetHotelDetailsV3Result", targetNamespace = "http://tourico.com/webservices/hotelv3")
    @RequestWrapper(localName = "GetHotelDetailsV3", targetNamespace = "http://tourico.com/webservices/hotelv3", className = "com.tourico.webservices.hotelv3.GetHotelDetailsV3")
    @ResponseWrapper(localName = "GetHotelDetailsV3Response", targetNamespace = "http://tourico.com/webservices/hotelv3", className = "com.tourico.webservices.hotelv3.GetHotelDetailsV3Response")
    public com.tourico.webservices.hotelv3.GetHotelDetailsV3Response.GetHotelDetailsV3Result getHotelDetailsV3(
        @WebParam(name = "HotelIds", targetNamespace = "http://tourico.com/webservices/hotelv3")
        ArrayOfHotelID hotelIds,
        @WebParam(name = "Features", targetNamespace = "http://tourico.com/webservices/hotelv3")
        ArrayOfFeature features)
        throws IHotelFlowGetHotelDetailsV3WSFaultFaultMessage
    ;

    /**
     * 
     * @param hotelId
     * @return
     *     returns com.tourico.schemas.webservices.hotelv3.TermAndConditionsResult
     * @throws IHotelFlowGetTermAndConditionsWSFaultFaultMessage
     */
    @WebMethod(operationName = "GetTermAndConditions", action = "http://tourico.com/webservices/hotelv3/IHotelFlow/GetTermAndConditions")
    @WebResult(name = "GetTermAndConditionsResult", targetNamespace = "http://tourico.com/webservices/hotelv3")
    @RequestWrapper(localName = "GetTermAndConditions", targetNamespace = "http://tourico.com/webservices/hotelv3", className = "com.tourico.webservices.hotelv3.GetTermAndConditions")
    @ResponseWrapper(localName = "GetTermAndConditionsResponse", targetNamespace = "http://tourico.com/webservices/hotelv3", className = "com.tourico.webservices.hotelv3.GetTermAndConditionsResponse")
    public TermAndConditionsResult getTermAndConditions(
        @WebParam(name = "HotelId", targetNamespace = "http://tourico.com/webservices/hotelv3")
        TermAndConditionsRequest hotelId)
        throws IHotelFlowGetTermAndConditionsWSFaultFaultMessage
    ;

    /**
     * 
     * @param clxDate
     * @param nResID
     * @return
     *     returns com.tourico.webservices.CancellationFeeInfo
     * @throws IHotelFlowGetCancellationFeeWSFaultFaultMessage
     */
    @WebMethod(operationName = "GetCancellationFee", action = "http://tourico.com/webservices/hotelv3/IHotelFlow/GetCancellationFee")
    @WebResult(name = "GetCancellationFeeResult", targetNamespace = "http://tourico.com/webservices/")
    @RequestWrapper(localName = "GetCancellationFee", targetNamespace = "http://tourico.com/webservices/hotelv3", className = "com.tourico.webservices.hotelv3.GetCancellationFee")
    @ResponseWrapper(localName = "GetCancellationFeeResponse", targetNamespace = "http://tourico.com/webservices/", className = "com.tourico.webservices.GetCancellationFeeResponse")
    public CancellationFeeInfo getCancellationFee(
        @WebParam(name = "nResID", targetNamespace = "http://tourico.com/webservices/hotelv3")
        int nResID,
        @WebParam(name = "clxDate", targetNamespace = "http://tourico.com/webservices/hotelv3")
        XMLGregorianCalendar clxDate)
        throws IHotelFlowGetCancellationFeeWSFaultFaultMessage
    ;

    /**
     * 
     * @param dtCheckOut
     * @param productId
     * @param nResId
     * @param dtCheckIn
     * @param hotelRoomTypeId
     * @param hotelId
     * @return
     *     returns com.tourico.webservices.tws_clxpolicies.HotelPolicyType
     * @throws IHotelFlowGetCancellationPoliciesWSFaultFaultMessage
     */
    @WebMethod(operationName = "GetCancellationPolicies", action = "http://tourico.com/webservices/hotelv3/IHotelFlow/GetCancellationPolicies")
    @WebResult(name = "HotelPolicy", targetNamespace = "http://tourico.com/webservices/TWS_ClxPolicies.xsd")
    @RequestWrapper(localName = "GetCancellationPolicies", targetNamespace = "http://tourico.com/webservices/hotelv3", className = "com.tourico.webservices.hotelv3.GetCancellationPolicies")
    @ResponseWrapper(localName = "GetCancellationPoliciesResponse", targetNamespace = "http://tourico.com/webservices/", className = "com.tourico.webservices.GetCancellationPoliciesResponse")
    public HotelPolicyType getCancellationPolicies(
        @WebParam(name = "nResId", targetNamespace = "http://tourico.com/webservices/hotelv3")
        int nResId,
        @WebParam(name = "hotelId", targetNamespace = "http://tourico.com/webservices/hotelv3")
        int hotelId,
        @WebParam(name = "hotelRoomTypeId", targetNamespace = "http://tourico.com/webservices/hotelv3")
        int hotelRoomTypeId,
        @WebParam(name = "productId", targetNamespace = "http://tourico.com/webservices/hotelv3")
        String productId,
        @WebParam(name = "dtCheckIn", targetNamespace = "http://tourico.com/webservices/hotelv3")
        XMLGregorianCalendar dtCheckIn,
        @WebParam(name = "dtCheckOut", targetNamespace = "http://tourico.com/webservices/hotelv3")
        XMLGregorianCalendar dtCheckOut)
        throws IHotelFlowGetCancellationPoliciesWSFaultFaultMessage
    ;

}
