
package com.nuwave_tech.soapam.services.bankdemo;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * his service provides methods for executing bank transactions
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BankingService", targetNamespace = "http://soapam.nuwave-tech.com/services/bankdemo", wsdlLocation = "META-INF/wsdl/14890_United_States_bankdemo.wsdl")
public class BankingService
    extends Service
{

    private final static URL BANKINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException BANKINGSERVICE_EXCEPTION;
    private final static QName BANKINGSERVICE_QNAME = new QName("http://soapam.nuwave-tech.com/services/bankdemo", "BankingService");

    static {
        BANKINGSERVICE_WSDL_LOCATION = com.nuwave_tech.soapam.services.bankdemo.BankingService.class.getClassLoader().getResource("META-INF/wsdl/14890_United_States_bankdemo.wsdl");
        WebServiceException e = null;
        if (BANKINGSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/14890_United_States_bankdemo.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        BANKINGSERVICE_EXCEPTION = e;
    }

    public BankingService() {
        super(__getWsdlLocation(), BANKINGSERVICE_QNAME);
    }

    public BankingService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANKINGSERVICE_QNAME, features);
    }

    public BankingService(URL wsdlLocation) {
        super(wsdlLocation, BANKINGSERVICE_QNAME);
    }

    public BankingService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANKINGSERVICE_QNAME, features);
    }

    public BankingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankingService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BankingServiceSoap
     */
    @WebEndpoint(name = "BankingServiceSoap")
    public BankingServiceSoap getBankingServiceSoap() {
        return super.getPort(new QName("http://soapam.nuwave-tech.com/services/bankdemo", "BankingServiceSoap"), BankingServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankingServiceSoap
     */
    @WebEndpoint(name = "BankingServiceSoap")
    public BankingServiceSoap getBankingServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://soapam.nuwave-tech.com/services/bankdemo", "BankingServiceSoap"), BankingServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANKINGSERVICE_EXCEPTION!= null) {
            throw BANKINGSERVICE_EXCEPTION;
        }
        return BANKINGSERVICE_WSDL_LOCATION;
    }

}
