
package es.juniper.webservice._2007;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JP_HotelList", targetNamespace = "http://www.juniper.es/webservice/2007/", wsdlLocation = "META-INF/wsdl/JP_HotelList.wsdl")
public class JPHotelList
    extends Service
{

    private final static URL JPHOTELLIST_WSDL_LOCATION;
    private final static WebServiceException JPHOTELLIST_EXCEPTION;
    private final static QName JPHOTELLIST_QNAME = new QName("http://www.juniper.es/webservice/2007/", "JP_HotelList");

    static {
        JPHOTELLIST_WSDL_LOCATION = es.juniper.webservice._2007.JPHotelList.class.getClassLoader().getResource("META-INF/wsdl/JP_HotelList.wsdl");
        WebServiceException e = null;
        if (JPHOTELLIST_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/JP_HotelList.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        JPHOTELLIST_EXCEPTION = e;
    }

    public JPHotelList() {
        super(__getWsdlLocation(), JPHOTELLIST_QNAME);
    }

    public JPHotelList(WebServiceFeature... features) {
        super(__getWsdlLocation(), JPHOTELLIST_QNAME, features);
    }

    public JPHotelList(URL wsdlLocation) {
        super(wsdlLocation, JPHOTELLIST_QNAME);
    }

    public JPHotelList(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JPHOTELLIST_QNAME, features);
    }

    public JPHotelList(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JPHotelList(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JPHotelListSoap
     */
    @WebEndpoint(name = "JP_HotelListSoap")
    public JPHotelListSoap getJPHotelListSoap() {
        return super.getPort(new QName("http://www.juniper.es/webservice/2007/", "JP_HotelListSoap"), JPHotelListSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JPHotelListSoap
     */
    @WebEndpoint(name = "JP_HotelListSoap")
    public JPHotelListSoap getJPHotelListSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.juniper.es/webservice/2007/", "JP_HotelListSoap"), JPHotelListSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JPHOTELLIST_EXCEPTION!= null) {
            throw JPHOTELLIST_EXCEPTION;
        }
        return JPHOTELLIST_WSDL_LOCATION;
    }

}
