
package com.vodafone.gdsp.ws;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CloneCustomerServiceProfilev5Service", targetNamespace = "http://ws.gdsp.vodafone.com/", wsdlLocation = "META-INF/wsdl/extWebServices.wsdl")
public class CloneCustomerServiceProfilev5Service
    extends Service
{

    private final static URL CLONECUSTOMERSERVICEPROFILEV5SERVICE_WSDL_LOCATION;
    private final static WebServiceException CLONECUSTOMERSERVICEPROFILEV5SERVICE_EXCEPTION;
    private final static QName CLONECUSTOMERSERVICEPROFILEV5SERVICE_QNAME = new QName("http://ws.gdsp.vodafone.com/", "CloneCustomerServiceProfilev5Service");

    static {
        CLONECUSTOMERSERVICEPROFILEV5SERVICE_WSDL_LOCATION = com.vodafone.gdsp.ws.CloneCustomerServiceProfilev5Service.class.getClassLoader().getResource("META-INF/wsdl/extWebServices.wsdl");
        WebServiceException e = null;
        if (CLONECUSTOMERSERVICEPROFILEV5SERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/extWebServices.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CLONECUSTOMERSERVICEPROFILEV5SERVICE_EXCEPTION = e;
    }

    public CloneCustomerServiceProfilev5Service() {
        super(__getWsdlLocation(), CLONECUSTOMERSERVICEPROFILEV5SERVICE_QNAME);
    }

    public CloneCustomerServiceProfilev5Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLONECUSTOMERSERVICEPROFILEV5SERVICE_QNAME, features);
    }

    public CloneCustomerServiceProfilev5Service(URL wsdlLocation) {
        super(wsdlLocation, CLONECUSTOMERSERVICEPROFILEV5SERVICE_QNAME);
    }

    public CloneCustomerServiceProfilev5Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLONECUSTOMERSERVICEPROFILEV5SERVICE_QNAME, features);
    }

    public CloneCustomerServiceProfilev5Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CloneCustomerServiceProfilev5Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CloneCustomerServiceProfilev5
     */
    @WebEndpoint(name = "CloneCustomerServiceProfilev5Port")
    public CloneCustomerServiceProfilev5 getCloneCustomerServiceProfilev5Port() {
        return super.getPort(new QName("http://ws.gdsp.vodafone.com/", "CloneCustomerServiceProfilev5Port"), CloneCustomerServiceProfilev5.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CloneCustomerServiceProfilev5
     */
    @WebEndpoint(name = "CloneCustomerServiceProfilev5Port")
    public CloneCustomerServiceProfilev5 getCloneCustomerServiceProfilev5Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.gdsp.vodafone.com/", "CloneCustomerServiceProfilev5Port"), CloneCustomerServiceProfilev5.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLONECUSTOMERSERVICEPROFILEV5SERVICE_EXCEPTION!= null) {
            throw CLONECUSTOMERSERVICEPROFILEV5SERVICE_EXCEPTION;
        }
        return CLONECUSTOMERSERVICEPROFILEV5SERVICE_WSDL_LOCATION;
    }

}
