
package com.vodafone.gdsp.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DeviceCredentials", targetNamespace = "http://ws.gdsp.vodafone.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DeviceCredentials {


    /**
     * 
     * @param gdspHeader
     * @param parameters
     * @return
     *     returns com.vodafone.gdsp.ws.SetDeviceCredentialsResponse
     */
    @WebMethod
    @WebResult(name = "setDeviceCredentialsResponse", targetNamespace = "http://ws.gdsp.vodafone.com/", partName = "result")
    public SetDeviceCredentialsResponse setDeviceCredentials(
        @WebParam(name = "setDeviceCredentials", targetNamespace = "http://ws.gdsp.vodafone.com/", partName = "parameters")
        SetDeviceCredentials parameters,
        @WebParam(name = "gdspHeader", targetNamespace = "http://ws.gdsp.vodafone.com/", header = true, partName = "gdspHeader")
        GdspHeader gdspHeader);

    /**
     * 
     * @param gdspHeader
     * @param parameters
     * @return
     *     returns com.vodafone.gdsp.ws.UpdateDeviceCredentialsResponse
     */
    @WebMethod
    @WebResult(name = "updateDeviceCredentialsResponse", targetNamespace = "http://ws.gdsp.vodafone.com/", partName = "result")
    public UpdateDeviceCredentialsResponse updateDeviceCredentials(
        @WebParam(name = "updateDeviceCredentials", targetNamespace = "http://ws.gdsp.vodafone.com/", partName = "parameters")
        UpdateDeviceCredentials parameters,
        @WebParam(name = "gdspHeader", targetNamespace = "http://ws.gdsp.vodafone.com/", header = true, partName = "gdspHeader")
        GdspHeader gdspHeader);

}
