
package com.vodafone.gdsp.ws;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetCustomerServiceProfileDetails", targetNamespace = "http://ws.gdsp.vodafone.com/", wsdlLocation = "META-INF/wsdl/extWebServices.wsdl")
public class GetCustomerServiceProfileDetails_Service
    extends Service
{

    private final static URL GETCUSTOMERSERVICEPROFILEDETAILS_WSDL_LOCATION;
    private final static WebServiceException GETCUSTOMERSERVICEPROFILEDETAILS_EXCEPTION;
    private final static QName GETCUSTOMERSERVICEPROFILEDETAILS_QNAME = new QName("http://ws.gdsp.vodafone.com/", "GetCustomerServiceProfileDetails");

    static {
        GETCUSTOMERSERVICEPROFILEDETAILS_WSDL_LOCATION = com.vodafone.gdsp.ws.GetCustomerServiceProfileDetails_Service.class.getClassLoader().getResource("META-INF/wsdl/extWebServices.wsdl");
        WebServiceException e = null;
        if (GETCUSTOMERSERVICEPROFILEDETAILS_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/extWebServices.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        GETCUSTOMERSERVICEPROFILEDETAILS_EXCEPTION = e;
    }

    public GetCustomerServiceProfileDetails_Service() {
        super(__getWsdlLocation(), GETCUSTOMERSERVICEPROFILEDETAILS_QNAME);
    }

    public GetCustomerServiceProfileDetails_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETCUSTOMERSERVICEPROFILEDETAILS_QNAME, features);
    }

    public GetCustomerServiceProfileDetails_Service(URL wsdlLocation) {
        super(wsdlLocation, GETCUSTOMERSERVICEPROFILEDETAILS_QNAME);
    }

    public GetCustomerServiceProfileDetails_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETCUSTOMERSERVICEPROFILEDETAILS_QNAME, features);
    }

    public GetCustomerServiceProfileDetails_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetCustomerServiceProfileDetails_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetCustomerServiceProfileDetails
     */
    @WebEndpoint(name = "GetCustomerServiceProfileDetailsPort")
    public GetCustomerServiceProfileDetails getGetCustomerServiceProfileDetailsPort() {
        return super.getPort(new QName("http://ws.gdsp.vodafone.com/", "GetCustomerServiceProfileDetailsPort"), GetCustomerServiceProfileDetails.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetCustomerServiceProfileDetails
     */
    @WebEndpoint(name = "GetCustomerServiceProfileDetailsPort")
    public GetCustomerServiceProfileDetails getGetCustomerServiceProfileDetailsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.gdsp.vodafone.com/", "GetCustomerServiceProfileDetailsPort"), GetCustomerServiceProfileDetails.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETCUSTOMERSERVICEPROFILEDETAILS_EXCEPTION!= null) {
            throw GETCUSTOMERSERVICEPROFILEDETAILS_EXCEPTION;
        }
        return GETCUSTOMERSERVICEPROFILEDETAILS_WSDL_LOCATION;
    }

}
