
package com.vodafone.gdsp.ws;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetDeviceStateListService", targetNamespace = "http://ws.gdsp.vodafone.com/", wsdlLocation = "META-INF/wsdl/extWebServices.wsdl")
public class GetDeviceStateListService
    extends Service
{

    private final static URL GETDEVICESTATELISTSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETDEVICESTATELISTSERVICE_EXCEPTION;
    private final static QName GETDEVICESTATELISTSERVICE_QNAME = new QName("http://ws.gdsp.vodafone.com/", "GetDeviceStateListService");

    static {
        GETDEVICESTATELISTSERVICE_WSDL_LOCATION = com.vodafone.gdsp.ws.GetDeviceStateListService.class.getClassLoader().getResource("META-INF/wsdl/extWebServices.wsdl");
        WebServiceException e = null;
        if (GETDEVICESTATELISTSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/extWebServices.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        GETDEVICESTATELISTSERVICE_EXCEPTION = e;
    }

    public GetDeviceStateListService() {
        super(__getWsdlLocation(), GETDEVICESTATELISTSERVICE_QNAME);
    }

    public GetDeviceStateListService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETDEVICESTATELISTSERVICE_QNAME, features);
    }

    public GetDeviceStateListService(URL wsdlLocation) {
        super(wsdlLocation, GETDEVICESTATELISTSERVICE_QNAME);
    }

    public GetDeviceStateListService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETDEVICESTATELISTSERVICE_QNAME, features);
    }

    public GetDeviceStateListService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetDeviceStateListService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetDeviceStateList
     */
    @WebEndpoint(name = "GetDeviceStateListPort")
    public GetDeviceStateList getGetDeviceStateListPort() {
        return super.getPort(new QName("http://ws.gdsp.vodafone.com/", "GetDeviceStateListPort"), GetDeviceStateList.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetDeviceStateList
     */
    @WebEndpoint(name = "GetDeviceStateListPort")
    public GetDeviceStateList getGetDeviceStateListPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.gdsp.vodafone.com/", "GetDeviceStateListPort"), GetDeviceStateList.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETDEVICESTATELISTSERVICE_EXCEPTION!= null) {
            throw GETDEVICESTATELISTSERVICE_EXCEPTION;
        }
        return GETDEVICESTATELISTSERVICE_WSDL_LOCATION;
    }

}
