
package com.vodafone.gdsp.ws;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetFilteredDeviceListv3Service", targetNamespace = "http://ws.gdsp.vodafone.com/", wsdlLocation = "META-INF/wsdl/extWebServices.wsdl")
public class GetFilteredDeviceListv3Service
    extends Service
{

    private final static URL GETFILTEREDDEVICELISTV3SERVICE_WSDL_LOCATION;
    private final static WebServiceException GETFILTEREDDEVICELISTV3SERVICE_EXCEPTION;
    private final static QName GETFILTEREDDEVICELISTV3SERVICE_QNAME = new QName("http://ws.gdsp.vodafone.com/", "GetFilteredDeviceListv3Service");

    static {
        GETFILTEREDDEVICELISTV3SERVICE_WSDL_LOCATION = com.vodafone.gdsp.ws.GetFilteredDeviceListv3Service.class.getClassLoader().getResource("META-INF/wsdl/extWebServices.wsdl");
        WebServiceException e = null;
        if (GETFILTEREDDEVICELISTV3SERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/extWebServices.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        GETFILTEREDDEVICELISTV3SERVICE_EXCEPTION = e;
    }

    public GetFilteredDeviceListv3Service() {
        super(__getWsdlLocation(), GETFILTEREDDEVICELISTV3SERVICE_QNAME);
    }

    public GetFilteredDeviceListv3Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETFILTEREDDEVICELISTV3SERVICE_QNAME, features);
    }

    public GetFilteredDeviceListv3Service(URL wsdlLocation) {
        super(wsdlLocation, GETFILTEREDDEVICELISTV3SERVICE_QNAME);
    }

    public GetFilteredDeviceListv3Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETFILTEREDDEVICELISTV3SERVICE_QNAME, features);
    }

    public GetFilteredDeviceListv3Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetFilteredDeviceListv3Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetFilteredDeviceListv3
     */
    @WebEndpoint(name = "GetFilteredDeviceListv3Port")
    public GetFilteredDeviceListv3 getGetFilteredDeviceListv3Port() {
        return super.getPort(new QName("http://ws.gdsp.vodafone.com/", "GetFilteredDeviceListv3Port"), GetFilteredDeviceListv3.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetFilteredDeviceListv3
     */
    @WebEndpoint(name = "GetFilteredDeviceListv3Port")
    public GetFilteredDeviceListv3 getGetFilteredDeviceListv3Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.gdsp.vodafone.com/", "GetFilteredDeviceListv3Port"), GetFilteredDeviceListv3.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETFILTEREDDEVICELISTV3SERVICE_EXCEPTION!= null) {
            throw GETFILTEREDDEVICELISTV3SERVICE_EXCEPTION;
        }
        return GETFILTEREDDEVICELISTV3SERVICE_WSDL_LOCATION;
    }

}
