
package com.vodafone.gdsp.ws;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetReportService", targetNamespace = "http://ws.gdsp.vodafone.com/", wsdlLocation = "META-INF/wsdl/extWebServices.wsdl")
public class GetReportService
    extends Service
{

    private final static URL GETREPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETREPORTSERVICE_EXCEPTION;
    private final static QName GETREPORTSERVICE_QNAME = new QName("http://ws.gdsp.vodafone.com/", "GetReportService");

    static {
        GETREPORTSERVICE_WSDL_LOCATION = com.vodafone.gdsp.ws.GetReportService.class.getClassLoader().getResource("META-INF/wsdl/extWebServices.wsdl");
        WebServiceException e = null;
        if (GETREPORTSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/extWebServices.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        GETREPORTSERVICE_EXCEPTION = e;
    }

    public GetReportService() {
        super(__getWsdlLocation(), GETREPORTSERVICE_QNAME);
    }

    public GetReportService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETREPORTSERVICE_QNAME, features);
    }

    public GetReportService(URL wsdlLocation) {
        super(wsdlLocation, GETREPORTSERVICE_QNAME);
    }

    public GetReportService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETREPORTSERVICE_QNAME, features);
    }

    public GetReportService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetReportService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetReport
     */
    @WebEndpoint(name = "GetReportPort")
    public GetReport getGetReportPort() {
        return super.getPort(new QName("http://ws.gdsp.vodafone.com/", "GetReportPort"), GetReport.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetReport
     */
    @WebEndpoint(name = "GetReportPort")
    public GetReport getGetReportPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.gdsp.vodafone.com/", "GetReportPort"), GetReport.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETREPORTSERVICE_EXCEPTION!= null) {
            throw GETREPORTSERVICE_EXCEPTION;
        }
        return GETREPORTSERVICE_WSDL_LOCATION;
    }

}
