
package com.vodafone.gdsp.ws;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetReportDetailsService", targetNamespace = "http://ws.gdsp.vodafone.com/", wsdlLocation = "META-INF/wsdl/extWebServices.wsdl")
public class GetReportDetailsService
    extends Service
{

    private final static URL GETREPORTDETAILSSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETREPORTDETAILSSERVICE_EXCEPTION;
    private final static QName GETREPORTDETAILSSERVICE_QNAME = new QName("http://ws.gdsp.vodafone.com/", "GetReportDetailsService");

    static {
        GETREPORTDETAILSSERVICE_WSDL_LOCATION = com.vodafone.gdsp.ws.GetReportDetailsService.class.getClassLoader().getResource("META-INF/wsdl/extWebServices.wsdl");
        WebServiceException e = null;
        if (GETREPORTDETAILSSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/extWebServices.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        GETREPORTDETAILSSERVICE_EXCEPTION = e;
    }

    public GetReportDetailsService() {
        super(__getWsdlLocation(), GETREPORTDETAILSSERVICE_QNAME);
    }

    public GetReportDetailsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETREPORTDETAILSSERVICE_QNAME, features);
    }

    public GetReportDetailsService(URL wsdlLocation) {
        super(wsdlLocation, GETREPORTDETAILSSERVICE_QNAME);
    }

    public GetReportDetailsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETREPORTDETAILSSERVICE_QNAME, features);
    }

    public GetReportDetailsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetReportDetailsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetReportDetails
     */
    @WebEndpoint(name = "GetReportDetailsPort")
    public GetReportDetails getGetReportDetailsPort() {
        return super.getPort(new QName("http://ws.gdsp.vodafone.com/", "GetReportDetailsPort"), GetReportDetails.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetReportDetails
     */
    @WebEndpoint(name = "GetReportDetailsPort")
    public GetReportDetails getGetReportDetailsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.gdsp.vodafone.com/", "GetReportDetailsPort"), GetReportDetails.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETREPORTDETAILSSERVICE_EXCEPTION!= null) {
            throw GETREPORTDETAILSSERVICE_EXCEPTION;
        }
        return GETREPORTDETAILSSERVICE_WSDL_LOCATION;
    }

}
