
package com.vodafone.gdsp.ws;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetUserListService", targetNamespace = "http://ws.gdsp.vodafone.com/", wsdlLocation = "META-INF/wsdl/extWebServices.wsdl")
public class GetUserListService
    extends Service
{

    private final static URL GETUSERLISTSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETUSERLISTSERVICE_EXCEPTION;
    private final static QName GETUSERLISTSERVICE_QNAME = new QName("http://ws.gdsp.vodafone.com/", "GetUserListService");

    static {
        GETUSERLISTSERVICE_WSDL_LOCATION = com.vodafone.gdsp.ws.GetUserListService.class.getClassLoader().getResource("META-INF/wsdl/extWebServices.wsdl");
        WebServiceException e = null;
        if (GETUSERLISTSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/extWebServices.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        GETUSERLISTSERVICE_EXCEPTION = e;
    }

    public GetUserListService() {
        super(__getWsdlLocation(), GETUSERLISTSERVICE_QNAME);
    }

    public GetUserListService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETUSERLISTSERVICE_QNAME, features);
    }

    public GetUserListService(URL wsdlLocation) {
        super(wsdlLocation, GETUSERLISTSERVICE_QNAME);
    }

    public GetUserListService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETUSERLISTSERVICE_QNAME, features);
    }

    public GetUserListService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetUserListService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetUserList
     */
    @WebEndpoint(name = "GetUserListPort")
    public GetUserList getGetUserListPort() {
        return super.getPort(new QName("http://ws.gdsp.vodafone.com/", "GetUserListPort"), GetUserList.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetUserList
     */
    @WebEndpoint(name = "GetUserListPort")
    public GetUserList getGetUserListPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.gdsp.vodafone.com/", "GetUserListPort"), GetUserList.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETUSERLISTSERVICE_EXCEPTION!= null) {
            throw GETUSERLISTSERVICE_EXCEPTION;
        }
        return GETUSERLISTSERVICE_WSDL_LOCATION;
    }

}
