
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfint;
import org.datacontract.schemas._2004._07.mouzenidis_services.ArrayOfStatItem;
import org.datacontract.schemas._2004._07.mouzenidis_services.FilterParametr;
import org.datacontract.schemas._2004._07.mouzenidis_services.FlightPackets;
import org.datacontract.schemas._2004._07.mouzenidis_services.QuotaFlightsState;
import org.datacontract.schemas._2004._07.mouzenidis_services.QuotaHotelsState;
import org.datacontract.schemas._2004._07.mouzenidis_services.SearchGroupHotelResult;
import org.datacontract.schemas._2004._07.mouzenidis_services.SearchResult;
import org.datacontract.schemas._2004._07.mouzenidis_services_objects.ArrayOfDictionaryEnum;
import org.datacontract.schemas._2004._07.mouzenidis_services_objects.ArrayOfRealCourse;
import org.datacontract.schemas._2004._07.mouzenidis_services_objects.ArrayOfReturnObject;
import org.datacontract.schemas._2004._07.mouzenidis_services_objects.DictionaryEnum;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IServiceMainSearch", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    org.datacontract.schemas._2004._07.mouzenidis_services.ObjectFactory.class,
    org.datacontract.schemas._2004._07.mouzenidis_services_objects.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface IServiceMainSearch {


    /**
     * 
     * @param filter
     * @return
     *     returns org.datacontract.schemas._2004._07.mouzenidis_services.SearchResult
     */
    @WebMethod(operationName = "GetData", action = "http://tempuri.org/IServiceMainSearch/GetData")
    @WebResult(name = "GetDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetData", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetData")
    @ResponseWrapper(localName = "GetDataResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDataResponse")
    public SearchResult getData(
        @WebParam(name = "filter", targetNamespace = "http://tempuri.org/")
        FilterParametr filter);

    /**
     * 
     * @param filter
     * @return
     *     returns org.datacontract.schemas._2004._07.mouzenidis_services.SearchResult
     */
    @WebMethod(operationName = "GetDataDistinctHotels", action = "http://tempuri.org/IServiceMainSearch/GetDataDistinctHotels")
    @WebResult(name = "GetDataDistinctHotelsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDataDistinctHotels", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDataDistinctHotels")
    @ResponseWrapper(localName = "GetDataDistinctHotelsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDataDistinctHotelsResponse")
    public SearchResult getDataDistinctHotels(
        @WebParam(name = "filter", targetNamespace = "http://tempuri.org/")
        FilterParametr filter);

    /**
     * 
     * @param date
     * @param spoKey
     * @param priceKey
     * @return
     *     returns java.lang.Double
     */
    @WebMethod(operationName = "GetPriceByKey", action = "http://tempuri.org/IServiceMainSearch/GetPriceByKey")
    @WebResult(name = "GetPriceByKeyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPriceByKey", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPriceByKey")
    @ResponseWrapper(localName = "GetPriceByKeyResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPriceByKeyResponse")
    public Double getPriceByKey(
        @WebParam(name = "spoKey", targetNamespace = "http://tempuri.org/")
        Integer spoKey,
        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar date,
        @WebParam(name = "priceKey", targetNamespace = "http://tempuri.org/")
        Integer priceKey);

    /**
     * 
     * @param filter
     * @return
     *     returns org.datacontract.schemas._2004._07.mouzenidis_services.SearchResult
     */
    @WebMethod(operationName = "GetDataByTours", action = "http://tempuri.org/IServiceMainSearch/GetDataByTours")
    @WebResult(name = "GetDataByToursResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDataByTours", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDataByTours")
    @ResponseWrapper(localName = "GetDataByToursResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDataByToursResponse")
    public SearchResult getDataByTours(
        @WebParam(name = "filter", targetNamespace = "http://tempuri.org/")
        FilterParametr filter);

    /**
     * 
     * @param filter
     * @return
     *     returns org.datacontract.schemas._2004._07.mouzenidis_services.SearchGroupHotelResult
     */
    @WebMethod(operationName = "SearchTourGroupByHotel", action = "http://tempuri.org/IServiceMainSearch/SearchTourGroupByHotel")
    @WebResult(name = "SearchTourGroupByHotelResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SearchTourGroupByHotel", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchTourGroupByHotel")
    @ResponseWrapper(localName = "SearchTourGroupByHotelResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchTourGroupByHotelResponse")
    public SearchGroupHotelResult searchTourGroupByHotel(
        @WebParam(name = "filter", targetNamespace = "http://tempuri.org/")
        FilterParametr filter);

    /**
     * 
     * @param filter
     * @return
     *     returns org.datacontract.schemas._2004._07.mouzenidis_services.FlightPackets
     */
    @WebMethod(operationName = "GetFlightPackets", action = "http://tempuri.org/IServiceMainSearch/GetFlightPackets")
    @WebResult(name = "GetFlightPacketsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetFlightPackets", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetFlightPackets")
    @ResponseWrapper(localName = "GetFlightPacketsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetFlightPacketsResponse")
    public FlightPackets getFlightPackets(
        @WebParam(name = "filter", targetNamespace = "http://tempuri.org/")
        FilterParametr filter);

    /**
     * 
     * @param filter
     * @return
     *     returns org.datacontract.schemas._2004._07.mouzenidis_services.QuotaHotelsState
     */
    @WebMethod(operationName = "QuotaHotelsState", action = "http://tempuri.org/IServiceMainSearch/QuotaHotelsState")
    @WebResult(name = "QuotaHotelsStateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QuotaHotelsState", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QuotaHotelsState")
    @ResponseWrapper(localName = "QuotaHotelsStateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QuotaHotelsStateResponse")
    public QuotaHotelsState quotaHotelsState(
        @WebParam(name = "filter", targetNamespace = "http://tempuri.org/")
        FilterParametr filter);

    /**
     * 
     * @param filter
     * @return
     *     returns org.datacontract.schemas._2004._07.mouzenidis_services.QuotaFlightsState
     */
    @WebMethod(operationName = "QuotaFlightsState", action = "http://tempuri.org/IServiceMainSearch/QuotaFlightsState")
    @WebResult(name = "QuotaFlightsStateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QuotaFlightsState", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QuotaFlightsState")
    @ResponseWrapper(localName = "QuotaFlightsStateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QuotaFlightsStateResponse")
    public QuotaFlightsState quotaFlightsState(
        @WebParam(name = "filter", targetNamespace = "http://tempuri.org/")
        FilterParametr filter);

    /**
     * 
     * @param filter
     * @return
     *     returns org.datacontract.schemas._2004._07.mouzenidis_services.SearchResult
     */
    @WebMethod(operationName = "GetMinPrices", action = "http://tempuri.org/IServiceMainSearch/GetMinPrices")
    @WebResult(name = "GetMinPricesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMinPrices", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMinPrices")
    @ResponseWrapper(localName = "GetMinPricesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMinPricesResponse")
    public SearchResult getMinPrices(
        @WebParam(name = "filter", targetNamespace = "http://tempuri.org/")
        FilterParametr filter);

    /**
     * 
     * @param changedItem
     * @param cities
     * @param hotels
     * @param departureCityId
     * @param durations
     * @param categories
     * @param tours
     * @param countryId
     * @param tourTypes
     * @param meals
     * @return
     *     returns org.datacontract.schemas._2004._07.mouzenidis_services_objects.ArrayOfReturnObject
     */
    @WebMethod(operationName = "GetFilter", action = "http://tempuri.org/IServiceMainSearch/GetFilter")
    @WebResult(name = "GetFilterResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetFilter", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetFilter")
    @ResponseWrapper(localName = "GetFilterResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetFilterResponse")
    public ArrayOfReturnObject getFilter(
        @WebParam(name = "countryId", targetNamespace = "http://tempuri.org/")
        Integer countryId,
        @WebParam(name = "departureCityId", targetNamespace = "http://tempuri.org/")
        ArrayOfint departureCityId,
        @WebParam(name = "tourTypes", targetNamespace = "http://tempuri.org/")
        ArrayOfint tourTypes,
        @WebParam(name = "tours", targetNamespace = "http://tempuri.org/")
        ArrayOfint tours,
        @WebParam(name = "cities", targetNamespace = "http://tempuri.org/")
        ArrayOfint cities,
        @WebParam(name = "categories", targetNamespace = "http://tempuri.org/")
        ArrayOfint categories,
        @WebParam(name = "hotels", targetNamespace = "http://tempuri.org/")
        ArrayOfint hotels,
        @WebParam(name = "meals", targetNamespace = "http://tempuri.org/")
        ArrayOfint meals,
        @WebParam(name = "durations", targetNamespace = "http://tempuri.org/")
        ArrayOfint durations,
        @WebParam(name = "changedItem", targetNamespace = "http://tempuri.org/")
        DictionaryEnum changedItem);

    /**
     * 
     * @param cities
     * @param dateFrom
     * @param tours
     * @param countryId
     * @param changedItem
     * @param paxChild
     * @param hotels
     * @param sender
     * @param departureCityId
     * @param dateTo
     * @param durations
     * @param categories
     * @param paxAdult
     * @param tourTypes
     * @param meals
     * @return
     *     returns org.datacontract.schemas._2004._07.mouzenidis_services_objects.ArrayOfReturnObject
     */
    @WebMethod(operationName = "GetFilter2", action = "http://tempuri.org/IServiceMainSearch/GetFilter2")
    @WebResult(name = "GetFilter2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetFilter2", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetFilter2")
    @ResponseWrapper(localName = "GetFilter2Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetFilter2Response")
    public ArrayOfReturnObject getFilter2(
        @WebParam(name = "countryId", targetNamespace = "http://tempuri.org/")
        Integer countryId,
        @WebParam(name = "departureCityId", targetNamespace = "http://tempuri.org/")
        ArrayOfint departureCityId,
        @WebParam(name = "tourTypes", targetNamespace = "http://tempuri.org/")
        ArrayOfint tourTypes,
        @WebParam(name = "tours", targetNamespace = "http://tempuri.org/")
        ArrayOfint tours,
        @WebParam(name = "cities", targetNamespace = "http://tempuri.org/")
        ArrayOfint cities,
        @WebParam(name = "categories", targetNamespace = "http://tempuri.org/")
        ArrayOfint categories,
        @WebParam(name = "hotels", targetNamespace = "http://tempuri.org/")
        ArrayOfint hotels,
        @WebParam(name = "meals", targetNamespace = "http://tempuri.org/")
        ArrayOfint meals,
        @WebParam(name = "durations", targetNamespace = "http://tempuri.org/")
        ArrayOfint durations,
        @WebParam(name = "dateFrom", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar dateFrom,
        @WebParam(name = "dateTo", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar dateTo,
        @WebParam(name = "paxAdult", targetNamespace = "http://tempuri.org/")
        Integer paxAdult,
        @WebParam(name = "paxChild", targetNamespace = "http://tempuri.org/")
        Integer paxChild,
        @WebParam(name = "changedItem", targetNamespace = "http://tempuri.org/")
        DictionaryEnum changedItem,
        @WebParam(name = "sender", targetNamespace = "http://tempuri.org/")
        String sender);

    /**
     * 
     * @param cities
     * @param hotelRatingTo
     * @param dateFrom
     * @param tours
     * @param countryId
     * @param hotelRatingFrom
     * @param changedItem
     * @param paxChild
     * @param hotelGroups
     * @param hotels
     * @param sender
     * @param departureCityId
     * @param hotelFacilities
     * @param dateTo
     * @param durations
     * @param categories
     * @param paxAdult
     * @param tourTypes
     * @param meals
     * @return
     *     returns org.datacontract.schemas._2004._07.mouzenidis_services_objects.ArrayOfReturnObject
     */
    @WebMethod(operationName = "GetFilter3", action = "http://tempuri.org/IServiceMainSearch/GetFilter3")
    @WebResult(name = "GetFilter3Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetFilter3", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetFilter3")
    @ResponseWrapper(localName = "GetFilter3Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetFilter3Response")
    public ArrayOfReturnObject getFilter3(
        @WebParam(name = "countryId", targetNamespace = "http://tempuri.org/")
        Integer countryId,
        @WebParam(name = "departureCityId", targetNamespace = "http://tempuri.org/")
        ArrayOfint departureCityId,
        @WebParam(name = "tourTypes", targetNamespace = "http://tempuri.org/")
        ArrayOfint tourTypes,
        @WebParam(name = "tours", targetNamespace = "http://tempuri.org/")
        ArrayOfint tours,
        @WebParam(name = "cities", targetNamespace = "http://tempuri.org/")
        ArrayOfint cities,
        @WebParam(name = "categories", targetNamespace = "http://tempuri.org/")
        ArrayOfint categories,
        @WebParam(name = "hotelGroups", targetNamespace = "http://tempuri.org/")
        ArrayOfint hotelGroups,
        @WebParam(name = "hotelFacilities", targetNamespace = "http://tempuri.org/")
        ArrayOfint hotelFacilities,
        @WebParam(name = "hotels", targetNamespace = "http://tempuri.org/")
        ArrayOfint hotels,
        @WebParam(name = "meals", targetNamespace = "http://tempuri.org/")
        ArrayOfint meals,
        @WebParam(name = "durations", targetNamespace = "http://tempuri.org/")
        ArrayOfint durations,
        @WebParam(name = "dateFrom", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar dateFrom,
        @WebParam(name = "dateTo", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar dateTo,
        @WebParam(name = "paxAdult", targetNamespace = "http://tempuri.org/")
        Integer paxAdult,
        @WebParam(name = "paxChild", targetNamespace = "http://tempuri.org/")
        Integer paxChild,
        @WebParam(name = "hotelRatingFrom", targetNamespace = "http://tempuri.org/")
        Double hotelRatingFrom,
        @WebParam(name = "hotelRatingTo", targetNamespace = "http://tempuri.org/")
        Double hotelRatingTo,
        @WebParam(name = "changedItem", targetNamespace = "http://tempuri.org/")
        DictionaryEnum changedItem,
        @WebParam(name = "sender", targetNamespace = "http://tempuri.org/")
        String sender);

    /**
     * 
     * @param cities
     * @param hotelRatingTo
     * @param dateFrom
     * @param tours
     * @param countryId
     * @param hotelRatingFrom
     * @param changedItem
     * @param paxChild
     * @param hotelGroups
     * @param hotels
     * @param sender
     * @param departureCityId
     * @param hotelFacilities
     * @param dateTo
     * @param durations
     * @param transportKindId
     * @param categories
     * @param paxAdult
     * @param tourTypes
     * @param meals
     * @return
     *     returns org.datacontract.schemas._2004._07.mouzenidis_services_objects.ArrayOfReturnObject
     */
    @WebMethod(operationName = "GetFilter4", action = "http://tempuri.org/IServiceMainSearch/GetFilter4")
    @WebResult(name = "GetFilter4Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetFilter4", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetFilter4")
    @ResponseWrapper(localName = "GetFilter4Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetFilter4Response")
    public ArrayOfReturnObject getFilter4(
        @WebParam(name = "countryId", targetNamespace = "http://tempuri.org/")
        Integer countryId,
        @WebParam(name = "departureCityId", targetNamespace = "http://tempuri.org/")
        ArrayOfint departureCityId,
        @WebParam(name = "transportKindId", targetNamespace = "http://tempuri.org/")
        Integer transportKindId,
        @WebParam(name = "tourTypes", targetNamespace = "http://tempuri.org/")
        ArrayOfint tourTypes,
        @WebParam(name = "tours", targetNamespace = "http://tempuri.org/")
        ArrayOfint tours,
        @WebParam(name = "cities", targetNamespace = "http://tempuri.org/")
        ArrayOfint cities,
        @WebParam(name = "categories", targetNamespace = "http://tempuri.org/")
        ArrayOfint categories,
        @WebParam(name = "hotelGroups", targetNamespace = "http://tempuri.org/")
        ArrayOfint hotelGroups,
        @WebParam(name = "hotelFacilities", targetNamespace = "http://tempuri.org/")
        ArrayOfint hotelFacilities,
        @WebParam(name = "hotels", targetNamespace = "http://tempuri.org/")
        ArrayOfint hotels,
        @WebParam(name = "meals", targetNamespace = "http://tempuri.org/")
        ArrayOfint meals,
        @WebParam(name = "durations", targetNamespace = "http://tempuri.org/")
        ArrayOfint durations,
        @WebParam(name = "dateFrom", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar dateFrom,
        @WebParam(name = "dateTo", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar dateTo,
        @WebParam(name = "paxAdult", targetNamespace = "http://tempuri.org/")
        Integer paxAdult,
        @WebParam(name = "paxChild", targetNamespace = "http://tempuri.org/")
        Integer paxChild,
        @WebParam(name = "hotelRatingFrom", targetNamespace = "http://tempuri.org/")
        Double hotelRatingFrom,
        @WebParam(name = "hotelRatingTo", targetNamespace = "http://tempuri.org/")
        Double hotelRatingTo,
        @WebParam(name = "changedItem", targetNamespace = "http://tempuri.org/")
        DictionaryEnum changedItem,
        @WebParam(name = "sender", targetNamespace = "http://tempuri.org/")
        String sender);

    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.mouzenidis_services_objects.ArrayOfReturnObject
     */
    @WebMethod(operationName = "GetCountries", action = "http://tempuri.org/IServiceMainSearch/GetCountries")
    @WebResult(name = "GetCountriesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCountries", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCountries")
    @ResponseWrapper(localName = "GetCountriesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCountriesResponse")
    public ArrayOfReturnObject getCountries();

    /**
     * 
     * @param countryID
     * @return
     *     returns org.datacontract.schemas._2004._07.mouzenidis_services_objects.ArrayOfReturnObject
     */
    @WebMethod(operationName = "GetCityDeparture", action = "http://tempuri.org/IServiceMainSearch/GetCityDeparture")
    @WebResult(name = "GetCityDepartureResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCityDeparture", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCityDeparture")
    @ResponseWrapper(localName = "GetCityDepartureResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCityDepartureResponse")
    public ArrayOfReturnObject getCityDeparture(
        @WebParam(name = "countryID", targetNamespace = "http://tempuri.org/")
        Integer countryID);

    /**
     * 
     * @param countryID
     * @param typeTourID
     * @return
     *     returns org.datacontract.schemas._2004._07.mouzenidis_services_objects.ArrayOfReturnObject
     */
    @WebMethod(operationName = "GetCityDepartureByTypeTour", action = "http://tempuri.org/IServiceMainSearch/GetCityDepartureByTypeTour")
    @WebResult(name = "GetCityDepartureByTypeTourResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCityDepartureByTypeTour", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCityDepartureByTypeTour")
    @ResponseWrapper(localName = "GetCityDepartureByTypeTourResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCityDepartureByTypeTourResponse")
    public ArrayOfReturnObject getCityDepartureByTypeTour(
        @WebParam(name = "countryID", targetNamespace = "http://tempuri.org/")
        Integer countryID,
        @WebParam(name = "typeTourID", targetNamespace = "http://tempuri.org/")
        Integer typeTourID);

    /**
     * 
     * @param country
     * @param cityDepartures
     * @param dictionaries
     * @return
     *     returns org.datacontract.schemas._2004._07.mouzenidis_services_objects.ArrayOfReturnObject
     */
    @WebMethod(operationName = "GetDictionary", action = "http://tempuri.org/IServiceMainSearch/GetDictionary")
    @WebResult(name = "GetDictionaryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDictionary", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDictionary")
    @ResponseWrapper(localName = "GetDictionaryResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDictionaryResponse")
    public ArrayOfReturnObject getDictionary(
        @WebParam(name = "country", targetNamespace = "http://tempuri.org/")
        Integer country,
        @WebParam(name = "cityDepartures", targetNamespace = "http://tempuri.org/")
        ArrayOfint cityDepartures,
        @WebParam(name = "dictionaries", targetNamespace = "http://tempuri.org/")
        ArrayOfDictionaryEnum dictionaries);

    /**
     * 
     * @param hash
     * @return
     *     returns org.datacontract.schemas._2004._07.mouzenidis_services.ArrayOfStatItem
     */
    @WebMethod(operationName = "GetStat", action = "http://tempuri.org/IServiceMainSearch/GetStat")
    @WebResult(name = "GetStatResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStat", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStat")
    @ResponseWrapper(localName = "GetStatResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStatResponse")
    public ArrayOfStatItem getStat(
        @WebParam(name = "hash", targetNamespace = "http://tempuri.org/")
        Integer hash);

    /**
     * 
     * @param hash
     * @return
     *     returns org.datacontract.schemas._2004._07.mouzenidis_services_objects.ArrayOfRealCourse
     */
    @WebMethod(operationName = "GetCourse", action = "http://tempuri.org/IServiceMainSearch/GetCourse")
    @WebResult(name = "GetCourseResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCourse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCourse")
    @ResponseWrapper(localName = "GetCourseResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCourseResponse")
    public ArrayOfRealCourse getCourse(
        @WebParam(name = "hash", targetNamespace = "http://tempuri.org/")
        Integer hash);

    /**
     * 
     * @param password
     * @param login
     * @param reservationCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetReservationState", action = "http://tempuri.org/IServiceMainSearch/GetReservationState")
    @WebResult(name = "GetReservationStateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetReservationState", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetReservationState")
    @ResponseWrapper(localName = "GetReservationStateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetReservationStateResponse")
    public String getReservationState(
        @WebParam(name = "reservationCode", targetNamespace = "http://tempuri.org/")
        String reservationCode,
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

}
