
package org.diacomp.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PublicationWebServiceSoap", targetNamespace = "http://www.diacomp.org/webservices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PublicationWebServiceSoap {


    /**
     * This method will return an Publication for the specified matching PublicationID 
     * 
     * @param publicationID
     * @return
     *     returns org.diacomp.webservices.Publication
     */
    @WebMethod(operationName = "GetPublication", action = "http://www.diacomp.org/webservices/GetPublication")
    @WebResult(name = "GetPublicationResult", targetNamespace = "http://www.diacomp.org/webservices/")
    @RequestWrapper(localName = "GetPublication", targetNamespace = "http://www.diacomp.org/webservices/", className = "org.diacomp.webservices.GetPublication")
    @ResponseWrapper(localName = "GetPublicationResponse", targetNamespace = "http://www.diacomp.org/webservices/", className = "org.diacomp.webservices.GetPublicationResponse")
    public Publication getPublication(
        @WebParam(name = "PublicationID", targetNamespace = "http://www.diacomp.org/webservices/")
        int publicationID);

    /**
     * This method will return a list of Publications
     * 
     * @return
     *     returns org.diacomp.webservices.ArrayOfPublication
     */
    @WebMethod(operationName = "GetPublications", action = "http://www.diacomp.org/webservices/GetPublications")
    @WebResult(name = "GetPublicationsResult", targetNamespace = "http://www.diacomp.org/webservices/")
    @RequestWrapper(localName = "GetPublications", targetNamespace = "http://www.diacomp.org/webservices/", className = "org.diacomp.webservices.GetPublications")
    @ResponseWrapper(localName = "GetPublicationsResponse", targetNamespace = "http://www.diacomp.org/webservices/", className = "org.diacomp.webservices.GetPublicationsResponse")
    public ArrayOfPublication getPublications();

    /**
     * This method will return a list of Publications that meet the optional Publication Search criteria
     * 
     * @param publicationSearch
     * @return
     *     returns org.diacomp.webservices.ArrayOfPublication
     */
    @WebMethod(operationName = "GetPublicationsBySearch", action = "http://www.diacomp.org/webservices/GetPublicationsBySearch")
    @WebResult(name = "GetPublicationsBySearchResult", targetNamespace = "http://www.diacomp.org/webservices/")
    @RequestWrapper(localName = "GetPublicationsBySearch", targetNamespace = "http://www.diacomp.org/webservices/", className = "org.diacomp.webservices.GetPublicationsBySearch")
    @ResponseWrapper(localName = "GetPublicationsBySearchResponse", targetNamespace = "http://www.diacomp.org/webservices/", className = "org.diacomp.webservices.GetPublicationsBySearchResponse")
    public ArrayOfPublication getPublicationsBySearch(
        @WebParam(name = "publicationSearch", targetNamespace = "http://www.diacomp.org/webservices/")
        PublicationSearch publicationSearch);

    /**
     * This method will return the list of associated Experiments for a specified Publication
     * 
     * @param publicationID
     * @return
     *     returns org.diacomp.webservices.ArrayOfExperiment
     */
    @WebMethod(operationName = "GetPublicationExperiments", action = "http://www.diacomp.org/webservices/GetPublicationExperiments")
    @WebResult(name = "GetPublicationExperimentsResult", targetNamespace = "http://www.diacomp.org/webservices/")
    @RequestWrapper(localName = "GetPublicationExperiments", targetNamespace = "http://www.diacomp.org/webservices/", className = "org.diacomp.webservices.GetPublicationExperiments")
    @ResponseWrapper(localName = "GetPublicationExperimentsResponse", targetNamespace = "http://www.diacomp.org/webservices/", className = "org.diacomp.webservices.GetPublicationExperimentsResponse")
    public ArrayOfExperiment getPublicationExperiments(
        @WebParam(name = "PublicationID", targetNamespace = "http://www.diacomp.org/webservices/")
        int publicationID);

    /**
     * This method will return the list of associated strains for a specified Publication
     * 
     * @param publicationID
     * @return
     *     returns org.diacomp.webservices.ArrayOfStrain
     */
    @WebMethod(operationName = "GetPublicationStrains", action = "http://www.diacomp.org/webservices/GetPublicationStrains")
    @WebResult(name = "GetPublicationStrainsResult", targetNamespace = "http://www.diacomp.org/webservices/")
    @RequestWrapper(localName = "GetPublicationStrains", targetNamespace = "http://www.diacomp.org/webservices/", className = "org.diacomp.webservices.GetPublicationStrains")
    @ResponseWrapper(localName = "GetPublicationStrainsResponse", targetNamespace = "http://www.diacomp.org/webservices/", className = "org.diacomp.webservices.GetPublicationStrainsResponse")
    public ArrayOfStrain getPublicationStrains(
        @WebParam(name = "PublicationID", targetNamespace = "http://www.diacomp.org/webservices/")
        int publicationID);

    /**
     * This method will return the list of associated model types for a specified Publication
     * 
     * @param publicationID
     * @return
     *     returns org.diacomp.webservices.ArrayOfString
     */
    @WebMethod(operationName = "GetPublicationModelTypes", action = "http://www.diacomp.org/webservices/GetPublicationModelTypes")
    @WebResult(name = "GetPublicationModelTypesResult", targetNamespace = "http://www.diacomp.org/webservices/")
    @RequestWrapper(localName = "GetPublicationModelTypes", targetNamespace = "http://www.diacomp.org/webservices/", className = "org.diacomp.webservices.GetPublicationModelTypes")
    @ResponseWrapper(localName = "GetPublicationModelTypesResponse", targetNamespace = "http://www.diacomp.org/webservices/", className = "org.diacomp.webservices.GetPublicationModelTypesResponse")
    public ArrayOfString getPublicationModelTypes(
        @WebParam(name = "PublicationID", targetNamespace = "http://www.diacomp.org/webservices/")
        int publicationID);

}
