
package com.epostcode.ws.uk;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This webservice contains postcode, address and geographical data lookup functions. Before using the ePostcode WebService please register at http://www.ePostcode.com and follow the instructions for signing up with a new account.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PostcodeServices09", targetNamespace = "http://ws.epostcode.com/uk/", wsdlLocation = "META-INF/wsdl/PostcodeServices09.wsdl")
public class PostcodeServices09
    extends Service
{

    private final static URL POSTCODESERVICES09_WSDL_LOCATION;
    private final static WebServiceException POSTCODESERVICES09_EXCEPTION;
    private final static QName POSTCODESERVICES09_QNAME = new QName("http://ws.epostcode.com/uk/", "PostcodeServices09");

    static {
        POSTCODESERVICES09_WSDL_LOCATION = com.epostcode.ws.uk.PostcodeServices09 .class.getClassLoader().getResource("META-INF/wsdl/PostcodeServices09.wsdl");
        WebServiceException e = null;
        if (POSTCODESERVICES09_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/PostcodeServices09.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        POSTCODESERVICES09_EXCEPTION = e;
    }

    public PostcodeServices09() {
        super(__getWsdlLocation(), POSTCODESERVICES09_QNAME);
    }

    public PostcodeServices09(WebServiceFeature... features) {
        super(__getWsdlLocation(), POSTCODESERVICES09_QNAME, features);
    }

    public PostcodeServices09(URL wsdlLocation) {
        super(wsdlLocation, POSTCODESERVICES09_QNAME);
    }

    public PostcodeServices09(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, POSTCODESERVICES09_QNAME, features);
    }

    public PostcodeServices09(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PostcodeServices09(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PostcodeServices09Soap
     */
    @WebEndpoint(name = "PostcodeServices09Soap")
    public PostcodeServices09Soap getPostcodeServices09Soap() {
        return super.getPort(new QName("http://ws.epostcode.com/uk/", "PostcodeServices09Soap"), PostcodeServices09Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PostcodeServices09Soap
     */
    @WebEndpoint(name = "PostcodeServices09Soap")
    public PostcodeServices09Soap getPostcodeServices09Soap(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.epostcode.com/uk/", "PostcodeServices09Soap"), PostcodeServices09Soap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (POSTCODESERVICES09_EXCEPTION!= null) {
            throw POSTCODESERVICES09_EXCEPTION;
        }
        return POSTCODESERVICES09_WSDL_LOCATION;
    }

}
