
package org.tempuri;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TravelService", targetNamespace = "http://tempuri.org/", wsdlLocation = "META-INF/wsdl/TravelService.wsdl")
public class TravelService
    extends Service
{

    private final static URL TRAVELSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRAVELSERVICE_EXCEPTION;
    private final static QName TRAVELSERVICE_QNAME = new QName("http://tempuri.org/", "TravelService");

    static {
        TRAVELSERVICE_WSDL_LOCATION = org.tempuri.TravelService.class.getClassLoader().getResource("META-INF/wsdl/TravelService.wsdl");
        WebServiceException e = null;
        if (TRAVELSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/TravelService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        TRAVELSERVICE_EXCEPTION = e;
    }

    public TravelService() {
        super(__getWsdlLocation(), TRAVELSERVICE_QNAME);
    }

    public TravelService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRAVELSERVICE_QNAME, features);
    }

    public TravelService(URL wsdlLocation) {
        super(wsdlLocation, TRAVELSERVICE_QNAME);
    }

    public TravelService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRAVELSERVICE_QNAME, features);
    }

    public TravelService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TravelService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ITravelService
     */
    @WebEndpoint(name = "travel")
    public ITravelService getTravel() {
        return super.getPort(new QName("http://tempuri.org/", "travel"), ITravelService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ITravelService
     */
    @WebEndpoint(name = "travel")
    public ITravelService getTravel(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "travel"), ITravelService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRAVELSERVICE_EXCEPTION!= null) {
            throw TRAVELSERVICE_EXCEPTION;
        }
        return TRAVELSERVICE_WSDL_LOCATION;
    }

}
