
package defaultnamespace;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "jmol", targetNamespace = "http://DefaultNamespace", wsdlLocation = "META-INF/wsdl/jmol.wsdl")
public class Jmol_Service
    extends Service
{

    private final static URL JMOL_WSDL_LOCATION;
    private final static WebServiceException JMOL_EXCEPTION;
    private final static QName JMOL_QNAME = new QName("http://DefaultNamespace", "jmol");

    static {
        JMOL_WSDL_LOCATION = defaultnamespace.Jmol_Service.class.getClassLoader().getResource("META-INF/wsdl/jmol.wsdl");
        WebServiceException e = null;
        if (JMOL_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/jmol.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        JMOL_EXCEPTION = e;
    }

    public Jmol_Service() {
        super(__getWsdlLocation(), JMOL_QNAME);
    }

    public Jmol_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), JMOL_QNAME, features);
    }

    public Jmol_Service(URL wsdlLocation) {
        super(wsdlLocation, JMOL_QNAME);
    }

    public Jmol_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JMOL_QNAME, features);
    }

    public Jmol_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Jmol_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Jmol
     */
    @WebEndpoint(name = "jmolHttpPort")
    public Jmol getJmolHttpPort() {
        return super.getPort(new QName("http://DefaultNamespace", "jmolHttpPort"), Jmol.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Jmol
     */
    @WebEndpoint(name = "jmolHttpPort")
    public Jmol getJmolHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://DefaultNamespace", "jmolHttpPort"), Jmol.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JMOL_EXCEPTION!= null) {
            throw JMOL_EXCEPTION;
        }
        return JMOL_WSDL_LOCATION;
    }

}
