
package com.conducivetech.cache.flighthistory.api_internal.v2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "flightsNearService", targetNamespace = "http://v2.api_internal.flighthistory.cache.conducivetech.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FlightsNearService {


    /**
     * 
     * @param extendedOptions
     * @param sourceType
     * @param appId
     * @param topLat
     * @param maxFlights
     * @param leftLon
     * @param rightLon
     * @param appKey
     * @param bottomLat
     * @return
     *     returns com.conducivetech.cache.flighthistory.api_internal.v2.ResponseFlightsNearBox
     * @throws APIException_Exception
     */
    @WebMethod(operationName = "flightsNear_box")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "flightsNear_box", targetNamespace = "http://v2.api_internal.flighthistory.cache.conducivetech.com/", className = "com.conducivetech.cache.flighthistory.api_internal.v2.FlightsNearBox")
    @ResponseWrapper(localName = "flightsNear_boxResponse", targetNamespace = "http://v2.api_internal.flighthistory.cache.conducivetech.com/", className = "com.conducivetech.cache.flighthistory.api_internal.v2.FlightsNearBoxResponse")
    @Action(input = "http://v2.api_internal.flighthistory.cache.conducivetech.com/flightsNearService/flightsNear_boxRequest", output = "http://v2.api_internal.flighthistory.cache.conducivetech.com/flightsNearService/flightsNear_boxResponse", fault = {
        @FaultAction(className = APIException_Exception.class, value = "http://v2.api_internal.flighthistory.cache.conducivetech.com/flightsNearService/flightsNear_box/Fault/APIException")
    })
    public ResponseFlightsNearBox flightsNearBox(
        @WebParam(name = "appId", targetNamespace = "")
        String appId,
        @WebParam(name = "appKey", targetNamespace = "")
        String appKey,
        @WebParam(name = "topLat", targetNamespace = "")
        double topLat,
        @WebParam(name = "leftLon", targetNamespace = "")
        double leftLon,
        @WebParam(name = "bottomLat", targetNamespace = "")
        double bottomLat,
        @WebParam(name = "rightLon", targetNamespace = "")
        double rightLon,
        @WebParam(name = "maxFlights", targetNamespace = "")
        Integer maxFlights,
        @WebParam(name = "sourceType", targetNamespace = "")
        String sourceType,
        @WebParam(name = "extendedOptions", targetNamespace = "")
        String extendedOptions)
        throws APIException_Exception
    ;

    /**
     * 
     * @param extendedOptions
     * @param sourceType
     * @param appId
     * @param maxFlights
     * @param appKey
     * @param lon
     * @param lat
     * @param miles
     * @return
     *     returns com.conducivetech.cache.flighthistory.api_internal.v2.ResponseFlightsNearRadius
     * @throws APIException_Exception
     */
    @WebMethod(operationName = "flightsNear_radius")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "flightsNear_radius", targetNamespace = "http://v2.api_internal.flighthistory.cache.conducivetech.com/", className = "com.conducivetech.cache.flighthistory.api_internal.v2.FlightsNearRadius")
    @ResponseWrapper(localName = "flightsNear_radiusResponse", targetNamespace = "http://v2.api_internal.flighthistory.cache.conducivetech.com/", className = "com.conducivetech.cache.flighthistory.api_internal.v2.FlightsNearRadiusResponse")
    @Action(input = "http://v2.api_internal.flighthistory.cache.conducivetech.com/flightsNearService/flightsNear_radiusRequest", output = "http://v2.api_internal.flighthistory.cache.conducivetech.com/flightsNearService/flightsNear_radiusResponse", fault = {
        @FaultAction(className = APIException_Exception.class, value = "http://v2.api_internal.flighthistory.cache.conducivetech.com/flightsNearService/flightsNear_radius/Fault/APIException")
    })
    public ResponseFlightsNearRadius flightsNearRadius(
        @WebParam(name = "appId", targetNamespace = "")
        String appId,
        @WebParam(name = "appKey", targetNamespace = "")
        String appKey,
        @WebParam(name = "lat", targetNamespace = "")
        double lat,
        @WebParam(name = "lon", targetNamespace = "")
        double lon,
        @WebParam(name = "miles", targetNamespace = "")
        int miles,
        @WebParam(name = "maxFlights", targetNamespace = "")
        Integer maxFlights,
        @WebParam(name = "sourceType", targetNamespace = "")
        String sourceType,
        @WebParam(name = "extendedOptions", targetNamespace = "")
        String extendedOptions)
        throws APIException_Exception
    ;

}
