
package com.xignite.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "XigniteInsiderSoap", targetNamespace = "http://www.xignite.com/services/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface XigniteInsiderSoap {


    /**
     * Retrieve an ownership file (Forms 3, 4 or 5) by Url.
     * 
     * @param htmlFileUrl
     * @return
     *     returns com.xignite.services.OwnershipDocument
     */
    @WebMethod(operationName = "GetOwnershipForm", action = "http://www.xignite.com/services/GetOwnershipForm")
    @WebResult(name = "GetOwnershipFormResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetOwnershipForm", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetOwnershipForm")
    @ResponseWrapper(localName = "GetOwnershipFormResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetOwnershipFormResponse")
    public OwnershipDocument getOwnershipForm(
        @WebParam(name = "HtmlFileUrl", targetNamespace = "http://www.xignite.com/services/")
        String htmlFileUrl);

    /**
     * Get insiders by cik, name or address.
     * 
     * @param insiderName
     * @param insiderCIK
     * @param insiderAddress
     * @return
     *     returns com.xignite.services.ArrayOfInsider
     */
    @WebMethod(operationName = "GetInsiders", action = "http://www.xignite.com/services/GetInsiders")
    @WebResult(name = "GetInsidersResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetInsiders", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetInsiders")
    @ResponseWrapper(localName = "GetInsidersResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetInsidersResponse")
    public ArrayOfInsider getInsiders(
        @WebParam(name = "InsiderCIK", targetNamespace = "http://www.xignite.com/services/")
        String insiderCIK,
        @WebParam(name = "InsiderName", targetNamespace = "http://www.xignite.com/services/")
        String insiderName,
        @WebParam(name = "InsiderAddress", targetNamespace = "http://www.xignite.com/services/")
        String insiderAddress);

    /**
     * Search an insider by name and address.
     * 
     * @param insiderName
     * @param insiderCIK
     * @param insiderAddress
     * @return
     *     returns com.xignite.services.ArrayOfRole
     */
    @WebMethod(operationName = "GetRoles", action = "http://www.xignite.com/services/GetRoles")
    @WebResult(name = "GetRolesResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetRoles", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRoles")
    @ResponseWrapper(localName = "GetRolesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRolesResponse")
    public ArrayOfRole getRoles(
        @WebParam(name = "InsiderCIK", targetNamespace = "http://www.xignite.com/services/")
        String insiderCIK,
        @WebParam(name = "InsiderName", targetNamespace = "http://www.xignite.com/services/")
        String insiderName,
        @WebParam(name = "InsiderAddress", targetNamespace = "http://www.xignite.com/services/")
        String insiderAddress);

    /**
     * Search an insider by name and address and by the name or identifier of a firm.
     * 
     * @param issuerIdentifier
     * @param issuerName
     * @param insiderName
     * @param insiderCIK
     * @param issuerIdentifierType
     * @param insiderAddress
     * @return
     *     returns com.xignite.services.ArrayOfRole
     */
    @WebMethod(operationName = "GetRole", action = "http://www.xignite.com/services/GetRole")
    @WebResult(name = "GetRoleResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetRole", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRole")
    @ResponseWrapper(localName = "GetRoleResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRoleResponse")
    public ArrayOfRole getRole(
        @WebParam(name = "InsiderCIK", targetNamespace = "http://www.xignite.com/services/")
        String insiderCIK,
        @WebParam(name = "InsiderName", targetNamespace = "http://www.xignite.com/services/")
        String insiderName,
        @WebParam(name = "InsiderAddress", targetNamespace = "http://www.xignite.com/services/")
        String insiderAddress,
        @WebParam(name = "IssuerIdentifier", targetNamespace = "http://www.xignite.com/services/")
        String issuerIdentifier,
        @WebParam(name = "IssuerIdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes issuerIdentifierType,
        @WebParam(name = "IssuerName", targetNamespace = "http://www.xignite.com/services/")
        String issuerName);

    /**
     * Returns the current roster of insider for a firm.
     * 
     * @param issuerIdentifier
     * @param issuerIdentifierType
     * @return
     *     returns com.xignite.services.Roster
     */
    @WebMethod(operationName = "GetRoster", action = "http://www.xignite.com/services/GetRoster")
    @WebResult(name = "GetRosterResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetRoster", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRoster")
    @ResponseWrapper(localName = "GetRosterResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRosterResponse")
    public Roster getRoster(
        @WebParam(name = "IssuerIdentifier", targetNamespace = "http://www.xignite.com/services/")
        String issuerIdentifier,
        @WebParam(name = "IssuerIdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes issuerIdentifierType);

    /**
     * Returns the directors for a firm.
     * 
     * @param issuerIdentifier
     * @param issuerIdentifierType
     * @return
     *     returns com.xignite.services.Roster
     */
    @WebMethod(operationName = "GetDirectors", action = "http://www.xignite.com/services/GetDirectors")
    @WebResult(name = "GetDirectorsResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetDirectors", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetDirectors")
    @ResponseWrapper(localName = "GetDirectorsResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetDirectorsResponse")
    public Roster getDirectors(
        @WebParam(name = "IssuerIdentifier", targetNamespace = "http://www.xignite.com/services/")
        String issuerIdentifier,
        @WebParam(name = "IssuerIdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes issuerIdentifierType);

    /**
     * Returns the officers for a firm.
     * 
     * @param issuerIdentifier
     * @param issuerIdentifierType
     * @return
     *     returns com.xignite.services.Roster
     */
    @WebMethod(operationName = "GetOfficers", action = "http://www.xignite.com/services/GetOfficers")
    @WebResult(name = "GetOfficersResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetOfficers", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetOfficers")
    @ResponseWrapper(localName = "GetOfficersResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetOfficersResponse")
    public Roster getOfficers(
        @WebParam(name = "IssuerIdentifier", targetNamespace = "http://www.xignite.com/services/")
        String issuerIdentifier,
        @WebParam(name = "IssuerIdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes issuerIdentifierType);

    /**
     * Returns the CEO for a firm.
     * 
     * @param issuerIdentifier
     * @param issuerIdentifierType
     * @return
     *     returns com.xignite.services.Roster
     */
    @WebMethod(operationName = "GetCEO", action = "http://www.xignite.com/services/GetCEO")
    @WebResult(name = "GetCEOResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetCEO", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCEO")
    @ResponseWrapper(localName = "GetCEOResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCEOResponse")
    public Roster getCEO(
        @WebParam(name = "IssuerIdentifier", targetNamespace = "http://www.xignite.com/services/")
        String issuerIdentifier,
        @WebParam(name = "IssuerIdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes issuerIdentifierType);

    /**
     * Returns the current ownerships for a firm.
     * 
     * @param issuerIdentifier
     * @param issuerIdentifierType
     * @return
     *     returns com.xignite.services.IssuerOwnerships
     */
    @WebMethod(operationName = "GetIssuerOwnerships", action = "http://www.xignite.com/services/GetIssuerOwnerships")
    @WebResult(name = "GetIssuerOwnershipsResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetIssuerOwnerships", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetIssuerOwnerships")
    @ResponseWrapper(localName = "GetIssuerOwnershipsResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetIssuerOwnershipsResponse")
    public IssuerOwnerships getIssuerOwnerships(
        @WebParam(name = "IssuerIdentifier", targetNamespace = "http://www.xignite.com/services/")
        String issuerIdentifier,
        @WebParam(name = "IssuerIdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes issuerIdentifierType);

    /**
     * Returns current ownership level for an insider and a firm.
     * 
     * @param issuerIdentifier
     * @param insiderName
     * @param insiderCIK
     * @param issuerIdentifierType
     * @param insiderAddress
     * @return
     *     returns com.xignite.services.IssuerOwnerships
     */
    @WebMethod(operationName = "GetInsiderOwnership", action = "http://www.xignite.com/services/GetInsiderOwnership")
    @WebResult(name = "GetInsiderOwnershipResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetInsiderOwnership", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetInsiderOwnership")
    @ResponseWrapper(localName = "GetInsiderOwnershipResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetInsiderOwnershipResponse")
    public IssuerOwnerships getInsiderOwnership(
        @WebParam(name = "InsiderCIK", targetNamespace = "http://www.xignite.com/services/")
        String insiderCIK,
        @WebParam(name = "InsiderName", targetNamespace = "http://www.xignite.com/services/")
        String insiderName,
        @WebParam(name = "InsiderAddress", targetNamespace = "http://www.xignite.com/services/")
        String insiderAddress,
        @WebParam(name = "IssuerIdentifier", targetNamespace = "http://www.xignite.com/services/")
        String issuerIdentifier,
        @WebParam(name = "IssuerIdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes issuerIdentifierType);

    /**
     * Returns current ownership level for an insider across all firms.
     * 
     * @param insiderName
     * @param insiderCIK
     * @param insiderAddress
     * @return
     *     returns com.xignite.services.InsiderOwnerships
     */
    @WebMethod(operationName = "GetInsiderOwnerships", action = "http://www.xignite.com/services/GetInsiderOwnerships")
    @WebResult(name = "GetInsiderOwnershipsResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetInsiderOwnerships", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetInsiderOwnerships")
    @ResponseWrapper(localName = "GetInsiderOwnershipsResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetInsiderOwnershipsResponse")
    public InsiderOwnerships getInsiderOwnerships(
        @WebParam(name = "InsiderCIK", targetNamespace = "http://www.xignite.com/services/")
        String insiderCIK,
        @WebParam(name = "InsiderName", targetNamespace = "http://www.xignite.com/services/")
        String insiderName,
        @WebParam(name = "InsiderAddress", targetNamespace = "http://www.xignite.com/services/")
        String insiderAddress);

    /**
     * Get transactions for an insider across all firms.
     * 
     * @param fromDate
     * @param ownershipType
     * @param securityType
     * @param toDate
     * @param insiderName
     * @param insiderCIK
     * @param insiderAddress
     * @param transactionCode
     * @return
     *     returns com.xignite.services.InsiderTransactions
     */
    @WebMethod(operationName = "GetAllInsiderTransactions", action = "http://www.xignite.com/services/GetAllInsiderTransactions")
    @WebResult(name = "GetAllInsiderTransactionsResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetAllInsiderTransactions", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetAllInsiderTransactions")
    @ResponseWrapper(localName = "GetAllInsiderTransactionsResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetAllInsiderTransactionsResponse")
    public InsiderTransactions getAllInsiderTransactions(
        @WebParam(name = "InsiderCIK", targetNamespace = "http://www.xignite.com/services/")
        String insiderCIK,
        @WebParam(name = "InsiderName", targetNamespace = "http://www.xignite.com/services/")
        String insiderName,
        @WebParam(name = "InsiderAddress", targetNamespace = "http://www.xignite.com/services/")
        String insiderAddress,
        @WebParam(name = "FromDate", targetNamespace = "http://www.xignite.com/services/")
        String fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://www.xignite.com/services/")
        String toDate,
        @WebParam(name = "TransactionCode", targetNamespace = "http://www.xignite.com/services/")
        TransactionCodes transactionCode,
        @WebParam(name = "SecurityType", targetNamespace = "http://www.xignite.com/services/")
        SecurityTypes securityType,
        @WebParam(name = "OwnershipType", targetNamespace = "http://www.xignite.com/services/")
        OwnershipTypes ownershipType);

    /**
     * Get transactions for an insider within one firm.
     * 
     * @param fromDate
     * @param ownershipType
     * @param issuerIdentifier
     * @param securityType
     * @param toDate
     * @param insiderName
     * @param insiderCIK
     * @param issuerIdentifierType
     * @param insiderAddress
     * @param transactionCode
     * @return
     *     returns com.xignite.services.InsiderTransactions
     */
    @WebMethod(operationName = "GetInsiderTransactions", action = "http://www.xignite.com/services/GetInsiderTransactions")
    @WebResult(name = "GetInsiderTransactionsResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetInsiderTransactions", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetInsiderTransactions")
    @ResponseWrapper(localName = "GetInsiderTransactionsResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetInsiderTransactionsResponse")
    public InsiderTransactions getInsiderTransactions(
        @WebParam(name = "InsiderCIK", targetNamespace = "http://www.xignite.com/services/")
        String insiderCIK,
        @WebParam(name = "InsiderName", targetNamespace = "http://www.xignite.com/services/")
        String insiderName,
        @WebParam(name = "InsiderAddress", targetNamespace = "http://www.xignite.com/services/")
        String insiderAddress,
        @WebParam(name = "IssuerIdentifier", targetNamespace = "http://www.xignite.com/services/")
        String issuerIdentifier,
        @WebParam(name = "IssuerIdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes issuerIdentifierType,
        @WebParam(name = "FromDate", targetNamespace = "http://www.xignite.com/services/")
        String fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://www.xignite.com/services/")
        String toDate,
        @WebParam(name = "TransactionCode", targetNamespace = "http://www.xignite.com/services/")
        TransactionCodes transactionCode,
        @WebParam(name = "SecurityType", targetNamespace = "http://www.xignite.com/services/")
        SecurityTypes securityType,
        @WebParam(name = "OwnershipType", targetNamespace = "http://www.xignite.com/services/")
        OwnershipTypes ownershipType);

    /**
     * Get holdings for an insider within one firm.
     * 
     * @param fromDate
     * @param ownershipType
     * @param issuerIdentifier
     * @param securityType
     * @param toDate
     * @param insiderName
     * @param insiderCIK
     * @param issuerIdentifierType
     * @param insiderAddress
     * @param transactionCode
     * @return
     *     returns com.xignite.services.InsiderHoldings
     */
    @WebMethod(operationName = "GetInsiderHoldings", action = "http://www.xignite.com/services/GetInsiderHoldings")
    @WebResult(name = "GetInsiderHoldingsResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetInsiderHoldings", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetInsiderHoldings")
    @ResponseWrapper(localName = "GetInsiderHoldingsResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetInsiderHoldingsResponse")
    public InsiderHoldings getInsiderHoldings(
        @WebParam(name = "InsiderCIK", targetNamespace = "http://www.xignite.com/services/")
        String insiderCIK,
        @WebParam(name = "InsiderName", targetNamespace = "http://www.xignite.com/services/")
        String insiderName,
        @WebParam(name = "InsiderAddress", targetNamespace = "http://www.xignite.com/services/")
        String insiderAddress,
        @WebParam(name = "IssuerIdentifier", targetNamespace = "http://www.xignite.com/services/")
        String issuerIdentifier,
        @WebParam(name = "IssuerIdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes issuerIdentifierType,
        @WebParam(name = "FromDate", targetNamespace = "http://www.xignite.com/services/")
        String fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://www.xignite.com/services/")
        String toDate,
        @WebParam(name = "TransactionCode", targetNamespace = "http://www.xignite.com/services/")
        TransactionCodes transactionCode,
        @WebParam(name = "SecurityType", targetNamespace = "http://www.xignite.com/services/")
        SecurityTypes securityType,
        @WebParam(name = "OwnershipType", targetNamespace = "http://www.xignite.com/services/")
        OwnershipTypes ownershipType);

    /**
     * Get transactions for an insider within one firm.
     * 
     * @param fromDate
     * @param ownershipType
     * @param issuerIdentifier
     * @param securityType
     * @param toDate
     * @param insiderName
     * @param insiderCIK
     * @param issuerIdentifierType
     * @param insiderAddress
     * @param transactionCode
     * @return
     *     returns com.xignite.services.InsiderSECTransactions
     */
    @WebMethod(operationName = "GetInsiderSECTransactions", action = "http://www.xignite.com/services/GetInsiderSECTransactions")
    @WebResult(name = "GetInsiderSECTransactionsResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetInsiderSECTransactions", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetInsiderSECTransactions")
    @ResponseWrapper(localName = "GetInsiderSECTransactionsResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetInsiderSECTransactionsResponse")
    public InsiderSECTransactions getInsiderSECTransactions(
        @WebParam(name = "InsiderCIK", targetNamespace = "http://www.xignite.com/services/")
        String insiderCIK,
        @WebParam(name = "InsiderName", targetNamespace = "http://www.xignite.com/services/")
        String insiderName,
        @WebParam(name = "InsiderAddress", targetNamespace = "http://www.xignite.com/services/")
        String insiderAddress,
        @WebParam(name = "IssuerIdentifier", targetNamespace = "http://www.xignite.com/services/")
        String issuerIdentifier,
        @WebParam(name = "IssuerIdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes issuerIdentifierType,
        @WebParam(name = "FromDate", targetNamespace = "http://www.xignite.com/services/")
        String fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://www.xignite.com/services/")
        String toDate,
        @WebParam(name = "TransactionCode", targetNamespace = "http://www.xignite.com/services/")
        TransactionCodes transactionCode,
        @WebParam(name = "SecurityType", targetNamespace = "http://www.xignite.com/services/")
        SecurityTypes securityType,
        @WebParam(name = "OwnershipType", targetNamespace = "http://www.xignite.com/services/")
        OwnershipTypes ownershipType);

    /**
     * Get transactions for an insider within one firm.
     * 
     * @param fromDate
     * @param ownershipType
     * @param issuerIdentifier
     * @param securityType
     * @param toDate
     * @param insiderName
     * @param insiderCIK
     * @param issuerIdentifierType
     * @param insiderAddress
     * @param transactionCode
     * @return
     *     returns com.xignite.services.InsiderTransactionSummary
     */
    @WebMethod(operationName = "GetInsiderTransactionSummary", action = "http://www.xignite.com/services/GetInsiderTransactionSummary")
    @WebResult(name = "GetInsiderTransactionSummaryResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetInsiderTransactionSummary", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetInsiderTransactionSummary")
    @ResponseWrapper(localName = "GetInsiderTransactionSummaryResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetInsiderTransactionSummaryResponse")
    public InsiderTransactionSummary getInsiderTransactionSummary(
        @WebParam(name = "InsiderCIK", targetNamespace = "http://www.xignite.com/services/")
        String insiderCIK,
        @WebParam(name = "InsiderName", targetNamespace = "http://www.xignite.com/services/")
        String insiderName,
        @WebParam(name = "InsiderAddress", targetNamespace = "http://www.xignite.com/services/")
        String insiderAddress,
        @WebParam(name = "IssuerIdentifier", targetNamespace = "http://www.xignite.com/services/")
        String issuerIdentifier,
        @WebParam(name = "IssuerIdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes issuerIdentifierType,
        @WebParam(name = "FromDate", targetNamespace = "http://www.xignite.com/services/")
        String fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://www.xignite.com/services/")
        String toDate,
        @WebParam(name = "TransactionCode", targetNamespace = "http://www.xignite.com/services/")
        TransactionCodes transactionCode,
        @WebParam(name = "SecurityType", targetNamespace = "http://www.xignite.com/services/")
        SecurityTypes securityType,
        @WebParam(name = "OwnershipType", targetNamespace = "http://www.xignite.com/services/")
        OwnershipTypes ownershipType);

    /**
     * Get transactions for an insider within one firm.
     * 
     * @param fromDate
     * @param ownershipType
     * @param issuerIdentifier
     * @param securityType
     * @param toDate
     * @param issuerIdentifierType
     * @param transactionCode
     * @return
     *     returns com.xignite.services.IssuerTransactionSummary
     */
    @WebMethod(operationName = "GetIssuerTransactionSummary", action = "http://www.xignite.com/services/GetIssuerTransactionSummary")
    @WebResult(name = "GetIssuerTransactionSummaryResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetIssuerTransactionSummary", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetIssuerTransactionSummary")
    @ResponseWrapper(localName = "GetIssuerTransactionSummaryResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetIssuerTransactionSummaryResponse")
    public IssuerTransactionSummary getIssuerTransactionSummary(
        @WebParam(name = "IssuerIdentifier", targetNamespace = "http://www.xignite.com/services/")
        String issuerIdentifier,
        @WebParam(name = "IssuerIdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes issuerIdentifierType,
        @WebParam(name = "FromDate", targetNamespace = "http://www.xignite.com/services/")
        String fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://www.xignite.com/services/")
        String toDate,
        @WebParam(name = "TransactionCode", targetNamespace = "http://www.xignite.com/services/")
        TransactionCodes transactionCode,
        @WebParam(name = "SecurityType", targetNamespace = "http://www.xignite.com/services/")
        SecurityTypes securityType,
        @WebParam(name = "OwnershipType", targetNamespace = "http://www.xignite.com/services/")
        OwnershipTypes ownershipType);

    /**
     * Returns all insider transactions for a single firm.
     * 
     * @param fromDate
     * @param ownershipType
     * @param issuerIdentifier
     * @param securityType
     * @param toDate
     * @param issuerIdentifierType
     * @param transactionCode
     * @return
     *     returns com.xignite.services.IssuerTransactions
     */
    @WebMethod(operationName = "GetIssuerTransactions", action = "http://www.xignite.com/services/GetIssuerTransactions")
    @WebResult(name = "GetIssuerTransactionsResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetIssuerTransactions", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetIssuerTransactions")
    @ResponseWrapper(localName = "GetIssuerTransactionsResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetIssuerTransactionsResponse")
    public IssuerTransactions getIssuerTransactions(
        @WebParam(name = "IssuerIdentifier", targetNamespace = "http://www.xignite.com/services/")
        String issuerIdentifier,
        @WebParam(name = "IssuerIdentifierType", targetNamespace = "http://www.xignite.com/services/")
        IdentifierTypes issuerIdentifierType,
        @WebParam(name = "FromDate", targetNamespace = "http://www.xignite.com/services/")
        String fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://www.xignite.com/services/")
        String toDate,
        @WebParam(name = "TransactionCode", targetNamespace = "http://www.xignite.com/services/")
        TransactionCodes transactionCode,
        @WebParam(name = "SecurityType", targetNamespace = "http://www.xignite.com/services/")
        SecurityTypes securityType,
        @WebParam(name = "OwnershipType", targetNamespace = "http://www.xignite.com/services/")
        OwnershipTypes ownershipType);

    /**
     * Returns all insider transactions for a all firms for a date.
     * 
     * @param ownershipType
     * @param onDate
     * @param securityType
     * @param transactionCode
     * @return
     *     returns com.xignite.services.IssuerTransactions
     */
    @WebMethod(operationName = "GetAllIssuerTransactions", action = "http://www.xignite.com/services/GetAllIssuerTransactions")
    @WebResult(name = "GetAllIssuerTransactionsResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetAllIssuerTransactions", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetAllIssuerTransactions")
    @ResponseWrapper(localName = "GetAllIssuerTransactionsResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetAllIssuerTransactionsResponse")
    public IssuerTransactions getAllIssuerTransactions(
        @WebParam(name = "OnDate", targetNamespace = "http://www.xignite.com/services/")
        String onDate,
        @WebParam(name = "TransactionCode", targetNamespace = "http://www.xignite.com/services/")
        TransactionCodes transactionCode,
        @WebParam(name = "SecurityType", targetNamespace = "http://www.xignite.com/services/")
        SecurityTypes securityType,
        @WebParam(name = "OwnershipType", targetNamespace = "http://www.xignite.com/services/")
        OwnershipTypes ownershipType);

    /**
     * Returns a list of firms that had insider transactions during a date range.
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns com.xignite.services.ArrayOfIssuerChange
     */
    @WebMethod(operationName = "GetAllIssuerTransactionsRange", action = "http://www.xignite.com/services/GetAllIssuerTransactionsRange")
    @WebResult(name = "GetAllIssuerTransactionsRangeResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetAllIssuerTransactionsRange", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetAllIssuerTransactionsRange")
    @ResponseWrapper(localName = "GetAllIssuerTransactionsRangeResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetAllIssuerTransactionsRangeResponse")
    public ArrayOfIssuerChange getAllIssuerTransactionsRange(
        @WebParam(name = "FromDate", targetNamespace = "http://www.xignite.com/services/")
        String fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://www.xignite.com/services/")
        String toDate);

    /**
     * Retrieve a text Filing by Url.
     * 
     * @param htmLize
     * @param textFileUrl
     * @return
     *     returns com.xignite.services.FilingAsText
     */
    @WebMethod(operationName = "GetFilingAsText", action = "http://www.xignite.com/services/GetFilingAsText")
    @WebResult(name = "GetFilingAsTextResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetFilingAsText", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetFilingAsText")
    @ResponseWrapper(localName = "GetFilingAsTextResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetFilingAsTextResponse")
    public FilingAsText getFilingAsText(
        @WebParam(name = "TextFileUrl", targetNamespace = "http://www.xignite.com/services/")
        String textFileUrl,
        @WebParam(name = "HTMLize", targetNamespace = "http://www.xignite.com/services/")
        boolean htmLize);

}
