
package gov.nsw.lands.address.ws;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AddressSearchService", targetNamespace = "http://ws.address.lands.nsw.gov", wsdlLocation = "META-INF/wsdl/AddressSearch.wsdl")
public class AddressSearchService
    extends Service
{

    private final static URL ADDRESSSEARCHSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADDRESSSEARCHSERVICE_EXCEPTION;
    private final static QName ADDRESSSEARCHSERVICE_QNAME = new QName("http://ws.address.lands.nsw.gov", "AddressSearchService");

    static {
        ADDRESSSEARCHSERVICE_WSDL_LOCATION = gov.nsw.lands.address.ws.AddressSearchService.class.getClassLoader().getResource("META-INF/wsdl/AddressSearch.wsdl");
        WebServiceException e = null;
        if (ADDRESSSEARCHSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/AddressSearch.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        ADDRESSSEARCHSERVICE_EXCEPTION = e;
    }

    public AddressSearchService() {
        super(__getWsdlLocation(), ADDRESSSEARCHSERVICE_QNAME);
    }

    public AddressSearchService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADDRESSSEARCHSERVICE_QNAME, features);
    }

    public AddressSearchService(URL wsdlLocation) {
        super(wsdlLocation, ADDRESSSEARCHSERVICE_QNAME);
    }

    public AddressSearchService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADDRESSSEARCHSERVICE_QNAME, features);
    }

    public AddressSearchService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AddressSearchService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AddressSearch
     */
    @WebEndpoint(name = "AddressSearch")
    public AddressSearch getAddressSearch() {
        return super.getPort(new QName("http://ws.address.lands.nsw.gov", "AddressSearch"), AddressSearch.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddressSearch
     */
    @WebEndpoint(name = "AddressSearch")
    public AddressSearch getAddressSearch(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.address.lands.nsw.gov", "AddressSearch"), AddressSearch.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADDRESSSEARCHSERVICE_EXCEPTION!= null) {
            throw ADDRESSSEARCHSERVICE_EXCEPTION;
        }
        return ADDRESSSEARCHSERVICE_WSDL_LOCATION;
    }

}
