
package org.diacomp.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ModelWebServiceSoap", targetNamespace = "http://www.diacomp.org/webservices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ModelWebServiceSoap {


    /**
     * This method will return an Model for the specified matching ModelID 
     * 
     * @param modelID
     * @return
     *     returns org.diacomp.webservices.Model
     */
    @WebMethod(operationName = "GetModel", action = "http://www.diacomp.org/webservices/GetModel")
    @WebResult(name = "GetModelResult", targetNamespace = "http://www.diacomp.org/webservices/")
    @RequestWrapper(localName = "GetModel", targetNamespace = "http://www.diacomp.org/webservices/", className = "org.diacomp.webservices.GetModel")
    @ResponseWrapper(localName = "GetModelResponse", targetNamespace = "http://www.diacomp.org/webservices/", className = "org.diacomp.webservices.GetModelResponse")
    public Model getModel(
        @WebParam(name = "ModelID", targetNamespace = "http://www.diacomp.org/webservices/")
        int modelID);

    /**
     * This method will return a list of Models
     * 
     * @return
     *     returns org.diacomp.webservices.ArrayOfModel
     */
    @WebMethod(operationName = "GetModels", action = "http://www.diacomp.org/webservices/GetModels")
    @WebResult(name = "GetModelsResult", targetNamespace = "http://www.diacomp.org/webservices/")
    @RequestWrapper(localName = "GetModels", targetNamespace = "http://www.diacomp.org/webservices/", className = "org.diacomp.webservices.GetModels")
    @ResponseWrapper(localName = "GetModelsResponse", targetNamespace = "http://www.diacomp.org/webservices/", className = "org.diacomp.webservices.GetModelsResponse")
    public ArrayOfModel getModels();

    /**
     * This method will return a list of Models that meet the optional Model Search criteria
     * 
     * @param modelSearch
     * @return
     *     returns org.diacomp.webservices.ArrayOfModel
     */
    @WebMethod(operationName = "GetModelsBySearch", action = "http://www.diacomp.org/webservices/GetModelsBySearch")
    @WebResult(name = "GetModelsBySearchResult", targetNamespace = "http://www.diacomp.org/webservices/")
    @RequestWrapper(localName = "GetModelsBySearch", targetNamespace = "http://www.diacomp.org/webservices/", className = "org.diacomp.webservices.GetModelsBySearch")
    @ResponseWrapper(localName = "GetModelsBySearchResponse", targetNamespace = "http://www.diacomp.org/webservices/", className = "org.diacomp.webservices.GetModelsBySearchResponse")
    public ArrayOfModel getModelsBySearch(
        @WebParam(name = "modelSearch", targetNamespace = "http://www.diacomp.org/webservices/")
        ModelSearch modelSearch);

    /**
     * This method will return the list of associated experiments for a specified model
     * 
     * @param modelID
     * @return
     *     returns org.diacomp.webservices.ArrayOfInvestigator
     */
    @WebMethod(operationName = "GetModelExperiments", action = "http://www.diacomp.org/webservices/GetModelExperiments")
    @WebResult(name = "GetModelExperimentsResult", targetNamespace = "http://www.diacomp.org/webservices/")
    @RequestWrapper(localName = "GetModelExperiments", targetNamespace = "http://www.diacomp.org/webservices/", className = "org.diacomp.webservices.GetModelExperiments")
    @ResponseWrapper(localName = "GetModelExperimentsResponse", targetNamespace = "http://www.diacomp.org/webservices/", className = "org.diacomp.webservices.GetModelExperimentsResponse")
    public ArrayOfInvestigator getModelExperiments(
        @WebParam(name = "ModelID", targetNamespace = "http://www.diacomp.org/webservices/")
        int modelID);

}
