
package ch.comteach.contest;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Tax", targetNamespace = "http://contest.comteach.ch/", wsdlLocation = "META-INF/wsdl/17654_Switzerland_tax.wsdl")
public class Tax
    extends Service
{

    private final static URL TAX_WSDL_LOCATION;
    private final static WebServiceException TAX_EXCEPTION;
    private final static QName TAX_QNAME = new QName("http://contest.comteach.ch/", "Tax");

    static {
        TAX_WSDL_LOCATION = ch.comteach.contest.Tax.class.getClassLoader().getResource("META-INF/wsdl/17654_Switzerland_tax.wsdl");
        WebServiceException e = null;
        if (TAX_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/17654_Switzerland_tax.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        TAX_EXCEPTION = e;
    }

    public Tax() {
        super(__getWsdlLocation(), TAX_QNAME);
    }

    public Tax(WebServiceFeature... features) {
        super(__getWsdlLocation(), TAX_QNAME, features);
    }

    public Tax(URL wsdlLocation) {
        super(wsdlLocation, TAX_QNAME);
    }

    public Tax(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TAX_QNAME, features);
    }

    public Tax(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Tax(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TaxSoap
     */
    @WebEndpoint(name = "TaxSoap")
    public TaxSoap getTaxSoap() {
        return super.getPort(new QName("http://contest.comteach.ch/", "TaxSoap"), TaxSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaxSoap
     */
    @WebEndpoint(name = "TaxSoap")
    public TaxSoap getTaxSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://contest.comteach.ch/", "TaxSoap"), TaxSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TAX_EXCEPTION!= null) {
            throw TAX_EXCEPTION;
        }
        return TAX_WSDL_LOCATION;
    }

}
