
package ch.comteach.contest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TaxSoap", targetNamespace = "http://contest.comteach.ch/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TaxSoap {


    /**
     * 
     * @param numberOfChildren
     * @param year
     * @param taxableIncome
     * @param canton
     * @param civilState
     * @param borough
     * @param accessToken
     * @param taxableWealth
     * @param religion
     * @return
     *     returns ch.comteach.contest.CalculateSimpleResponse.CalculateSimpleResult
     */
    @WebMethod(operationName = "CalculateSimple", action = "http://contest.comteach.ch/CalculateSimple")
    @WebResult(name = "CalculateSimpleResult", targetNamespace = "http://contest.comteach.ch/")
    @RequestWrapper(localName = "CalculateSimple", targetNamespace = "http://contest.comteach.ch/", className = "ch.comteach.contest.CalculateSimple")
    @ResponseWrapper(localName = "CalculateSimpleResponse", targetNamespace = "http://contest.comteach.ch/", className = "ch.comteach.contest.CalculateSimpleResponse")
    public ch.comteach.contest.CalculateSimpleResponse.CalculateSimpleResult calculateSimple(
        @WebParam(name = "AccessToken", targetNamespace = "http://contest.comteach.ch/")
        String accessToken,
        @WebParam(name = "Year", targetNamespace = "http://contest.comteach.ch/")
        int year,
        @WebParam(name = "Canton", targetNamespace = "http://contest.comteach.ch/")
        String canton,
        @WebParam(name = "Borough", targetNamespace = "http://contest.comteach.ch/")
        String borough,
        @WebParam(name = "CivilState", targetNamespace = "http://contest.comteach.ch/")
        String civilState,
        @WebParam(name = "NumberOfChildren", targetNamespace = "http://contest.comteach.ch/")
        int numberOfChildren,
        @WebParam(name = "Religion", targetNamespace = "http://contest.comteach.ch/")
        String religion,
        @WebParam(name = "TaxableIncome", targetNamespace = "http://contest.comteach.ch/")
        double taxableIncome,
        @WebParam(name = "TaxableWealth", targetNamespace = "http://contest.comteach.ch/")
        double taxableWealth);

    /**
     * 
     * @param password
     * @param company
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateAccessToken", action = "http://contest.comteach.ch/CreateAccessToken")
    @WebResult(name = "CreateAccessTokenResult", targetNamespace = "http://contest.comteach.ch/")
    @RequestWrapper(localName = "CreateAccessToken", targetNamespace = "http://contest.comteach.ch/", className = "ch.comteach.contest.CreateAccessToken")
    @ResponseWrapper(localName = "CreateAccessTokenResponse", targetNamespace = "http://contest.comteach.ch/", className = "ch.comteach.contest.CreateAccessTokenResponse")
    public String createAccessToken(
        @WebParam(name = "Company", targetNamespace = "http://contest.comteach.ch/")
        String company,
        @WebParam(name = "Username", targetNamespace = "http://contest.comteach.ch/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://contest.comteach.ch/")
        String password);

    /**
     * 
     * @param zip
     * @param canton
     * @param borough
     * @return
     *     returns ch.comteach.contest.CheckTaxBoroughResponse.CheckTaxBoroughResult
     */
    @WebMethod(operationName = "CheckTaxBorough", action = "http://contest.comteach.ch/CheckTaxBorough")
    @WebResult(name = "CheckTaxBoroughResult", targetNamespace = "http://contest.comteach.ch/")
    @RequestWrapper(localName = "CheckTaxBorough", targetNamespace = "http://contest.comteach.ch/", className = "ch.comteach.contest.CheckTaxBorough")
    @ResponseWrapper(localName = "CheckTaxBoroughResponse", targetNamespace = "http://contest.comteach.ch/", className = "ch.comteach.contest.CheckTaxBoroughResponse")
    public ch.comteach.contest.CheckTaxBoroughResponse.CheckTaxBoroughResult checkTaxBorough(
        @WebParam(name = "Borough", targetNamespace = "http://contest.comteach.ch/")
        String borough,
        @WebParam(name = "Canton", targetNamespace = "http://contest.comteach.ch/")
        String canton,
        @WebParam(name = "ZIP", targetNamespace = "http://contest.comteach.ch/")
        String zip);

}
