
package ca.ubc.cstudies.netpub.dotnet.webservices.financialfunctions;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FinancialFunctions", targetNamespace = "http://netpub.cstudies.ubc.ca/dotnet/WebServices/FinancialFunctions", wsdlLocation = "META-INF/wsdl/1353_Canada_FinancialFunctions.wsdl")
public class FinancialFunctions
    extends Service
{

    private final static URL FINANCIALFUNCTIONS_WSDL_LOCATION;
    private final static WebServiceException FINANCIALFUNCTIONS_EXCEPTION;
    private final static QName FINANCIALFUNCTIONS_QNAME = new QName("http://netpub.cstudies.ubc.ca/dotnet/WebServices/FinancialFunctions", "FinancialFunctions");

    static {
        FINANCIALFUNCTIONS_WSDL_LOCATION = ca.ubc.cstudies.netpub.dotnet.webservices.financialfunctions.FinancialFunctions.class.getClassLoader().getResource("META-INF/wsdl/1353_Canada_FinancialFunctions.wsdl");
        WebServiceException e = null;
        if (FINANCIALFUNCTIONS_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/1353_Canada_FinancialFunctions.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        FINANCIALFUNCTIONS_EXCEPTION = e;
    }

    public FinancialFunctions() {
        super(__getWsdlLocation(), FINANCIALFUNCTIONS_QNAME);
    }

    public FinancialFunctions(WebServiceFeature... features) {
        super(__getWsdlLocation(), FINANCIALFUNCTIONS_QNAME, features);
    }

    public FinancialFunctions(URL wsdlLocation) {
        super(wsdlLocation, FINANCIALFUNCTIONS_QNAME);
    }

    public FinancialFunctions(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FINANCIALFUNCTIONS_QNAME, features);
    }

    public FinancialFunctions(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FinancialFunctions(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FinancialFunctionsSoap
     */
    @WebEndpoint(name = "FinancialFunctionsSoap")
    public FinancialFunctionsSoap getFinancialFunctionsSoap() {
        return super.getPort(new QName("http://netpub.cstudies.ubc.ca/dotnet/WebServices/FinancialFunctions", "FinancialFunctionsSoap"), FinancialFunctionsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FinancialFunctionsSoap
     */
    @WebEndpoint(name = "FinancialFunctionsSoap")
    public FinancialFunctionsSoap getFinancialFunctionsSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://netpub.cstudies.ubc.ca/dotnet/WebServices/FinancialFunctions", "FinancialFunctionsSoap"), FinancialFunctionsSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FINANCIALFUNCTIONS_EXCEPTION!= null) {
            throw FINANCIALFUNCTIONS_EXCEPTION;
        }
        return FINANCIALFUNCTIONS_WSDL_LOCATION;
    }

}
