
package com.qas.ondemand_2010_01;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "QASOnDemand", targetNamespace = "http://www.qas.com/OnDemand-2010-01")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.qas.ondemand_2010_01.ObjectFactory.class,
    org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.ObjectFactory.class
})
public interface QASOnDemand {


    /**
     * 
     * @param qaCanSearch
     * @return
     *     returns com.qas.ondemand_2010_01.QASearchOk
     */
    @WebMethod(operationName = "DoCanSearch", action = "http://www.qas.com/OnDemand-2010-01/DoCanSearch")
    @WebResult(name = "QASearchOk", targetNamespace = "http://www.qas.com/OnDemand-2010-01", partName = "DoCanSearchResult")
    public QASearchOk doCanSearch(
        @WebParam(name = "QACanSearch", targetNamespace = "http://www.qas.com/OnDemand-2010-01", partName = "QACanSearch")
        QACanSearch qaCanSearch);

    /**
     * 
     * @param qaGetAddress
     * @return
     *     returns com.qas.ondemand_2010_01.Address
     */
    @WebMethod(operationName = "DoGetAddress", action = "http://www.qas.com/OnDemand-2010-01/DoGetAddress")
    @WebResult(name = "Address", targetNamespace = "http://www.qas.com/OnDemand-2010-01", partName = "DoGetAddressResult")
    public Address doGetAddress(
        @WebParam(name = "QAGetAddress", targetNamespace = "http://www.qas.com/OnDemand-2010-01", partName = "QAGetAddress")
        QAGetAddress qaGetAddress);

    /**
     * 
     * @param qaGetData
     * @return
     *     returns com.qas.ondemand_2010_01.ArrayOfQADataSet
     */
    @WebMethod(operationName = "DoGetData", action = "http://www.qas.com/OnDemand-2010-01/DoGetData")
    @WebResult(name = "QAData", targetNamespace = "http://www.qas.com/OnDemand-2010-01", partName = "DoGetDataResult")
    public ArrayOfQADataSet doGetData(
        @WebParam(name = "QAGetData", targetNamespace = "http://www.qas.com/OnDemand-2010-01", partName = "QAGetData")
        QAGetData qaGetData);

    /**
     * 
     * @param qaGetExampleAddresses
     * @return
     *     returns com.qas.ondemand_2010_01.ArrayOfQAExampleAddress
     */
    @WebMethod(operationName = "DoGetExampleAddresses", action = "http://www.qas.com/OnDemand-2010-01/DoGetExampleAddresses")
    @WebResult(name = "QAExampleAddresses", targetNamespace = "http://www.qas.com/OnDemand-2010-01", partName = "DoGetExampleAddressesResult")
    public ArrayOfQAExampleAddress doGetExampleAddresses(
        @WebParam(name = "QAGetExampleAddresses", targetNamespace = "http://www.qas.com/OnDemand-2010-01", partName = "QAGetExampleAddresses")
        QAGetExampleAddresses qaGetExampleAddresses);

    /**
     * 
     * @param qaGetLayouts
     * @return
     *     returns com.qas.ondemand_2010_01.ArrayOfQALayout
     */
    @WebMethod(operationName = "DoGetLayouts", action = "http://www.qas.com/OnDemand-2010-01/DoGetLayouts")
    @WebResult(name = "QALayouts", targetNamespace = "http://www.qas.com/OnDemand-2010-01", partName = "DoGetLayoutsResult")
    public ArrayOfQALayout doGetLayouts(
        @WebParam(name = "QAGetLayouts", targetNamespace = "http://www.qas.com/OnDemand-2010-01", partName = "QAGetLayouts")
        QAGetLayouts qaGetLayouts);

    /**
     * 
     * @param qaGetLicenseInfo
     * @return
     *     returns com.qas.ondemand_2010_01.QALicenceInfo
     */
    @WebMethod(operationName = "DoGetLicenseInfo", action = "http://www.qas.com/OnDemand-2010-01/DoGetLicenseInfo")
    @WebResult(name = "QALicenceInfo", targetNamespace = "http://www.qas.com/OnDemand-2010-01", partName = "DoGetLicenseInfoResult")
    public QALicenceInfo doGetLicenseInfo(
        @WebParam(name = "QAGetLicenseInfo", targetNamespace = "http://www.qas.com/OnDemand-2010-01", partName = "QAGetLicenseInfo")
        QAGetLicenseInfo qaGetLicenseInfo);

    /**
     * 
     * @param qaGetPromptSet
     * @return
     *     returns com.qas.ondemand_2010_01.QAPromptSet
     */
    @WebMethod(operationName = "DoGetPromptSet", action = "http://www.qas.com/OnDemand-2010-01/DoGetPromptSet")
    @WebResult(name = "QAPromptSet", targetNamespace = "http://www.qas.com/OnDemand-2010-01", partName = "DoGetPromptSetResult")
    public QAPromptSet doGetPromptSet(
        @WebParam(name = "QAGetPromptSet", targetNamespace = "http://www.qas.com/OnDemand-2010-01", partName = "QAGetPromptSet")
        QAGetPromptSet qaGetPromptSet);

    /**
     * 
     * @param qaGetSystemInfo
     * @return
     *     returns com.qas.ondemand_2010_01.ArrayOfString
     */
    @WebMethod(operationName = "DoGetSystemInfo", action = "http://www.qas.com/OnDemand-2010-01/DoGetSystemInfo")
    @WebResult(name = "QASystemInfo", targetNamespace = "http://www.qas.com/OnDemand-2010-01", partName = "DoGetSystemInfoResult")
    public ArrayOfString doGetSystemInfo(
        @WebParam(name = "QAGetSystemInfo", targetNamespace = "http://www.qas.com/OnDemand-2010-01", partName = "QAGetSystemInfo")
        QAGetSystemInfo qaGetSystemInfo);

    /**
     * 
     * @param qaRefine
     * @return
     *     returns com.qas.ondemand_2010_01.Picklist
     */
    @WebMethod(operationName = "DoRefine", action = "http://www.qas.com/OnDemand-2010-01/DoRefine")
    @WebResult(name = "Picklist", targetNamespace = "http://www.qas.com/OnDemand-2010-01", partName = "DoRefineResult")
    public Picklist doRefine(
        @WebParam(name = "QARefine", targetNamespace = "http://www.qas.com/OnDemand-2010-01", partName = "QARefine")
        QARefine qaRefine);

    /**
     * 
     * @param qaSearch
     * @return
     *     returns com.qas.ondemand_2010_01.QASearchResult
     */
    @WebMethod(operationName = "DoSearch", action = "http://www.qas.com/OnDemand-2010-01/DoSearch")
    @WebResult(name = "QASearchResult", targetNamespace = "http://www.qas.com/OnDemand-2010-01", partName = "DoSearchResult")
    public QASearchResult doSearch(
        @WebParam(name = "QASearch", targetNamespace = "http://www.qas.com/OnDemand-2010-01", partName = "QASearch")
        QASearch qaSearch);

    /**
     * 
     * @param qaBulkSearch
     * @return
     *     returns com.qas.ondemand_2010_01.QABulkSearchResult
     */
    @WebMethod(operationName = "DoBulkSearch", action = "http://www.qas.com/OnDemand-2010-01/DoBulkSearch")
    @WebResult(name = "QABulkSearchResult", targetNamespace = "http://www.qas.com/OnDemand-2010-01", partName = "DoBulkSearchResult")
    public QABulkSearchResult doBulkSearch(
        @WebParam(name = "QABulkSearch", targetNamespace = "http://www.qas.com/OnDemand-2010-01", partName = "QABulkSearch")
        QABulkSearch qaBulkSearch);

    /**
     * 
     * @param qaGetDataMapDetail
     * @return
     *     returns com.qas.ondemand_2010_01.QADataMapDetail
     */
    @WebMethod(operationName = "DoGetDataMapDetail", action = "http://www.qas.com/OnDemand-2010-01/DoGetDataMapDetail")
    @WebResult(name = "QADataMapDetail", targetNamespace = "http://www.qas.com/OnDemand-2010-01", partName = "DoGetDataMapDetailResult")
    public QADataMapDetail doGetDataMapDetail(
        @WebParam(name = "QAGetDataMapDetail", targetNamespace = "http://www.qas.com/OnDemand-2010-01", partName = "QAGetDataMapDetail")
        QAGetDataMapDetail qaGetDataMapDetail);

}
