
package com.clearforest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "calaisSoap", targetNamespace = "http://clearforest.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalaisSoap {


    /**
     * 
     * @param paramsXML
     * @param licenseID
     * @param content
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Enlighten", action = "http://clearforest.com/Enlighten")
    @WebResult(name = "EnlightenResult", targetNamespace = "http://clearforest.com/")
    @RequestWrapper(localName = "Enlighten", targetNamespace = "http://clearforest.com/", className = "com.clearforest.Enlighten")
    @ResponseWrapper(localName = "EnlightenResponse", targetNamespace = "http://clearforest.com/", className = "com.clearforest.EnlightenResponse")
    public String enlighten(
        @WebParam(name = "licenseID", targetNamespace = "http://clearforest.com/")
        String licenseID,
        @WebParam(name = "content", targetNamespace = "http://clearforest.com/")
        String content,
        @WebParam(name = "paramsXML", targetNamespace = "http://clearforest.com/")
        String paramsXML);

}
