
package uk.co.astonprograms.ap_licencing;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LicencingSoap", targetNamespace = "http://www.astonprograms.co.uk/AP_Licencing")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LicencingSoap {


    /**
     * 
     * @param productName
     * @param url
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "CheckLicence", action = "http://www.astonprograms.co.uk/AP_Licencing/CheckLicence")
    @WebResult(name = "CheckLicenceResult", targetNamespace = "http://www.astonprograms.co.uk/AP_Licencing")
    @RequestWrapper(localName = "CheckLicence", targetNamespace = "http://www.astonprograms.co.uk/AP_Licencing", className = "uk.co.astonprograms.ap_licencing.CheckLicence")
    @ResponseWrapper(localName = "CheckLicenceResponse", targetNamespace = "http://www.astonprograms.co.uk/AP_Licencing", className = "uk.co.astonprograms.ap_licencing.CheckLicenceResponse")
    public boolean checkLicence(
        @WebParam(name = "productName", targetNamespace = "http://www.astonprograms.co.uk/AP_Licencing")
        String productName,
        @WebParam(name = "url", targetNamespace = "http://www.astonprograms.co.uk/AP_Licencing")
        String url);

}
