
package com.myasptools;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WeatherFetcherSoap", targetNamespace = "http://www.myasptools.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WeatherFetcherSoap {


    /**
     * This method returns the U.S. weather info based upon the 5 digit zip code
     * 
     * @param zipCode
     * @return
     *     returns com.myasptools.Weather
     */
    @WebMethod(operationName = "GetWeather", action = "http://www.myasptools.com/GetWeather")
    @WebResult(name = "GetWeatherResult", targetNamespace = "http://www.myasptools.com/")
    @RequestWrapper(localName = "GetWeather", targetNamespace = "http://www.myasptools.com/", className = "com.myasptools.GetWeather")
    @ResponseWrapper(localName = "GetWeatherResponse", targetNamespace = "http://www.myasptools.com/", className = "com.myasptools.GetWeatherResponse")
    public Weather getWeather(
        @WebParam(name = "zipCode", targetNamespace = "http://www.myasptools.com/")
        String zipCode);

    /**
     * This method returns the U.S. weather info based upon the 5 digit zip code
     * 
     * @param zipCode
     * @param licNumber
     * @return
     *     returns com.myasptools.Weather
     */
    @WebMethod(operationName = "GetLicWeather", action = "http://www.myasptools.com/GetLicWeather")
    @WebResult(name = "GetLicWeatherResult", targetNamespace = "http://www.myasptools.com/")
    @RequestWrapper(localName = "GetLicWeather", targetNamespace = "http://www.myasptools.com/", className = "com.myasptools.GetLicWeather")
    @ResponseWrapper(localName = "GetLicWeatherResponse", targetNamespace = "http://www.myasptools.com/", className = "com.myasptools.GetLicWeatherResponse")
    public Weather getLicWeather(
        @WebParam(name = "zipCode", targetNamespace = "http://www.myasptools.com/")
        String zipCode,
        @WebParam(name = "licNumber", targetNamespace = "http://www.myasptools.com/")
        String licNumber);

}
