
package com.myasptools;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WeatherFetcher", targetNamespace = "http://www.myasptools.com/", wsdlLocation = "META-INF/wsdl/service227.wsdl")
public class WeatherFetcher
    extends Service
{

    private final static URL WEATHERFETCHER_WSDL_LOCATION;
    private final static WebServiceException WEATHERFETCHER_EXCEPTION;
    private final static QName WEATHERFETCHER_QNAME = new QName("http://www.myasptools.com/", "WeatherFetcher");

    static {
        WEATHERFETCHER_WSDL_LOCATION = com.myasptools.WeatherFetcher.class.getClassLoader().getResource("META-INF/wsdl/service227.wsdl");
        WebServiceException e = null;
        if (WEATHERFETCHER_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/service227.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        WEATHERFETCHER_EXCEPTION = e;
    }

    public WeatherFetcher() {
        super(__getWsdlLocation(), WEATHERFETCHER_QNAME);
    }

    public WeatherFetcher(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEATHERFETCHER_QNAME, features);
    }

    public WeatherFetcher(URL wsdlLocation) {
        super(wsdlLocation, WEATHERFETCHER_QNAME);
    }

    public WeatherFetcher(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEATHERFETCHER_QNAME, features);
    }

    public WeatherFetcher(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WeatherFetcher(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WeatherFetcherSoap
     */
    @WebEndpoint(name = "WeatherFetcherSoap")
    public WeatherFetcherSoap getWeatherFetcherSoap() {
        return super.getPort(new QName("http://www.myasptools.com/", "WeatherFetcherSoap"), WeatherFetcherSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeatherFetcherSoap
     */
    @WebEndpoint(name = "WeatherFetcherSoap")
    public WeatherFetcherSoap getWeatherFetcherSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.myasptools.com/", "WeatherFetcherSoap"), WeatherFetcherSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEATHERFETCHER_EXCEPTION!= null) {
            throw WEATHERFETCHER_EXCEPTION;
        }
        return WEATHERFETCHER_WSDL_LOCATION;
    }

}
