
package webservices;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * 
 * Description: This model forecasts the overall financial health of the Wright Flyer production company.
 * 
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Company%20Simulation", targetNamespace = "http://webservices", wsdlLocation = "META-INF/wsdl/10327_United_States_Company_Simulation.wsdl")
public class Company_002520Simulation
    extends Service
{

    private final static URL COMPANY_002520SIMULATION_WSDL_LOCATION;
    private final static WebServiceException COMPANY_002520SIMULATION_EXCEPTION;
    private final static QName COMPANY_002520SIMULATION_QNAME = new QName("http://webservices", "Company%20Simulation");

    static {
        COMPANY_002520SIMULATION_WSDL_LOCATION = webservices.Company_002520Simulation.class.getClassLoader().getResource("META-INF/wsdl/10327_United_States_Company_Simulation.wsdl");
        WebServiceException e = null;
        if (COMPANY_002520SIMULATION_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/10327_United_States_Company_Simulation.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        COMPANY_002520SIMULATION_EXCEPTION = e;
    }

    public Company_002520Simulation() {
        super(__getWsdlLocation(), COMPANY_002520SIMULATION_QNAME);
    }

    public Company_002520Simulation(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMPANY_002520SIMULATION_QNAME, features);
    }

    public Company_002520Simulation(URL wsdlLocation) {
        super(wsdlLocation, COMPANY_002520SIMULATION_QNAME);
    }

    public Company_002520Simulation(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMPANY_002520SIMULATION_QNAME, features);
    }

    public Company_002520Simulation(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Company_002520Simulation(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicePortType
     */
    @WebEndpoint(name = "ServicePort")
    public ServicePortType getServicePort() {
        return super.getPort(new QName("http://webservices", "ServicePort"), ServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicePortType
     */
    @WebEndpoint(name = "ServicePort")
    public ServicePortType getServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices", "ServicePort"), ServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMPANY_002520SIMULATION_EXCEPTION!= null) {
            throw COMPANY_002520SIMULATION_EXCEPTION;
        }
        return COMPANY_002520SIMULATION_WSDL_LOCATION;
    }

}
