
package jp.co.est.btonic.zipcode;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * \u90f5\u4fbf\u756a\u53f7\u30c7\u30fc\u30bf\u3092\u691c\u7d22\u3057\u3066\u304f\u308c\u308bWeb\u30b5\u30fc\u30d3\u30b9\u3067\u3059\u3002
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SearchEngine", targetNamespace = "http://btonic.est.co.jp/zipcode/", wsdlLocation = "META-INF/wsdl/SearchEngine.wsdl")
public class SearchEngine
    extends Service
{

    private final static URL SEARCHENGINE_WSDL_LOCATION;
    private final static WebServiceException SEARCHENGINE_EXCEPTION;
    private final static QName SEARCHENGINE_QNAME = new QName("http://btonic.est.co.jp/zipcode/", "SearchEngine");

    static {
        SEARCHENGINE_WSDL_LOCATION = jp.co.est.btonic.zipcode.SearchEngine.class.getClassLoader().getResource("META-INF/wsdl/SearchEngine.wsdl");
        WebServiceException e = null;
        if (SEARCHENGINE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/SearchEngine.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        SEARCHENGINE_EXCEPTION = e;
    }

    public SearchEngine() {
        super(__getWsdlLocation(), SEARCHENGINE_QNAME);
    }

    public SearchEngine(WebServiceFeature... features) {
        super(__getWsdlLocation(), SEARCHENGINE_QNAME, features);
    }

    public SearchEngine(URL wsdlLocation) {
        super(wsdlLocation, SEARCHENGINE_QNAME);
    }

    public SearchEngine(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SEARCHENGINE_QNAME, features);
    }

    public SearchEngine(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SearchEngine(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SearchEngineSoap
     */
    @WebEndpoint(name = "SearchEngineSoap")
    public SearchEngineSoap getSearchEngineSoap() {
        return super.getPort(new QName("http://btonic.est.co.jp/zipcode/", "SearchEngineSoap"), SearchEngineSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SearchEngineSoap
     */
    @WebEndpoint(name = "SearchEngineSoap")
    public SearchEngineSoap getSearchEngineSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://btonic.est.co.jp/zipcode/", "SearchEngineSoap"), SearchEngineSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SEARCHENGINE_EXCEPTION!= null) {
            throw SEARCHENGINE_EXCEPTION;
        }
        return SEARCHENGINE_WSDL_LOCATION;
    }

}
