
package com.xignite.services;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This web service provides corporate press release information.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "XigniteReleases", targetNamespace = "http://www.xignite.com/services/", wsdlLocation = "META-INF/wsdl/XigniteReleases.wsdl")
public class XigniteReleases
    extends Service
{

    private final static URL XIGNITERELEASES_WSDL_LOCATION;
    private final static WebServiceException XIGNITERELEASES_EXCEPTION;
    private final static QName XIGNITERELEASES_QNAME = new QName("http://www.xignite.com/services/", "XigniteReleases");

    static {
        XIGNITERELEASES_WSDL_LOCATION = com.xignite.services.XigniteReleases.class.getClassLoader().getResource("META-INF/wsdl/XigniteReleases.wsdl");
        WebServiceException e = null;
        if (XIGNITERELEASES_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/XigniteReleases.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        XIGNITERELEASES_EXCEPTION = e;
    }

    public XigniteReleases() {
        super(__getWsdlLocation(), XIGNITERELEASES_QNAME);
    }

    public XigniteReleases(WebServiceFeature... features) {
        super(__getWsdlLocation(), XIGNITERELEASES_QNAME, features);
    }

    public XigniteReleases(URL wsdlLocation) {
        super(wsdlLocation, XIGNITERELEASES_QNAME);
    }

    public XigniteReleases(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, XIGNITERELEASES_QNAME, features);
    }

    public XigniteReleases(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XigniteReleases(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns XigniteReleasesSoap
     */
    @WebEndpoint(name = "XigniteReleasesSoap")
    public XigniteReleasesSoap getXigniteReleasesSoap() {
        return super.getPort(new QName("http://www.xignite.com/services/", "XigniteReleasesSoap"), XigniteReleasesSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns XigniteReleasesSoap
     */
    @WebEndpoint(name = "XigniteReleasesSoap")
    public XigniteReleasesSoap getXigniteReleasesSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.xignite.com/services/", "XigniteReleasesSoap"), XigniteReleasesSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (XIGNITERELEASES_EXCEPTION!= null) {
            throw XIGNITERELEASES_EXCEPTION;
        }
        return XIGNITERELEASES_WSDL_LOCATION;
    }

}
