
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.ftv_hotel_business.ArrayOfHotel;
import org.datacontract.schemas._2004._07.ftv_hotel_business.ArrayOfHotelCodigo;
import org.datacontract.schemas._2004._07.ftv_hotel_business.ArrayOfHotelDestaque;
import org.datacontract.schemas._2004._07.ftv_hotel_business.ArrayOfHotelFacilidade;
import org.datacontract.schemas._2004._07.ftv_hotel_business.ArrayOfHotelFoto;
import org.datacontract.schemas._2004._07.ftv_hotel_business.ArrayOfHotelLocalizacao;
import org.datacontract.schemas._2004._07.ftv_hotel_business.Atualizacao;
import org.datacontract.schemas._2004._07.ftv_hotel_business.CancelamentoParametro;
import org.datacontract.schemas._2004._07.ftv_hotel_business.CancelamentoRetorno;
import org.datacontract.schemas._2004._07.ftv_hotel_business.ConsultaFacilidadeFiltro;
import org.datacontract.schemas._2004._07.ftv_hotel_business.ConsultaFotoFiltro;
import org.datacontract.schemas._2004._07.ftv_hotel_business.CosultaFiltro;
import org.datacontract.schemas._2004._07.ftv_hotel_business.CosultaInformacaoFiltro;
import org.datacontract.schemas._2004._07.ftv_hotel_business.HotelAlteradoConfirmacao;
import org.datacontract.schemas._2004._07.ftv_hotel_business.HotelAlteradoConfirmacaoFiltro;
import org.datacontract.schemas._2004._07.ftv_hotel_business.HotelAlteradoFiltro;
import org.datacontract.schemas._2004._07.ftv_hotel_business.HotelDestaque;
import org.datacontract.schemas._2004._07.ftv_hotel_business.HotelLocalizacaoFiltro;
import org.datacontract.schemas._2004._07.ftv_hotel_business.HotelRetorno;
import org.datacontract.schemas._2004._07.ftv_hotel_business.ReservaParametro;
import org.datacontract.schemas._2004._07.ftv_hotel_business.ReservaRetorno;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IVenda", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.ftv_hotel_business.ObjectFactory.class,
    org.datacontract.schemas._2004._07.ftv_shared.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface IVenda {


    /**
     * 
     * @param consultaFiltro
     * @return
     *     returns org.datacontract.schemas._2004._07.ftv_hotel_business.HotelRetorno
     */
    @WebMethod(operationName = "Consultar", action = "http://tempuri.org/IVenda/Consultar")
    @WebResult(name = "ConsultarResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Consultar", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Consultar")
    @ResponseWrapper(localName = "ConsultarResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarResponse")
    public HotelRetorno consultar(
        @WebParam(name = "consultaFiltro", targetNamespace = "http://tempuri.org/")
        CosultaFiltro consultaFiltro);

    /**
     * 
     * @param consultaFiltro
     * @return
     *     returns org.datacontract.schemas._2004._07.ftv_hotel_business.HotelRetorno
     */
    @WebMethod(operationName = "Retornar", action = "http://tempuri.org/IVenda/Retornar")
    @WebResult(name = "RetornarResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Retornar", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Retornar")
    @ResponseWrapper(localName = "RetornarResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RetornarResponse")
    public HotelRetorno retornar(
        @WebParam(name = "consultaFiltro", targetNamespace = "http://tempuri.org/")
        CosultaFiltro consultaFiltro);

    /**
     * 
     * @param consultaFiltro
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "ContadorHoteisProcessados", action = "http://tempuri.org/IVenda/ContadorHoteisProcessados")
    @WebResult(name = "ContadorHoteisProcessadosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ContadorHoteisProcessados", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ContadorHoteisProcessados")
    @ResponseWrapper(localName = "ContadorHoteisProcessadosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ContadorHoteisProcessadosResponse")
    public Integer contadorHoteisProcessados(
        @WebParam(name = "consultaFiltro", targetNamespace = "http://tempuri.org/")
        CosultaFiltro consultaFiltro);

    /**
     * 
     * @param consultaFiltro
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "VerificarConsultaFinalizada", action = "http://tempuri.org/IVenda/VerificarConsultaFinalizada")
    @WebResult(name = "VerificarConsultaFinalizadaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "VerificarConsultaFinalizada", targetNamespace = "http://tempuri.org/", className = "org.tempuri.VerificarConsultaFinalizada")
    @ResponseWrapper(localName = "VerificarConsultaFinalizadaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.VerificarConsultaFinalizadaResponse")
    public Boolean verificarConsultaFinalizada(
        @WebParam(name = "consultaFiltro", targetNamespace = "http://tempuri.org/")
        CosultaFiltro consultaFiltro);

    /**
     * 
     * @param consultaFiltro
     * @return
     *     returns org.datacontract.schemas._2004._07.ftv_hotel_business.ArrayOfHotel
     */
    @WebMethod(operationName = "ConsultarHotel", action = "http://tempuri.org/IVenda/ConsultarHotel")
    @WebResult(name = "ConsultarHotelResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarHotel", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarHotel")
    @ResponseWrapper(localName = "ConsultarHotelResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarHotelResponse")
    public ArrayOfHotel consultarHotel(
        @WebParam(name = "consultaFiltro", targetNamespace = "http://tempuri.org/")
        CosultaFiltro consultaFiltro);

    /**
     * 
     * @param hotelAlteradoFiltro
     * @return
     *     returns org.datacontract.schemas._2004._07.ftv_hotel_business.ArrayOfHotelCodigo
     */
    @WebMethod(operationName = "ConsultarHotelAlterado", action = "http://tempuri.org/IVenda/ConsultarHotelAlterado")
    @WebResult(name = "ConsultarHotelAlteradoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarHotelAlterado", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarHotelAlterado")
    @ResponseWrapper(localName = "ConsultarHotelAlteradoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarHotelAlteradoResponse")
    public ArrayOfHotelCodigo consultarHotelAlterado(
        @WebParam(name = "hotelAlteradoFiltro", targetNamespace = "http://tempuri.org/")
        HotelAlteradoFiltro hotelAlteradoFiltro);

    /**
     * 
     * @param hotelAlteradoConfirmacaoFiltro
     * @return
     *     returns org.datacontract.schemas._2004._07.ftv_hotel_business.HotelAlteradoConfirmacao
     */
    @WebMethod(operationName = "ConfirmarHotelAlterado", action = "http://tempuri.org/IVenda/ConfirmarHotelAlterado")
    @WebResult(name = "ConfirmarHotelAlteradoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConfirmarHotelAlterado", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConfirmarHotelAlterado")
    @ResponseWrapper(localName = "ConfirmarHotelAlteradoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConfirmarHotelAlteradoResponse")
    public HotelAlteradoConfirmacao confirmarHotelAlterado(
        @WebParam(name = "hotelAlteradoConfirmacaoFiltro", targetNamespace = "http://tempuri.org/")
        HotelAlteradoConfirmacaoFiltro hotelAlteradoConfirmacaoFiltro);

    /**
     * 
     * @param consultaFiltro
     * @return
     *     returns org.datacontract.schemas._2004._07.ftv_hotel_business.ArrayOfHotel
     */
    @WebMethod(operationName = "ConsultarHotelInformacao", action = "http://tempuri.org/IVenda/ConsultarHotelInformacao")
    @WebResult(name = "ConsultarHotelInformacaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarHotelInformacao", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarHotelInformacao")
    @ResponseWrapper(localName = "ConsultarHotelInformacaoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarHotelInformacaoResponse")
    public ArrayOfHotel consultarHotelInformacao(
        @WebParam(name = "consultaFiltro", targetNamespace = "http://tempuri.org/")
        CosultaInformacaoFiltro consultaFiltro);

    /**
     * 
     * @param cosultaFacilidadeFiltro
     * @return
     *     returns org.datacontract.schemas._2004._07.ftv_hotel_business.ArrayOfHotelFacilidade
     */
    @WebMethod(operationName = "ConsultarHotelFacilidade", action = "http://tempuri.org/IVenda/ConsultarHotelFacilidade")
    @WebResult(name = "ConsultarHotelFacilidadeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarHotelFacilidade", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarHotelFacilidade")
    @ResponseWrapper(localName = "ConsultarHotelFacilidadeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarHotelFacilidadeResponse")
    public ArrayOfHotelFacilidade consultarHotelFacilidade(
        @WebParam(name = "cosultaFacilidadeFiltro", targetNamespace = "http://tempuri.org/")
        ConsultaFacilidadeFiltro cosultaFacilidadeFiltro);

    /**
     * 
     * @param cosultaFotoFiltro
     * @return
     *     returns org.datacontract.schemas._2004._07.ftv_hotel_business.ArrayOfHotelFoto
     */
    @WebMethod(operationName = "ConsultarHotelFoto", action = "http://tempuri.org/IVenda/ConsultarHotelFoto")
    @WebResult(name = "ConsultarHotelFotoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarHotelFoto", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarHotelFoto")
    @ResponseWrapper(localName = "ConsultarHotelFotoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarHotelFotoResponse")
    public ArrayOfHotelFoto consultarHotelFoto(
        @WebParam(name = "cosultaFotoFiltro", targetNamespace = "http://tempuri.org/")
        ConsultaFotoFiltro cosultaFotoFiltro);

    /**
     * 
     * @param hotelLocalizacaoFiltro
     * @return
     *     returns org.datacontract.schemas._2004._07.ftv_hotel_business.ArrayOfHotelLocalizacao
     */
    @WebMethod(operationName = "ConsultarLocalizacao", action = "http://tempuri.org/IVenda/ConsultarLocalizacao")
    @WebResult(name = "ConsultarLocalizacaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarLocalizacao", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarLocalizacao")
    @ResponseWrapper(localName = "ConsultarLocalizacaoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarLocalizacaoResponse")
    public ArrayOfHotelLocalizacao consultarLocalizacao(
        @WebParam(name = "hotelLocalizacaoFiltro", targetNamespace = "http://tempuri.org/")
        HotelLocalizacaoFiltro hotelLocalizacaoFiltro);

    /**
     * 
     * @param reservaParametro
     * @return
     *     returns org.datacontract.schemas._2004._07.ftv_hotel_business.ReservaRetorno
     */
    @WebMethod(operationName = "ReservarHotel", action = "http://tempuri.org/IVenda/ReservarHotel")
    @WebResult(name = "ReservarHotelResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ReservarHotel", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReservarHotel")
    @ResponseWrapper(localName = "ReservarHotelResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReservarHotelResponse")
    public ReservaRetorno reservarHotel(
        @WebParam(name = "reservaParametro", targetNamespace = "http://tempuri.org/")
        ReservaParametro reservaParametro);

    /**
     * 
     * @param cancelamentoParametro
     * @return
     *     returns org.datacontract.schemas._2004._07.ftv_hotel_business.CancelamentoRetorno
     */
    @WebMethod(operationName = "Cancelar", action = "http://tempuri.org/IVenda/Cancelar")
    @WebResult(name = "CancelarResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Cancelar", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Cancelar")
    @ResponseWrapper(localName = "CancelarResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelarResponse")
    public CancelamentoRetorno cancelar(
        @WebParam(name = "cancelamentoParametro", targetNamespace = "http://tempuri.org/")
        CancelamentoParametro cancelamentoParametro);

    /**
     * 
     * @param atualizacao
     * @return
     *     returns org.datacontract.schemas._2004._07.ftv_hotel_business.Atualizacao
     */
    @WebMethod(operationName = "AtualizarStatusReservaIntegracao", action = "http://tempuri.org/IVenda/AtualizarStatusReservaIntegracao")
    @WebResult(name = "AtualizarStatusReservaIntegracaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AtualizarStatusReservaIntegracao", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AtualizarStatusReservaIntegracao")
    @ResponseWrapper(localName = "AtualizarStatusReservaIntegracaoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AtualizarStatusReservaIntegracaoResponse")
    public Atualizacao atualizarStatusReservaIntegracao(
        @WebParam(name = "atualizacao", targetNamespace = "http://tempuri.org/")
        Atualizacao atualizacao);

    /**
     * 
     * @param atualizacao
     * @return
     *     returns org.datacontract.schemas._2004._07.ftv_hotel_business.Atualizacao
     */
    @WebMethod(operationName = "ImportarReservaExterna", action = "http://tempuri.org/IVenda/ImportarReservaExterna")
    @WebResult(name = "ImportarReservaExternaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ImportarReservaExterna", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ImportarReservaExterna")
    @ResponseWrapper(localName = "ImportarReservaExternaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ImportarReservaExternaResponse")
    public Atualizacao importarReservaExterna(
        @WebParam(name = "atualizacao", targetNamespace = "http://tempuri.org/")
        Atualizacao atualizacao);

    /**
     * 
     * @param hotelDestaque
     * @return
     *     returns org.datacontract.schemas._2004._07.ftv_hotel_business.ArrayOfHotelDestaque
     */
    @WebMethod(operationName = "ConsultarHotelDestaque", action = "http://tempuri.org/IVenda/ConsultarHotelDestaque")
    @WebResult(name = "ConsultarHotelDestaqueResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarHotelDestaque", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarHotelDestaque")
    @ResponseWrapper(localName = "ConsultarHotelDestaqueResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarHotelDestaqueResponse")
    public ArrayOfHotelDestaque consultarHotelDestaque(
        @WebParam(name = "hotelDestaque", targetNamespace = "http://tempuri.org/")
        HotelDestaque hotelDestaque);

}
