
package com.postini.pstn.soapapi.v2.automatedbatch;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AutomatedBatchService", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", wsdlLocation = "META-INF/wsdl/automatedbatch.wsdl")
public class AutomatedBatchService
    extends Service
{

    private final static URL AUTOMATEDBATCHSERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTOMATEDBATCHSERVICE_EXCEPTION;
    private final static QName AUTOMATEDBATCHSERVICE_QNAME = new QName("http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "AutomatedBatchService");

    static {
        AUTOMATEDBATCHSERVICE_WSDL_LOCATION = com.postini.pstn.soapapi.v2.automatedbatch.AutomatedBatchService.class.getClassLoader().getResource("META-INF/wsdl/automatedbatch.wsdl");
        WebServiceException e = null;
        if (AUTOMATEDBATCHSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/automatedbatch.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        AUTOMATEDBATCHSERVICE_EXCEPTION = e;
    }

    public AutomatedBatchService() {
        super(__getWsdlLocation(), AUTOMATEDBATCHSERVICE_QNAME);
    }

    public AutomatedBatchService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTOMATEDBATCHSERVICE_QNAME, features);
    }

    public AutomatedBatchService(URL wsdlLocation) {
        super(wsdlLocation, AUTOMATEDBATCHSERVICE_QNAME);
    }

    public AutomatedBatchService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTOMATEDBATCHSERVICE_QNAME, features);
    }

    public AutomatedBatchService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutomatedBatchService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AutomatedBatchPort
     */
    @WebEndpoint(name = "AutomatedBatchPort")
    public AutomatedBatchPort getAutomatedBatchPort() {
        return super.getPort(new QName("http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "AutomatedBatchPort"), AutomatedBatchPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutomatedBatchPort
     */
    @WebEndpoint(name = "AutomatedBatchPort")
    public AutomatedBatchPort getAutomatedBatchPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "AutomatedBatchPort"), AutomatedBatchPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTOMATEDBATCHSERVICE_EXCEPTION!= null) {
            throw AUTOMATEDBATCHSERVICE_EXCEPTION;
        }
        return AUTOMATEDBATCHSERVICE_WSDL_LOCATION;
    }

}
