
package com.postini.pstn.soapapi.v2.automatedbatch;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AutomatedBatchPort", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AutomatedBatchPort {


    /**
     * Performs simple connection level round-trip testing.
     * 
     * @param shouldWork
     * @return
     *     returns java.lang.String
     * @throws MalformedKeyException_Exception
     * @throws InvalidValueException_Exception
     * @throws InternalException_Exception
     * @throws NoSuchKeyException_Exception
     * @throws UnknownInternalException_Exception
     * @throws AuthenticationException_Exception
     * @throws MissingElementException_Exception
     * @throws BatchException_Exception
     * @throws StatusException_Exception
     * @throws AdminBlockException_Exception
     */
    @WebMethod
    @WebResult(name = "confirmation_message", targetNamespace = "")
    @RequestWrapper(localName = "test", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.Test")
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.TestResponse")
    public String test(
        @WebParam(name = "should_work", targetNamespace = "")
        boolean shouldWork)
        throws AdminBlockException_Exception, AuthenticationException_Exception, BatchException_Exception, InternalException_Exception, InvalidValueException_Exception, MalformedKeyException_Exception, MissingElementException_Exception, NoSuchKeyException_Exception, StatusException_Exception, UnknownInternalException_Exception
    ;

    /**
     * Verifies the specified authentication credentials without the need to call another operation.
     * 
     * @param authElem
     * @throws MalformedKeyException_Exception
     * @throws InternalException_Exception
     * @throws InvalidValueException_Exception
     * @throws NoSuchKeyException_Exception
     * @throws UnknownInternalException_Exception
     * @throws AuthenticationException_Exception
     * @throws BatchException_Exception
     * @throws MissingElementException_Exception
     * @throws AdminBlockException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "checkauth", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.Checkauth")
    @ResponseWrapper(localName = "checkauthResponse", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.CheckauthResponse")
    public void checkauth(
        @WebParam(name = "authElem", targetNamespace = "")
        AuthElem authElem)
        throws AdminBlockException_Exception, AuthenticationException_Exception, BatchException_Exception, InternalException_Exception, InvalidValueException_Exception, MalformedKeyException_Exception, MissingElementException_Exception, NoSuchKeyException_Exception, UnknownInternalException_Exception
    ;

    /**
     * Add a user alias
     * 
     * @param authElem
     * @param confirm
     * @param userAddressOrId
     * @param aliasAddress
     * @throws MalformedKeyException_Exception
     * @throws InvalidValueException_Exception
     * @throws InternalException_Exception
     * @throws NoSuchKeyException_Exception
     * @throws UnknownInternalException_Exception
     * @throws AuthenticationException_Exception
     * @throws BatchException_Exception
     * @throws MissingElementException_Exception
     * @throws AdminBlockException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addalias", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.Addalias")
    @ResponseWrapper(localName = "addaliasResponse", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.AddaliasResponse")
    public void addalias(
        @WebParam(name = "authElem", targetNamespace = "")
        AuthElem authElem,
        @WebParam(name = "userAddressOrId", targetNamespace = "")
        String userAddressOrId,
        @WebParam(name = "aliasAddress", targetNamespace = "")
        String aliasAddress,
        @WebParam(name = "confirm", targetNamespace = "")
        String confirm)
        throws AdminBlockException_Exception, AuthenticationException_Exception, BatchException_Exception, InternalException_Exception, InvalidValueException_Exception, MalformedKeyException_Exception, MissingElementException_Exception, NoSuchKeyException_Exception, UnknownInternalException_Exception
    ;

    /**
     * Add a domain
     * 
     * @param authElem
     * @param args
     * @param orgNameOrId
     * @throws MalformedKeyException_Exception
     * @throws InternalException_Exception
     * @throws InvalidValueException_Exception
     * @throws NoSuchKeyException_Exception
     * @throws UnknownInternalException_Exception
     * @throws AuthenticationException_Exception
     * @throws MissingElementException_Exception
     * @throws BatchException_Exception
     * @throws AdminBlockException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "adddomain", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.Adddomain")
    @ResponseWrapper(localName = "adddomainResponse", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.AdddomainResponse")
    public void adddomain(
        @WebParam(name = "authElem", targetNamespace = "")
        AuthElem authElem,
        @WebParam(name = "orgNameOrId", targetNamespace = "")
        String orgNameOrId,
        @WebParam(name = "args", targetNamespace = "")
        Adddomainargs args)
        throws AdminBlockException_Exception, AuthenticationException_Exception, BatchException_Exception, InternalException_Exception, InvalidValueException_Exception, MalformedKeyException_Exception, MissingElementException_Exception, NoSuchKeyException_Exception, UnknownInternalException_Exception
    ;

    /**
     * Add a org
     * 
     * @param authElem
     * @param args
     * @param orgName
     * @throws MalformedKeyException_Exception
     * @throws InvalidValueException_Exception
     * @throws InternalException_Exception
     * @throws NoSuchKeyException_Exception
     * @throws UnknownInternalException_Exception
     * @throws AuthenticationException_Exception
     * @throws BatchException_Exception
     * @throws MissingElementException_Exception
     * @throws AdminBlockException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addorg", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.Addorg")
    @ResponseWrapper(localName = "addorgResponse", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.AddorgResponse")
    public void addorg(
        @WebParam(name = "authElem", targetNamespace = "")
        AuthElem authElem,
        @WebParam(name = "orgName", targetNamespace = "")
        String orgName,
        @WebParam(name = "args", targetNamespace = "")
        Addorgargs args)
        throws AdminBlockException_Exception, AuthenticationException_Exception, BatchException_Exception, InternalException_Exception, InvalidValueException_Exception, MalformedKeyException_Exception, MissingElementException_Exception, NoSuchKeyException_Exception, UnknownInternalException_Exception
    ;

    /**
     * Add a user
     * 
     * @param authElem
     * @param userAddress
     * @param args
     * @throws MalformedKeyException_Exception
     * @throws InternalException_Exception
     * @throws InvalidValueException_Exception
     * @throws NoSuchKeyException_Exception
     * @throws UnknownInternalException_Exception
     * @throws AuthenticationException_Exception
     * @throws BatchException_Exception
     * @throws MissingElementException_Exception
     * @throws AdminBlockException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "adduser", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.Adduser")
    @ResponseWrapper(localName = "adduserResponse", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.AdduserResponse")
    public void adduser(
        @WebParam(name = "authElem", targetNamespace = "")
        AuthElem authElem,
        @WebParam(name = "userAddress", targetNamespace = "")
        String userAddress,
        @WebParam(name = "args", targetNamespace = "")
        Adduserargs args)
        throws AdminBlockException_Exception, AuthenticationException_Exception, BatchException_Exception, InternalException_Exception, InvalidValueException_Exception, MalformedKeyException_Exception, MissingElementException_Exception, NoSuchKeyException_Exception, UnknownInternalException_Exception
    ;

    /**
     * Delete a user alias
     * 
     * @param authElem
     * @param aliasAddress
     * @throws MalformedKeyException_Exception
     * @throws InternalException_Exception
     * @throws InvalidValueException_Exception
     * @throws NoSuchKeyException_Exception
     * @throws UnknownInternalException_Exception
     * @throws AuthenticationException_Exception
     * @throws BatchException_Exception
     * @throws MissingElementException_Exception
     * @throws AdminBlockException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deletealias", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.Deletealias")
    @ResponseWrapper(localName = "deletealiasResponse", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.DeletealiasResponse")
    public void deletealias(
        @WebParam(name = "authElem", targetNamespace = "")
        AuthElem authElem,
        @WebParam(name = "aliasAddress", targetNamespace = "")
        String aliasAddress)
        throws AdminBlockException_Exception, AuthenticationException_Exception, BatchException_Exception, InternalException_Exception, InvalidValueException_Exception, MalformedKeyException_Exception, MissingElementException_Exception, NoSuchKeyException_Exception, UnknownInternalException_Exception
    ;

    /**
     * Delete a domain
     * 
     * @param authElem
     * @param domainNameOrId
     * @throws MalformedKeyException_Exception
     * @throws InternalException_Exception
     * @throws InvalidValueException_Exception
     * @throws NoSuchKeyException_Exception
     * @throws UnknownInternalException_Exception
     * @throws AuthenticationException_Exception
     * @throws MissingElementException_Exception
     * @throws BatchException_Exception
     * @throws AdminBlockException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deletedomain", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.Deletedomain")
    @ResponseWrapper(localName = "deletedomainResponse", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.DeletedomainResponse")
    public void deletedomain(
        @WebParam(name = "authElem", targetNamespace = "")
        AuthElem authElem,
        @WebParam(name = "domainNameOrId", targetNamespace = "")
        String domainNameOrId)
        throws AdminBlockException_Exception, AuthenticationException_Exception, BatchException_Exception, InternalException_Exception, InvalidValueException_Exception, MalformedKeyException_Exception, MissingElementException_Exception, NoSuchKeyException_Exception, UnknownInternalException_Exception
    ;

    /**
     * Delete a org
     * 
     * @param authElem
     * @param orgNameOrId
     * @throws MalformedKeyException_Exception
     * @throws InvalidValueException_Exception
     * @throws InternalException_Exception
     * @throws NoSuchKeyException_Exception
     * @throws UnknownInternalException_Exception
     * @throws AuthenticationException_Exception
     * @throws BatchException_Exception
     * @throws MissingElementException_Exception
     * @throws AdminBlockException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteorg", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.Deleteorg")
    @ResponseWrapper(localName = "deleteorgResponse", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.DeleteorgResponse")
    public void deleteorg(
        @WebParam(name = "authElem", targetNamespace = "")
        AuthElem authElem,
        @WebParam(name = "orgNameOrId", targetNamespace = "")
        String orgNameOrId)
        throws AdminBlockException_Exception, AuthenticationException_Exception, BatchException_Exception, InternalException_Exception, InvalidValueException_Exception, MalformedKeyException_Exception, MissingElementException_Exception, NoSuchKeyException_Exception, UnknownInternalException_Exception
    ;

    /**
     * Delete a user
     * 
     * @param authElem
     * @param userAddressOrId
     * @throws MalformedKeyException_Exception
     * @throws InternalException_Exception
     * @throws InvalidValueException_Exception
     * @throws NoSuchKeyException_Exception
     * @throws UnknownInternalException_Exception
     * @throws AuthenticationException_Exception
     * @throws MissingElementException_Exception
     * @throws BatchException_Exception
     * @throws AdminBlockException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteuser", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.Deleteuser")
    @ResponseWrapper(localName = "deleteuserResponse", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.DeleteuserResponse")
    public void deleteuser(
        @WebParam(name = "authElem", targetNamespace = "")
        AuthElem authElem,
        @WebParam(name = "userAddressOrId", targetNamespace = "")
        String userAddressOrId)
        throws AdminBlockException_Exception, AuthenticationException_Exception, BatchException_Exception, InternalException_Exception, InvalidValueException_Exception, MalformedKeyException_Exception, MissingElementException_Exception, NoSuchKeyException_Exception, UnknownInternalException_Exception
    ;

    /**
     * Display domain information
     * 
     * @param authElem
     * @param domainNameOrId
     * @return
     *     returns com.postini.pstn.soapapi.v2.automatedbatch.DomainRecord
     * @throws MalformedKeyException_Exception
     * @throws InvalidValueException_Exception
     * @throws InternalException_Exception
     * @throws NoSuchKeyException_Exception
     * @throws UnknownInternalException_Exception
     * @throws AuthenticationException_Exception
     * @throws MissingElementException_Exception
     * @throws BatchException_Exception
     * @throws AdminBlockException_Exception
     */
    @WebMethod
    @WebResult(name = "domainRecord", targetNamespace = "")
    @RequestWrapper(localName = "displaydomain", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.Displaydomain")
    @ResponseWrapper(localName = "displaydomainResponse", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.DisplaydomainResponse")
    public DomainRecord displaydomain(
        @WebParam(name = "authElem", targetNamespace = "")
        AuthElem authElem,
        @WebParam(name = "domainNameOrId", targetNamespace = "")
        String domainNameOrId)
        throws AdminBlockException_Exception, AuthenticationException_Exception, BatchException_Exception, InternalException_Exception, InvalidValueException_Exception, MalformedKeyException_Exception, MissingElementException_Exception, NoSuchKeyException_Exception, UnknownInternalException_Exception
    ;

    /**
     * Display org information
     * 
     * @param authElem
     * @param orgNameOrId
     * @return
     *     returns com.postini.pstn.soapapi.v2.automatedbatch.OrgRecord
     * @throws MalformedKeyException_Exception
     * @throws InternalException_Exception
     * @throws InvalidValueException_Exception
     * @throws NoSuchKeyException_Exception
     * @throws UnknownInternalException_Exception
     * @throws AuthenticationException_Exception
     * @throws BatchException_Exception
     * @throws MissingElementException_Exception
     * @throws AdminBlockException_Exception
     */
    @WebMethod
    @WebResult(name = "orgRecord", targetNamespace = "")
    @RequestWrapper(localName = "displayorg", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.Displayorg")
    @ResponseWrapper(localName = "displayorgResponse", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.DisplayorgResponse")
    public OrgRecord displayorg(
        @WebParam(name = "authElem", targetNamespace = "")
        AuthElem authElem,
        @WebParam(name = "orgNameOrId", targetNamespace = "")
        String orgNameOrId)
        throws AdminBlockException_Exception, AuthenticationException_Exception, BatchException_Exception, InternalException_Exception, InvalidValueException_Exception, MalformedKeyException_Exception, MissingElementException_Exception, NoSuchKeyException_Exception, UnknownInternalException_Exception
    ;

    /**
     * Display email org spooling information
     * 
     * @param authElem
     * @param emailOrgNameOrId
     * @return
     *     returns com.postini.pstn.soapapi.v2.automatedbatch.SpoolRecord
     * @throws MalformedKeyException_Exception
     * @throws InvalidValueException_Exception
     * @throws InternalException_Exception
     * @throws NoSuchKeyException_Exception
     * @throws UnknownInternalException_Exception
     * @throws AuthenticationException_Exception
     * @throws MissingElementException_Exception
     * @throws BatchException_Exception
     * @throws AdminBlockException_Exception
     */
    @WebMethod
    @WebResult(name = "spoolRecord", targetNamespace = "")
    @RequestWrapper(localName = "displayspool", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.Displayspool")
    @ResponseWrapper(localName = "displayspoolResponse", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.DisplayspoolResponse")
    public SpoolRecord displayspool(
        @WebParam(name = "authElem", targetNamespace = "")
        AuthElem authElem,
        @WebParam(name = "emailOrgNameOrId", targetNamespace = "")
        String emailOrgNameOrId)
        throws AdminBlockException_Exception, AuthenticationException_Exception, BatchException_Exception, InternalException_Exception, InvalidValueException_Exception, MalformedKeyException_Exception, MissingElementException_Exception, NoSuchKeyException_Exception, UnknownInternalException_Exception
    ;

    /**
     * Display user information
     * 
     * @param authElem
     * @param userAddressOrId
     * @return
     *     returns com.postini.pstn.soapapi.v2.automatedbatch.UserRecord
     * @throws MalformedKeyException_Exception
     * @throws InvalidValueException_Exception
     * @throws InternalException_Exception
     * @throws NoSuchKeyException_Exception
     * @throws UnknownInternalException_Exception
     * @throws AuthenticationException_Exception
     * @throws BatchException_Exception
     * @throws MissingElementException_Exception
     * @throws AdminBlockException_Exception
     */
    @WebMethod
    @WebResult(name = "userRecord", targetNamespace = "")
    @RequestWrapper(localName = "displayuser", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.Displayuser")
    @ResponseWrapper(localName = "displayuserResponse", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.DisplayuserResponse")
    public UserRecord displayuser(
        @WebParam(name = "authElem", targetNamespace = "")
        AuthElem authElem,
        @WebParam(name = "userAddressOrId", targetNamespace = "")
        String userAddressOrId)
        throws AdminBlockException_Exception, AuthenticationException_Exception, BatchException_Exception, InternalException_Exception, InvalidValueException_Exception, MalformedKeyException_Exception, MissingElementException_Exception, NoSuchKeyException_Exception, UnknownInternalException_Exception
    ;

    /**
     * Get org report
     * 
     * @param authElem
     * @param args
     * @param orgNameOrId
     * @return
     *     returns java.util.List<com.postini.pstn.soapapi.v2.automatedbatch.OrgReportRecord>
     * @throws MalformedKeyException_Exception
     * @throws InvalidValueException_Exception
     * @throws InternalException_Exception
     * @throws NoSuchKeyException_Exception
     * @throws UnknownInternalException_Exception
     * @throws AuthenticationException_Exception
     * @throws MissingElementException_Exception
     * @throws BatchException_Exception
     * @throws AdminBlockException_Exception
     */
    @WebMethod
    @WebResult(name = "report", targetNamespace = "")
    @RequestWrapper(localName = "getorgreport", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.Getorgreport")
    @ResponseWrapper(localName = "getorgreportResponse", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.GetorgreportResponse")
    public List<OrgReportRecord> getorgreport(
        @WebParam(name = "authElem", targetNamespace = "")
        AuthElem authElem,
        @WebParam(name = "orgNameOrId", targetNamespace = "")
        String orgNameOrId,
        @WebParam(name = "args", targetNamespace = "")
        Getorgreportargs args)
        throws AdminBlockException_Exception, AuthenticationException_Exception, BatchException_Exception, InternalException_Exception, InvalidValueException_Exception, MalformedKeyException_Exception, MissingElementException_Exception, NoSuchKeyException_Exception, UnknownInternalException_Exception
    ;

    /**
     * List domain information
     * 
     * @param authElem
     * @param queryParams
     * @param queryString
     * @return
     *     returns java.util.List<com.postini.pstn.soapapi.v2.automatedbatch.DomainRecord>
     * @throws MalformedKeyException_Exception
     * @throws InternalException_Exception
     * @throws InvalidValueException_Exception
     * @throws NoSuchKeyException_Exception
     * @throws UnknownInternalException_Exception
     * @throws AuthenticationException_Exception
     * @throws BatchException_Exception
     * @throws MissingElementException_Exception
     * @throws AdminBlockException_Exception
     */
    @WebMethod
    @WebResult(name = "domain", targetNamespace = "")
    @RequestWrapper(localName = "listdomains", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.Listdomains")
    @ResponseWrapper(localName = "listdomainsResponse", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.ListdomainsResponse")
    public List<DomainRecord> listdomains(
        @WebParam(name = "authElem", targetNamespace = "")
        AuthElem authElem,
        @WebParam(name = "queryString", targetNamespace = "")
        String queryString,
        @WebParam(name = "queryParams", targetNamespace = "")
        ListdomainsqueryParams queryParams)
        throws AdminBlockException_Exception, AuthenticationException_Exception, BatchException_Exception, InternalException_Exception, InvalidValueException_Exception, MalformedKeyException_Exception, MissingElementException_Exception, NoSuchKeyException_Exception, UnknownInternalException_Exception
    ;

    /**
     * List org information
     * 
     * @param authElem
     * @param queryParams
     * @param queryString
     * @return
     *     returns java.util.List<com.postini.pstn.soapapi.v2.automatedbatch.OrgRecord>
     * @throws MalformedKeyException_Exception
     * @throws InvalidValueException_Exception
     * @throws InternalException_Exception
     * @throws NoSuchKeyException_Exception
     * @throws UnknownInternalException_Exception
     * @throws AuthenticationException_Exception
     * @throws MissingElementException_Exception
     * @throws BatchException_Exception
     * @throws AdminBlockException_Exception
     */
    @WebMethod
    @WebResult(name = "org", targetNamespace = "")
    @RequestWrapper(localName = "listorgs", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.Listorgs")
    @ResponseWrapper(localName = "listorgsResponse", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.ListorgsResponse")
    public List<OrgRecord> listorgs(
        @WebParam(name = "authElem", targetNamespace = "")
        AuthElem authElem,
        @WebParam(name = "queryString", targetNamespace = "")
        String queryString,
        @WebParam(name = "queryParams", targetNamespace = "")
        ListorgsqueryParams queryParams)
        throws AdminBlockException_Exception, AuthenticationException_Exception, BatchException_Exception, InternalException_Exception, InvalidValueException_Exception, MalformedKeyException_Exception, MissingElementException_Exception, NoSuchKeyException_Exception, UnknownInternalException_Exception
    ;

    /**
     * Retrieve a list of users meeting arbitary criteria
     * 
     * @param authElem
     * @param queryParams
     * @param queryString
     * @return
     *     returns java.util.List<com.postini.pstn.soapapi.v2.automatedbatch.UserRecord>
     * @throws MalformedKeyException_Exception
     * @throws InternalException_Exception
     * @throws InvalidValueException_Exception
     * @throws NoSuchKeyException_Exception
     * @throws UnknownInternalException_Exception
     * @throws AuthenticationException_Exception
     * @throws BatchException_Exception
     * @throws MissingElementException_Exception
     * @throws AdminBlockException_Exception
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "listusers", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.Listusers")
    @ResponseWrapper(localName = "listusersResponse", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.ListusersResponse")
    public List<UserRecord> listusers(
        @WebParam(name = "authElem", targetNamespace = "")
        AuthElem authElem,
        @WebParam(name = "queryString", targetNamespace = "")
        String queryString,
        @WebParam(name = "queryParams", targetNamespace = "")
        ListusersqueryParams queryParams)
        throws AdminBlockException_Exception, AuthenticationException_Exception, BatchException_Exception, InternalException_Exception, InvalidValueException_Exception, MalformedKeyException_Exception, MissingElementException_Exception, NoSuchKeyException_Exception, UnknownInternalException_Exception
    ;

    /**
     * Modify domain information
     * 
     * @param authElem
     * @param domainModifications
     * @param domainNameOrId
     * @throws MalformedKeyException_Exception
     * @throws InternalException_Exception
     * @throws InvalidValueException_Exception
     * @throws NoSuchKeyException_Exception
     * @throws UnknownInternalException_Exception
     * @throws AuthenticationException_Exception
     * @throws BatchException_Exception
     * @throws MissingElementException_Exception
     * @throws AdminBlockException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "modifydomain", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.Modifydomain")
    @ResponseWrapper(localName = "modifydomainResponse", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.ModifydomainResponse")
    public void modifydomain(
        @WebParam(name = "authElem", targetNamespace = "")
        AuthElem authElem,
        @WebParam(name = "domainNameOrId", targetNamespace = "")
        String domainNameOrId,
        @WebParam(name = "domainModifications", targetNamespace = "")
        DomainRecord domainModifications)
        throws AdminBlockException_Exception, AuthenticationException_Exception, BatchException_Exception, InternalException_Exception, InvalidValueException_Exception, MalformedKeyException_Exception, MissingElementException_Exception, NoSuchKeyException_Exception, UnknownInternalException_Exception
    ;

    /**
     * Modify org information
     * 
     * @param authElem
     * @param orgModifications
     * @param orgNameOrId
     * @throws MalformedKeyException_Exception
     * @throws InvalidValueException_Exception
     * @throws InternalException_Exception
     * @throws NoSuchKeyException_Exception
     * @throws UnknownInternalException_Exception
     * @throws AuthenticationException_Exception
     * @throws BatchException_Exception
     * @throws MissingElementException_Exception
     * @throws AdminBlockException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "modifyorg", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.Modifyorg")
    @ResponseWrapper(localName = "modifyorgResponse", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.ModifyorgResponse")
    public void modifyorg(
        @WebParam(name = "authElem", targetNamespace = "")
        AuthElem authElem,
        @WebParam(name = "orgNameOrId", targetNamespace = "")
        String orgNameOrId,
        @WebParam(name = "orgModifications", targetNamespace = "")
        OrgRecord orgModifications)
        throws AdminBlockException_Exception, AuthenticationException_Exception, BatchException_Exception, InternalException_Exception, InvalidValueException_Exception, MalformedKeyException_Exception, MissingElementException_Exception, NoSuchKeyException_Exception, UnknownInternalException_Exception
    ;

    /**
     * Modify user information
     * 
     * @param authElem
     * @param userAddressOrId
     * @param userModifications
     * @throws MalformedKeyException_Exception
     * @throws InternalException_Exception
     * @throws InvalidValueException_Exception
     * @throws NoSuchKeyException_Exception
     * @throws UnknownInternalException_Exception
     * @throws AuthenticationException_Exception
     * @throws BatchException_Exception
     * @throws MissingElementException_Exception
     * @throws AdminBlockException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "modifyuser", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.Modifyuser")
    @ResponseWrapper(localName = "modifyuserResponse", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.ModifyuserResponse")
    public void modifyuser(
        @WebParam(name = "authElem", targetNamespace = "")
        AuthElem authElem,
        @WebParam(name = "userAddressOrId", targetNamespace = "")
        String userAddressOrId,
        @WebParam(name = "userModifications", targetNamespace = "")
        UserRecord userModifications)
        throws AdminBlockException_Exception, AuthenticationException_Exception, BatchException_Exception, InternalException_Exception, InvalidValueException_Exception, MalformedKeyException_Exception, MissingElementException_Exception, NoSuchKeyException_Exception, UnknownInternalException_Exception
    ;

    /**
     * Suspend a user
     * 
     * @param authElem
     * @param userAddressOrId
     * @param optArgStr1
     * @param optArgStr3
     * @param optArgStr2
     * @throws MalformedKeyException_Exception
     * @throws InvalidValueException_Exception
     * @throws InternalException_Exception
     * @throws NoSuchKeyException_Exception
     * @throws UnknownInternalException_Exception
     * @throws AuthenticationException_Exception
     * @throws MissingElementException_Exception
     * @throws BatchException_Exception
     * @throws AdminBlockException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "suspenduser", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.Suspenduser")
    @ResponseWrapper(localName = "suspenduserResponse", targetNamespace = "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", className = "com.postini.pstn.soapapi.v2.automatedbatch.SuspenduserResponse")
    public void suspenduser(
        @WebParam(name = "authElem", targetNamespace = "")
        AuthElem authElem,
        @WebParam(name = "userAddressOrId", targetNamespace = "")
        String userAddressOrId,
        @WebParam(name = "optArgStr1", targetNamespace = "")
        String optArgStr1,
        @WebParam(name = "optArgStr2", targetNamespace = "")
        String optArgStr2,
        @WebParam(name = "optArgStr3", targetNamespace = "")
        String optArgStr3)
        throws AdminBlockException_Exception, AuthenticationException_Exception, BatchException_Exception, InternalException_Exception, InvalidValueException_Exception, MalformedKeyException_Exception, MissingElementException_Exception, NoSuchKeyException_Exception, UnknownInternalException_Exception
    ;

}
