
package elguille.webservices;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Conversor de grados Fahrenheit a grados centígrados (Celsius)
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Conversor", targetNamespace = "http://elGuille/WebServices", wsdlLocation = "META-INF/wsdl/Conversor.wsdl")
public class Conversor
    extends Service
{

    private final static URL CONVERSOR_WSDL_LOCATION;
    private final static WebServiceException CONVERSOR_EXCEPTION;
    private final static QName CONVERSOR_QNAME = new QName("http://elGuille/WebServices", "Conversor");

    static {
        CONVERSOR_WSDL_LOCATION = elguille.webservices.Conversor.class.getClassLoader().getResource("META-INF/wsdl/Conversor.wsdl");
        WebServiceException e = null;
        if (CONVERSOR_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/Conversor.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CONVERSOR_EXCEPTION = e;
    }

    public Conversor() {
        super(__getWsdlLocation(), CONVERSOR_QNAME);
    }

    public Conversor(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONVERSOR_QNAME, features);
    }

    public Conversor(URL wsdlLocation) {
        super(wsdlLocation, CONVERSOR_QNAME);
    }

    public Conversor(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONVERSOR_QNAME, features);
    }

    public Conversor(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Conversor(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConversorSoap
     */
    @WebEndpoint(name = "ConversorSoap")
    public ConversorSoap getConversorSoap() {
        return super.getPort(new QName("http://elGuille/WebServices", "ConversorSoap"), ConversorSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConversorSoap
     */
    @WebEndpoint(name = "ConversorSoap")
    public ConversorSoap getConversorSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://elGuille/WebServices", "ConversorSoap"), ConversorSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONVERSOR_EXCEPTION!= null) {
            throw CONVERSOR_EXCEPTION;
        }
        return CONVERSOR_WSDL_LOCATION;
    }

}
