
package com.unisys.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WeatherServicesSoap", targetNamespace = "http://www.unisys.com/WebServices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WeatherServicesSoap {


    /**
     * This method retrieves the weather forecast given a zip code.
     * 
     * @param zipCode
     * @return
     *     returns com.unisys.webservices.WeatherForecast
     */
    @WebMethod(operationName = "GetWeather", action = "http://www.unisys.com/WebServices/GetWeather")
    @WebResult(name = "GetWeatherResult", targetNamespace = "http://www.unisys.com/WebServices/")
    @RequestWrapper(localName = "GetWeather", targetNamespace = "http://www.unisys.com/WebServices/", className = "com.unisys.webservices.GetWeather")
    @ResponseWrapper(localName = "GetWeatherResponse", targetNamespace = "http://www.unisys.com/WebServices/", className = "com.unisys.webservices.GetWeatherResponse")
    public WeatherForecast getWeather(
        @WebParam(name = "ZipCode", targetNamespace = "http://www.unisys.com/WebServices/")
        String zipCode);

    /**
     * This method retrieves the weather forecast as a string given a zip code.
     * 
     * @param zipCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetWeatherText", action = "http://www.unisys.com/WebServices/GetWeatherText")
    @WebResult(name = "GetWeatherTextResult", targetNamespace = "http://www.unisys.com/WebServices/")
    @RequestWrapper(localName = "GetWeatherText", targetNamespace = "http://www.unisys.com/WebServices/", className = "com.unisys.webservices.GetWeatherText")
    @ResponseWrapper(localName = "GetWeatherTextResponse", targetNamespace = "http://www.unisys.com/WebServices/", className = "com.unisys.webservices.GetWeatherTextResponse")
    public String getWeatherText(
        @WebParam(name = "ZipCode", targetNamespace = "http://www.unisys.com/WebServices/")
        String zipCode);

}
