
package com.epnet.webservices.searchservice._2007._07;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.epnet.webservices.searchservice.response._2007._07.EPServicesEITAuthoritySearchResponse;
import com.epnet.webservices.searchservice.response._2007._07.EPServicesEITBrowseResponse;
import com.epnet.webservices.searchservice.response._2007._07.EPServicesEITClusterResponse;
import com.epnet.webservices.searchservice.response._2007._07.EPServicesEITInfoResponse;
import com.epnet.webservices.searchservice.response._2007._07.EPServicesEITSearchResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SearchServiceSoap", targetNamespace = "http://epnet.com/webservices/SearchService/2007/07/")
@XmlSeeAlso({
    com.epnet.webservices.searchservice.response._2007._07.ObjectFactory.class,
    com.epnet.webservices.searchservice._2007._07.ObjectFactory.class
})
public interface SearchServiceSoap {


    /**
     * The Info method allows the Data Partner to receive a list of databases available to the given profile as well as the attributes of those databases and any attached authorities and their supported format types.
     * 
     * @param infoRequest
     * @return
     *     returns com.epnet.webservices.searchservice.response._2007._07.EPServicesEITInfoResponse
     */
    @WebMethod(operationName = "Info", action = "http://epnet.com/webservices/SearchService/2007/07/Info")
    @WebResult(name = "info", targetNamespace = "http://epnet.com/webservices/SearchService/2007/07/")
    @RequestWrapper(localName = "Info", targetNamespace = "http://epnet.com/webservices/SearchService/2007/07/", className = "com.epnet.webservices.searchservice._2007._07.Info")
    @ResponseWrapper(localName = "InfoResponse", targetNamespace = "http://epnet.com/webservices/SearchService/2007/07/", className = "com.epnet.webservices.searchservice._2007._07.InfoResponse")
    public EPServicesEITInfoResponse info(
        @WebParam(name = "infoRequest", targetNamespace = "http://epnet.com/webservices/SearchService/2007/07/")
        InfoRequest infoRequest);

    /**
     * The Browse method is used to view indexes such as Authors or Subject Terms on an EBSCOhost database.  Note that the index availability can be different per database.
     * 
     * @param browseRequest
     * @return
     *     returns com.epnet.webservices.searchservice.response._2007._07.EPServicesEITBrowseResponse
     */
    @WebMethod(operationName = "Browse", action = "http://epnet.com/webservices/SearchService/2007/07/Browse")
    @WebResult(name = "browseResponse", targetNamespace = "http://epnet.com/webservices/SearchService/2007/07/")
    @RequestWrapper(localName = "Browse", targetNamespace = "http://epnet.com/webservices/SearchService/2007/07/", className = "com.epnet.webservices.searchservice._2007._07.Browse")
    @ResponseWrapper(localName = "BrowseResponse", targetNamespace = "http://epnet.com/webservices/SearchService/2007/07/", className = "com.epnet.webservices.searchservice._2007._07.BrowseResponse")
    public EPServicesEITBrowseResponse browse(
        @WebParam(name = "browseRequest", targetNamespace = "http://epnet.com/webservices/SearchService/2007/07/")
        BrowseRequest browseRequest);

    /**
     * The Search method is used to perform basic searches on EBSCOhost reference system.  Abstracts as well as the full text for documents and articles can be retrieved using this method.  When available, full text articles can also be downloaded in pdf format.
     * 
     * @param searchRequest
     * @return
     *     returns com.epnet.webservices.searchservice.response._2007._07.EPServicesEITSearchResponse
     */
    @WebMethod(operationName = "Search", action = "http://epnet.com/webservices/SearchService/2007/07/Search")
    @WebResult(name = "searchResponse", targetNamespace = "http://epnet.com/webservices/SearchService/2007/07/")
    @RequestWrapper(localName = "Search", targetNamespace = "http://epnet.com/webservices/SearchService/2007/07/", className = "com.epnet.webservices.searchservice._2007._07.Search")
    @ResponseWrapper(localName = "SearchResponse", targetNamespace = "http://epnet.com/webservices/SearchService/2007/07/", className = "com.epnet.webservices.searchservice._2007._07.SearchResponse")
    public EPServicesEITSearchResponse search(
        @WebParam(name = "searchRequest", targetNamespace = "http://epnet.com/webservices/SearchService/2007/07/")
        SearchRequest searchRequest);

    /**
     * The AuthoritySearch method is used to perform authority searches on EBSCOhost reference system.
     * 
     * @param searchRequest
     * @return
     *     returns com.epnet.webservices.searchservice.response._2007._07.EPServicesEITAuthoritySearchResponse
     */
    @WebMethod(operationName = "AuthoritySearch", action = "http://epnet.com/webservices/SearchService/2007/07/AuthoritySearch")
    @WebResult(name = "AuthoritySearchResponse", targetNamespace = "http://epnet.com/webservices/SearchService/2007/07/")
    @RequestWrapper(localName = "AuthoritySearch", targetNamespace = "http://epnet.com/webservices/SearchService/2007/07/", className = "com.epnet.webservices.searchservice._2007._07.AuthoritySearch")
    @ResponseWrapper(localName = "AuthoritySearchResponse", targetNamespace = "http://epnet.com/webservices/SearchService/2007/07/", className = "com.epnet.webservices.searchservice._2007._07.AuthoritySearchResponse")
    public EPServicesEITAuthoritySearchResponse authoritySearch(
        @WebParam(name = "searchRequest", targetNamespace = "http://epnet.com/webservices/SearchService/2007/07/")
        AuthoritySearchRequest searchRequest);

    /**
     * Finds and returns the set of clusters that would be returned by the given search.
     * 
     * @param request
     * @return
     *     returns com.epnet.webservices.searchservice.response._2007._07.EPServicesEITClusterResponse
     */
    @WebMethod(operationName = "GetClusters", action = "http://epnet.com/webservices/SearchService/2007/07/GetClusters")
    @WebResult(name = "clusterResponse", targetNamespace = "http://epnet.com/webservices/SearchService/2007/07/")
    @RequestWrapper(localName = "GetClusters", targetNamespace = "http://epnet.com/webservices/SearchService/2007/07/", className = "com.epnet.webservices.searchservice._2007._07.GetClusters")
    @ResponseWrapper(localName = "GetClustersResponse", targetNamespace = "http://epnet.com/webservices/SearchService/2007/07/", className = "com.epnet.webservices.searchservice._2007._07.GetClustersResponse")
    public EPServicesEITClusterResponse getClusters(
        @WebParam(name = "request", targetNamespace = "http://epnet.com/webservices/SearchService/2007/07/")
        ClusterSearchRequest request);

}
