
package jp.ac.u_tokyo.h.dis.webservices;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * <b>\u75c5\u540d XML Web\u30b5\u30fc\u30d3\u30b9</b><br>
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ByomeiWS", targetNamespace = "http://www.dis.h.u-tokyo.ac.jp/webservices/", wsdlLocation = "META-INF/wsdl/ByomeiWS.wsdl")
public class ByomeiWS
    extends Service
{

    private final static URL BYOMEIWS_WSDL_LOCATION;
    private final static WebServiceException BYOMEIWS_EXCEPTION;
    private final static QName BYOMEIWS_QNAME = new QName("http://www.dis.h.u-tokyo.ac.jp/webservices/", "ByomeiWS");

    static {
        BYOMEIWS_WSDL_LOCATION = jp.ac.u_tokyo.h.dis.webservices.ByomeiWS.class.getClassLoader().getResource("META-INF/wsdl/ByomeiWS.wsdl");
        WebServiceException e = null;
        if (BYOMEIWS_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/ByomeiWS.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        BYOMEIWS_EXCEPTION = e;
    }

    public ByomeiWS() {
        super(__getWsdlLocation(), BYOMEIWS_QNAME);
    }

    public ByomeiWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), BYOMEIWS_QNAME, features);
    }

    public ByomeiWS(URL wsdlLocation) {
        super(wsdlLocation, BYOMEIWS_QNAME);
    }

    public ByomeiWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BYOMEIWS_QNAME, features);
    }

    public ByomeiWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ByomeiWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ByomeiWSSoap
     */
    @WebEndpoint(name = "ByomeiWSSoap")
    public ByomeiWSSoap getByomeiWSSoap() {
        return super.getPort(new QName("http://www.dis.h.u-tokyo.ac.jp/webservices/", "ByomeiWSSoap"), ByomeiWSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ByomeiWSSoap
     */
    @WebEndpoint(name = "ByomeiWSSoap")
    public ByomeiWSSoap getByomeiWSSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.dis.h.u-tokyo.ac.jp/webservices/", "ByomeiWSSoap"), ByomeiWSSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BYOMEIWS_EXCEPTION!= null) {
            throw BYOMEIWS_EXCEPTION;
        }
        return BYOMEIWS_WSDL_LOCATION;
    }

}
