
package org.opentravel.ota._2003._05;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OTA_HotelResSoap", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OTAHotelResSoap {


    /**
     * Creates and confirms a reservation.
     * 
     * @param otaHotelResRQ
     * @return
     *     returns org.opentravel.ota._2003._05.OTAHotelResRS
     */
    @WebMethod(operationName = "OTA_HotelResV2Service", action = "http://www.opentravel.org/OTA/2003/05/OTA_HotelResV2Service")
    @WebResult(name = "OTA_HotelResRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
    @RequestWrapper(localName = "OTA_HotelResV2Service", targetNamespace = "http://www.opentravel.org/OTA/2003/05", className = "org.opentravel.ota._2003._05.OTAHotelResV2Service")
    @ResponseWrapper(localName = "OTA_HotelResV2ServiceResponse", targetNamespace = "http://www.opentravel.org/OTA/2003/05", className = "org.opentravel.ota._2003._05.OTAHotelResV2ServiceResponse")
    public OTAHotelResRS otaHotelResV2Service(
        @WebParam(name = "OTA_HotelResRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        OTAHotelResRQ otaHotelResRQ);

}
