
package org.tempuri.dotnet.financeservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FinanceServiceSoap", targetNamespace = "http://tempuri.org/dotnet/FinanceService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FinanceServiceSoap {


    /**
     * Given Nominal  (annual) interest rate % and compounding periods per year, returns effective interest rate
     * 
     * @param compoundingPeriodsPerYear
     * @param nominalInterest
     * @return
     *     returns double
     */
    @WebMethod(operationName = "EffectiveInterest", action = "http://tempuri.org/dotnet/FinanceService/EffectiveInterest")
    @WebResult(name = "EffectiveInterestResult", targetNamespace = "http://tempuri.org/dotnet/FinanceService")
    @RequestWrapper(localName = "EffectiveInterest", targetNamespace = "http://tempuri.org/dotnet/FinanceService", className = "org.tempuri.dotnet.financeservice.EffectiveInterest")
    @ResponseWrapper(localName = "EffectiveInterestResponse", targetNamespace = "http://tempuri.org/dotnet/FinanceService", className = "org.tempuri.dotnet.financeservice.EffectiveInterestResponse")
    public double effectiveInterest(
        @WebParam(name = "NominalInterest", targetNamespace = "http://tempuri.org/dotnet/FinanceService")
        double nominalInterest,
        @WebParam(name = "CompoundingPeriodsPerYear", targetNamespace = "http://tempuri.org/dotnet/FinanceService")
        double compoundingPeriodsPerYear);

    /**
     * Given Interest per period, number of periods, Present Value, returns Present Value
     * 
     * @param presentValue
     * @param interestPerPeriod
     * @param numberOfPeriods
     * @return
     *     returns double
     */
    @WebMethod(operationName = "FutureValue", action = "http://tempuri.org/dotnet/FinanceService/FutureValue")
    @WebResult(name = "FutureValueResult", targetNamespace = "http://tempuri.org/dotnet/FinanceService")
    @RequestWrapper(localName = "FutureValue", targetNamespace = "http://tempuri.org/dotnet/FinanceService", className = "org.tempuri.dotnet.financeservice.FutureValue")
    @ResponseWrapper(localName = "FutureValueResponse", targetNamespace = "http://tempuri.org/dotnet/FinanceService", className = "org.tempuri.dotnet.financeservice.FutureValueResponse")
    public double futureValue(
        @WebParam(name = "InterestPerPeriod", targetNamespace = "http://tempuri.org/dotnet/FinanceService")
        double interestPerPeriod,
        @WebParam(name = "NumberOfPeriods", targetNamespace = "http://tempuri.org/dotnet/FinanceService")
        int numberOfPeriods,
        @WebParam(name = "PresentValue", targetNamespace = "http://tempuri.org/dotnet/FinanceService")
        double presentValue);

    /**
     * Given Interest Rate, Number of Periods, Present Value, returns periodic payment required
     * 
     * @param presentValue
     * @param interestPerPeriod
     * @param numberOfPeriods
     * @return
     *     returns double
     */
    @WebMethod(operationName = "Payment", action = "http://tempuri.org/dotnet/FinanceService/Payment")
    @WebResult(name = "PaymentResult", targetNamespace = "http://tempuri.org/dotnet/FinanceService")
    @RequestWrapper(localName = "Payment", targetNamespace = "http://tempuri.org/dotnet/FinanceService", className = "org.tempuri.dotnet.financeservice.Payment")
    @ResponseWrapper(localName = "PaymentResponse", targetNamespace = "http://tempuri.org/dotnet/FinanceService", className = "org.tempuri.dotnet.financeservice.PaymentResponse")
    public double payment(
        @WebParam(name = "InterestPerPeriod", targetNamespace = "http://tempuri.org/dotnet/FinanceService")
        double interestPerPeriod,
        @WebParam(name = "NumberOfPeriods", targetNamespace = "http://tempuri.org/dotnet/FinanceService")
        int numberOfPeriods,
        @WebParam(name = "PresentValue", targetNamespace = "http://tempuri.org/dotnet/FinanceService")
        double presentValue);

}
